/**
 * ggplot2-parity tests for deriveGroups() (ported from the M0a-5 spike; decision 0005).
 *
 * Fixtures in ../fixtures/grouping/ are generated by generate.R against real
 * ggplot2 (see each fixture's `provenance` field). Every fixture carries the
 * canonical (first-occurrence-renumbered) group id per input row plus derived
 * expectations (line split counts, stack segments per x, dodge slots per x).
 */
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { deriveGroups, inferDiscreteness, type AesMapping } from "../src/grouping.ts";
import type { CellValue, Columns } from "../src/table.ts";

const FIXTURE_DIR = join(import.meta.dir, "fixtures", "grouping");

interface DataFile {
  columns: Record<string, "string" | "number" | "date">;
  rows: Record<string, string | number>[];
}

interface Fixture {
  case: string;
  description: string;
  provenance: string;
  ggplotCall: string;
  aes: AesMapping;
  expected: {
    rawGgplotGroups: number[];
    canonicalGroups: number[];
    groupCount: number;
  };
  expectedLineCount?: number;
  stackSegmentsPerX?: number[];
  dodgeSlotsPerX?: number[];
}

function loadJson<T>(name: string): T {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf8")) as T;
}

function loadTable(): Columns {
  const data = loadJson<DataFile>("data.json");
  const table: Record<string, CellValue[]> = {};
  for (const [name, type] of Object.entries(data.columns)) {
    table[name] = data.rows.map((row) => {
      const v = row[name]!;
      // date columns arrive as ISO strings; bind them as Date so the
      // discreteness inference sees a temporal (continuous) column, mirroring
      // R's Date class.
      return type === "date" ? new Date(`${String(v)}T00:00:00Z`) : v;
    });
  }
  return table;
}

const table = loadTable();
const fixtureNames = readdirSync(FIXTURE_DIR)
  .filter((f) => /^\d{2}-.*\.json$/.test(f))
  .toSorted();

/** Distinct-group counts per x partition, ordered by sorted x value (matches R factor-level order). */
function groupsPerX(xField: string, groups: readonly number[]): number[] {
  const column = table[xField]!;
  const perX = new Map<string, Set<number>>();
  for (let i = 0; i < groups.length; i++) {
    const key = String(column[i]);
    let set = perX.get(key);
    if (!set) perX.set(key, (set = new Set()));
    set.add(groups[i]!);
  }
  return [...perX.keys()].toSorted().map((k) => perX.get(k)!.size);
}

describe("deriveGroups: ggplot2 parity fixtures", () => {
  expect(fixtureNames.length).toBeGreaterThanOrEqual(10);

  for (const name of fixtureNames) {
    const fixture = loadJson<Fixture>(name);
    test(`${fixture.case} [${fixture.provenance}]`, () => {
      const result = deriveGroups(table, fixture.aes);

      expect([...result.groups]).toEqual(fixture.expected.canonicalGroups);
      expect(result.groupCount).toBe(fixture.expected.groupCount);

      if (fixture.expectedLineCount !== undefined) {
        expect(result.groupCount).toBe(fixture.expectedLineCount);
      }
      if (fixture.stackSegmentsPerX !== undefined) {
        const xField = (fixture.aes["x"] as { field: string }).field;
        expect(groupsPerX(xField, result.groups)).toEqual(fixture.stackSegmentsPerX);
      }
      if (fixture.dodgeSlotsPerX !== undefined) {
        const xField = (fixture.aes["x"] as { field: string }).field;
        expect(groupsPerX(xField, result.groups)).toEqual(fixture.dodgeSlotsPerX);
      }
    });
  }
});

describe("deriveGroups: derivation source", () => {
  test("explicit group override reports source 'explicit'", () => {
    const r = deriveGroups(table, { x: { field: "cat1" }, group: { field: "cat2" } });
    expect(r.source).toBe("explicit");
    expect(r.groupedBy).toEqual(["cat2"]);
    expect(r.groupCount).toBe(2);
  });

  test("no discrete aesthetic reports source 'none'", () => {
    const r = deriveGroups(table, { x: { field: "num1" }, y: { field: "num2" } });
    expect(r.source).toBe("none");
    expect(r.groupCount).toBe(1);
    expect(new Set(r.groups)).toEqual(new Set([0]));
  });

  test("discrete interaction reports source 'derived' with participating fields", () => {
    const r = deriveGroups(table, {
      x: { field: "num1" },
      color: { field: "cat1" },
      linetype: { field: "cat2" },
    });
    expect(r.source).toBe("derived");
    expect(r.groupedBy).toEqual(["cat1", "cat2"]);
    expect(r.groupCount).toBe(6);
  });
});

describe("deriveGroups: discreteness rules", () => {
  test("number columns are continuous by default, discrete when declared", () => {
    const cont = deriveGroups(table, { x: { field: "num1" }, color: { field: "num2" } });
    expect(cont.groupCount).toBe(1);

    const disc = deriveGroups(
      table,
      { x: { field: "num1" }, color: { field: "num2" } },
      { num2: "discrete" },
    );
    expect(disc.groupCount).toBe(12); // all num2 values distinct
  });

  test("string column can be declared continuous to opt out of grouping", () => {
    const r = deriveGroups(
      table,
      { x: { field: "num1" }, color: { field: "cat1" } },
      { cat1: "continuous" },
    );
    expect(r.groupCount).toBe(1);
    expect(r.source).toBe("none");
  });

  test("Date columns are continuous by default", () => {
    const r = deriveGroups(table, { x: { field: "date1" }, y: { field: "num1" } });
    expect(r.source).toBe("none");
    expect(r.groupCount).toBe(1);
  });

  test("boolean columns are discrete", () => {
    const t: Columns = { flag: [true, false, true, false], v: [1, 2, 3, 4] };
    const r = deriveGroups(t, { x: { field: "v" }, color: { field: "flag" } });
    expect(r.source).toBe("derived");
    expect([...r.groups]).toEqual([0, 1, 0, 1]);
  });

  test("inferDiscreteness: mixed column with any string is discrete; nulls carry no type", () => {
    expect(inferDiscreteness([1, 2, "3"])).toBe("discrete");
    expect(inferDiscreteness([null, 1, 2])).toBe("continuous");
    expect(inferDiscreteness([null, null])).toBe("continuous");
  });
});

describe("deriveGroups: edge cases", () => {
  test("multi-field interaction keys keep components separated", () => {
    // SEP must be non-empty so ("a","bc") and ("as","bc") stay distinct under join.
    const t: Columns = {
      a: ["a", "as"],
      b: ["bc", "bc"],
      v: [1, 2],
    };
    const r = deriveGroups(t, { x: { field: "v" }, color: { field: "a" }, fill: { field: "b" } });
    expect(r.groupCount).toBe(2);
    expect([...r.groups]).toEqual([0, 1]);
  });

  test("null forms its own group level", () => {
    const t: Columns = { c: ["a", null, "a", null], v: [1, 2, 3, 4] };
    const r = deriveGroups(t, { x: { field: "v" }, color: { field: "c" } });
    expect([...r.groups]).toEqual([0, 1, 0, 1]);
    expect(r.groupCount).toBe(2);
  });

  test("canonical ids follow first occurrence, not sort order", () => {
    const t: Columns = { c: ["zebra", "apple", "zebra", "mango"] };
    const r = deriveGroups(t, { x: { field: "c" } });
    expect([...r.groups]).toEqual([0, 1, 0, 2]);
  });

  test("numeric explicit group field groups by value", () => {
    const t: Columns = { g: [10, 20, 10, 30], v: [1, 2, 3, 4] };
    const r = deriveGroups(t, { x: { field: "v" }, group: { field: "g" } });
    expect([...r.groups]).toEqual([0, 1, 0, 2]);
    expect(r.source).toBe("explicit");
  });

  test("constant group value yields a single group", () => {
    const r = deriveGroups(table, {
      x: { field: "num1" },
      y: { field: "num2" },
      group: { value: 1 },
    });
    expect(r.groupCount).toBe(1);
    expect(r.source).toBe("explicit");
  });

  test("label channel never participates in grouping", () => {
    const r = deriveGroups(table, {
      x: { field: "num1" },
      y: { field: "num2" },
      label: { field: "cat1" },
    });
    expect(r.source).toBe("none");
    expect(r.groupCount).toBe(1);
  });

  test("zero-row table yields zero groups", () => {
    const r = deriveGroups({ cat1: [] }, { x: { field: "cat1" } });
    expect(r.groupCount).toBe(0);
    expect([...r.groups]).toEqual([]);
  });

  test("zero-row explicit group field yields empty groups and groupCount 0", () => {
    const r = deriveGroups({ g: [] }, { group: { field: "g" } });
    expect(r.source).toBe("explicit");
    expect(r.groupCount).toBe(0);
    expect([...r.groups]).toEqual([]);
  });

  test("zero-row derived discrete field yields empty groups and groupCount 0", () => {
    const r = deriveGroups({ c: [] }, { color: { field: "c" } }, { c: "discrete" });
    expect(r.source).toBe("derived");
    expect(r.groupCount).toBe(0);
    expect([...r.groups]).toEqual([]);
  });

  /**
   * groupCount must not be derived via Math.max(...groups): spreading R ids
   * re-scans every row and can blow the arg-limit (Bun RangeError ~1e6).
   * Guard Math.max arity so both explicit and derived paths stay safe at 1e5.
   */
  test("large-R groupCount avoids Math.max(...groups) on explicit and derived paths", () => {
    const n = 100_000;
    const keys = Array.from({ length: n }, (_, i) => `k${i % 11}`);
    const columns: Columns = { g: keys, c: keys };
    const originalMax = Math.max;
    Math.max = (...args: number[]) => {
      if (args.length > 1_000) {
        throw new Error(`Math.max spread over ${String(args.length)} args (groupCount leak)`);
      }
      return originalMax(...args);
    };
    try {
      const explicit = deriveGroups(columns, { group: { field: "g" } });
      expect(explicit.source).toBe("explicit");
      expect(explicit.groupCount).toBe(11);
      expect(explicit.groups.length).toBe(n);

      const derived = deriveGroups(columns, { color: { field: "c" } }, { c: "discrete" });
      expect(derived.source).toBe("derived");
      expect(derived.groupCount).toBe(11);
      expect(derived.groups.length).toBe(n);
    } finally {
      Math.max = originalMax;
    }
  });

  test("unknown field throws", () => {
    expect(() => deriveGroups(table, { x: { field: "nope" } })).toThrow(/unknown field/);
  });

  test("unequal column lengths throw", () => {
    expect(() => deriveGroups({ a: [1], b: [1, 2] }, { x: { field: "a" } })).toThrow(/unequal/);
  });
});
