/**
 * Andre-Michel Guerry's "Essai sur la statistique morale de la France" (1833),
 * the founding work of moral statistics: 86 departments scored on crime,
 * literacy, wealth and much else, drawn from the first national crime records
 * in Europe.
 *
 * Guerry's finding was the uncomfortable one - departments with more literate
 * conscripts did not have less crime. Ranks run 1 = worst, 86 = best, so higher
 * is better throughout.
 *
 * Transcribed from HistData::Guerry (see NOTICE); 86 rows. Corsica has no
 * region in the source and is omitted rather than shown as an unlabelled group.
 */
export const guerry = [
  { department: "Ain", region: "East", literacy: 37, crimePersons: 28870, wealth: 73 },
  { department: "Aisne", region: "North", literacy: 51, crimePersons: 26226, wealth: 22 },
  { department: "Allier", region: "Centre", literacy: 13, crimePersons: 26747, wealth: 61 },
  { department: "Basses-Alpes", region: "East", literacy: 46, crimePersons: 12935, wealth: 76 },
  { department: "Hautes-Alpes", region: "East", literacy: 69, crimePersons: 17488, wealth: 83 },
  { department: "Ardeche", region: "South", literacy: 27, crimePersons: 9474, wealth: 84 },
  { department: "Ardennes", region: "North", literacy: 67, crimePersons: 35203, wealth: 33 },
  { department: "Ariege", region: "South", literacy: 18, crimePersons: 6173, wealth: 72 },
  { department: "Aube", region: "East", literacy: 59, crimePersons: 19602, wealth: 14 },
  { department: "Aude", region: "South", literacy: 34, crimePersons: 15647, wealth: 17 },
  { department: "Aveyron", region: "South", literacy: 31, crimePersons: 8236, wealth: 50 },
  { department: "Bouches-du-Rhone", region: "South", literacy: 38, crimePersons: 13409, wealth: 2 },
  { department: "Calvados", region: "North", literacy: 52, crimePersons: 17577, wealth: 10 },
  { department: "Cantal", region: "Centre", literacy: 31, crimePersons: 18070, wealth: 59 },
  { department: "Charente", region: "West", literacy: 36, crimePersons: 24964, wealth: 86 },
  {
    department: "Charente-Inferieure",
    region: "West",
    literacy: 39,
    crimePersons: 18712,
    wealth: 18,
  },
  { department: "Cher", region: "Centre", literacy: 13, crimePersons: 21934, wealth: 63 },
  { department: "Correze", region: "Centre", literacy: 12, crimePersons: 15262, wealth: 74 },
  { department: "Cote-d'Or", region: "East", literacy: 60, crimePersons: 32256, wealth: 16 },
  { department: "Cotes-du-Nord", region: "West", literacy: 16, crimePersons: 28607, wealth: 70 },
  { department: "Creuse", region: "Centre", literacy: 23, crimePersons: 37014, wealth: 78 },
  { department: "Dordogne", region: "West", literacy: 18, crimePersons: 21585, wealth: 60 },
  { department: "Doubs", region: "East", literacy: 73, crimePersons: 11560, wealth: 31 },
  { department: "Drome", region: "East", literacy: 42, crimePersons: 13396, wealth: 66 },
  { department: "Eure", region: "North", literacy: 51, crimePersons: 14795, wealth: 20 },
  { department: "Eure-et-Loir", region: "Centre", literacy: 54, crimePersons: 21368, wealth: 11 },
  { department: "Finistere", region: "West", literacy: 15, crimePersons: 29872, wealth: 36 },
  { department: "Gard", region: "South", literacy: 40, crimePersons: 13115, wealth: 26 },
  { department: "Haute-Garonne", region: "South", literacy: 31, crimePersons: 18642, wealth: 23 },
  { department: "Gers", region: "South", literacy: 38, crimePersons: 18642, wealth: 40 },
  { department: "Gironde", region: "West", literacy: 40, crimePersons: 24096, wealth: 8 },
  { department: "Herault", region: "South", literacy: 45, crimePersons: 12814, wealth: 12 },
  { department: "Ille-et-Vilaine", region: "West", literacy: 25, crimePersons: 22138, wealth: 55 },
  { department: "Indre", region: "Centre", literacy: 17, crimePersons: 32404, wealth: 54 },
  { department: "Indre-et-Loire", region: "Centre", literacy: 27, crimePersons: 19131, wealth: 27 },
  { department: "Isere", region: "East", literacy: 29, crimePersons: 18785, wealth: 65 },
  { department: "Jura", region: "East", literacy: 73, crimePersons: 26221, wealth: 62 },
  { department: "Landes", region: "West", literacy: 28, crimePersons: 17687, wealth: 81 },
  { department: "Loir-et-Cher", region: "Centre", literacy: 27, crimePersons: 21292, wealth: 19 },
  { department: "Loire", region: "Centre", literacy: 29, crimePersons: 27491, wealth: 24 },
  { department: "Haute-Loire", region: "Centre", literacy: 21, crimePersons: 16170, wealth: 75 },
  { department: "Loire-Inferieure", region: "West", literacy: 24, crimePersons: 19314, wealth: 80 },
  { department: "Loiret", region: "Centre", literacy: 42, crimePersons: 17722, wealth: 9 },
  { department: "Lot", region: "South", literacy: 24, crimePersons: 5883, wealth: 42 },
  { department: "Lot-et-Garonne", region: "West", literacy: 31, crimePersons: 22969, wealth: 7 },
  { department: "Lozere", region: "South", literacy: 27, crimePersons: 7710, wealth: 77 },
  { department: "Maine-et-Loire", region: "West", literacy: 23, crimePersons: 29692, wealth: 34 },
  { department: "Manche", region: "North", literacy: 43, crimePersons: 31078, wealth: 32 },
  { department: "Marne", region: "North", literacy: 63, crimePersons: 15602, wealth: 13 },
  { department: "Haute-Marne", region: "East", literacy: 72, crimePersons: 26231, wealth: 25 },
  { department: "Mayenne", region: "West", literacy: 19, crimePersons: 28331, wealth: 38 },
  { department: "Meurthe", region: "East", literacy: 68, crimePersons: 26674, wealth: 57 },
  { department: "Meuse", region: "North", literacy: 74, crimePersons: 24507, wealth: 52 },
  { department: "Morbihan", region: "West", literacy: 14, crimePersons: 23316, wealth: 48 },
  { department: "Moselle", region: "North", literacy: 57, crimePersons: 12153, wealth: 53 },
  { department: "Nievre", region: "Centre", literacy: 20, crimePersons: 25087, wealth: 44 },
  { department: "Nord", region: "North", literacy: 45, crimePersons: 26740, wealth: 28 },
  { department: "Oise", region: "North", literacy: 54, crimePersons: 28180, wealth: 15 },
  { department: "Orne", region: "North", literacy: 45, crimePersons: 28329, wealth: 35 },
  { department: "Pas-de-Calais", region: "North", literacy: 49, crimePersons: 23101, wealth: 45 },
  { department: "Puy-de-Dome", region: "Centre", literacy: 19, crimePersons: 17256, wealth: 51 },
  { department: "Basses-Pyrenees", region: "West", literacy: 47, crimePersons: 16722, wealth: 79 },
  { department: "Hautes-Pyrenees", region: "South", literacy: 53, crimePersons: 12223, wealth: 85 },
  {
    department: "Pyrenees-Orientales",
    region: "South",
    literacy: 31,
    crimePersons: 6728,
    wealth: 71,
  },
  { department: "Bas-Rhin", region: "East", literacy: 62, crimePersons: 12309, wealth: 46 },
  { department: "Haut-Rhin", region: "East", literacy: 71, crimePersons: 7343, wealth: 58 },
  { department: "Rhone", region: "East", literacy: 45, crimePersons: 18793, wealth: 6 },
  { department: "Haute-Saone", region: "East", literacy: 59, crimePersons: 22339, wealth: 69 },
  { department: "Saone-et-Loire", region: "East", literacy: 32, crimePersons: 28391, wealth: 49 },
  { department: "Sarthe", region: "Centre", literacy: 30, crimePersons: 33913, wealth: 41 },
  { department: "Seine", region: "North", literacy: 71, crimePersons: 13945, wealth: 1 },
  { department: "Seine-Inferieure", region: "North", literacy: 43, crimePersons: 18355, wealth: 3 },
  { department: "Seine-et-Marne", region: "North", literacy: 54, crimePersons: 22201, wealth: 4 },
  { department: "Seine-et-Oise", region: "North", literacy: 56, crimePersons: 12477, wealth: 5 },
  { department: "Deux-Sevres", region: "West", literacy: 41, crimePersons: 18400, wealth: 39 },
  { department: "Somme", region: "North", literacy: 44, crimePersons: 33592, wealth: 21 },
  { department: "Tarn", region: "South", literacy: 20, crimePersons: 13019, wealth: 47 },
  { department: "Tarn-et-Garonne", region: "South", literacy: 25, crimePersons: 14790, wealth: 29 },
  { department: "Var", region: "South", literacy: 23, crimePersons: 13145, wealth: 43 },
  { department: "Vaucluse", region: "South", literacy: 37, crimePersons: 13576, wealth: 64 },
  { department: "Vendee", region: "West", literacy: 28, crimePersons: 20827, wealth: 56 },
  { department: "Vienne", region: "West", literacy: 25, crimePersons: 15010, wealth: 68 },
  { department: "Haute-Vienne", region: "Centre", literacy: 13, crimePersons: 16256, wealth: 67 },
  { department: "Vosges", region: "East", literacy: 62, crimePersons: 18835, wealth: 82 },
  { department: "Yonne", region: "Centre", literacy: 47, crimePersons: 18006, wealth: 30 },
] as const;
