/**
 * The Palmer Archipelago penguins: body measurements for 344 adult foraging
 * penguins of three species, collected by Dr Kristen Gorman at Palmer Station,
 * Antarctica, between 2007 and 2009 as part of the Long Term Ecological
 * Research network. Released by Allison Horst, Alison Hill and Kristen Gorman
 * as the palmerpenguins R package under CC0 (see NOTICE).
 *
 * The 11 rows missing a measurement or a sex are dropped, leaving 333: 146
 * Adelie, 119 Gentoo, 68 Chinstrap, across the Biscoe, Dream and Torgersen
 * islands. `id` is stable and unique, which is what the interaction key
 * contract needs.
 */
export const penguins: {
  id: string;
  species: string;
  island: string;
  flipper: number;
  mass: number;
  bill: number;
  sex: string;
}[] = [
  {
    id: "adelie-001",
    species: "Adelie",
    island: "Torgersen",
    flipper: 181,
    mass: 3750,
    bill: 39.1,
    sex: "male",
  },
  {
    id: "adelie-002",
    species: "Adelie",
    island: "Torgersen",
    flipper: 186,
    mass: 3800,
    bill: 39.5,
    sex: "female",
  },
  {
    id: "adelie-003",
    species: "Adelie",
    island: "Torgersen",
    flipper: 195,
    mass: 3250,
    bill: 40.3,
    sex: "female",
  },
  {
    id: "adelie-004",
    species: "Adelie",
    island: "Torgersen",
    flipper: 193,
    mass: 3450,
    bill: 36.7,
    sex: "female",
  },
  {
    id: "adelie-005",
    species: "Adelie",
    island: "Torgersen",
    flipper: 190,
    mass: 3650,
    bill: 39.3,
    sex: "male",
  },
  {
    id: "adelie-006",
    species: "Adelie",
    island: "Torgersen",
    flipper: 181,
    mass: 3625,
    bill: 38.9,
    sex: "female",
  },
  {
    id: "adelie-007",
    species: "Adelie",
    island: "Torgersen",
    flipper: 195,
    mass: 4675,
    bill: 39.2,
    sex: "male",
  },
  {
    id: "adelie-008",
    species: "Adelie",
    island: "Torgersen",
    flipper: 182,
    mass: 3200,
    bill: 41.1,
    sex: "female",
  },
  {
    id: "adelie-009",
    species: "Adelie",
    island: "Torgersen",
    flipper: 191,
    mass: 3800,
    bill: 38.6,
    sex: "male",
  },
  {
    id: "adelie-010",
    species: "Adelie",
    island: "Torgersen",
    flipper: 198,
    mass: 4400,
    bill: 34.6,
    sex: "male",
  },
  {
    id: "adelie-011",
    species: "Adelie",
    island: "Torgersen",
    flipper: 185,
    mass: 3700,
    bill: 36.6,
    sex: "female",
  },
  {
    id: "adelie-012",
    species: "Adelie",
    island: "Torgersen",
    flipper: 195,
    mass: 3450,
    bill: 38.7,
    sex: "female",
  },
  {
    id: "adelie-013",
    species: "Adelie",
    island: "Torgersen",
    flipper: 197,
    mass: 4500,
    bill: 42.5,
    sex: "male",
  },
  {
    id: "adelie-014",
    species: "Adelie",
    island: "Torgersen",
    flipper: 184,
    mass: 3325,
    bill: 34.4,
    sex: "female",
  },
  {
    id: "adelie-015",
    species: "Adelie",
    island: "Torgersen",
    flipper: 194,
    mass: 4200,
    bill: 46,
    sex: "male",
  },
  {
    id: "adelie-016",
    species: "Adelie",
    island: "Biscoe",
    flipper: 174,
    mass: 3400,
    bill: 37.8,
    sex: "female",
  },
  {
    id: "adelie-017",
    species: "Adelie",
    island: "Biscoe",
    flipper: 180,
    mass: 3600,
    bill: 37.7,
    sex: "male",
  },
  {
    id: "adelie-018",
    species: "Adelie",
    island: "Biscoe",
    flipper: 189,
    mass: 3800,
    bill: 35.9,
    sex: "female",
  },
  {
    id: "adelie-019",
    species: "Adelie",
    island: "Biscoe",
    flipper: 185,
    mass: 3950,
    bill: 38.2,
    sex: "male",
  },
  {
    id: "adelie-020",
    species: "Adelie",
    island: "Biscoe",
    flipper: 180,
    mass: 3800,
    bill: 38.8,
    sex: "male",
  },
  {
    id: "adelie-021",
    species: "Adelie",
    island: "Biscoe",
    flipper: 187,
    mass: 3800,
    bill: 35.3,
    sex: "female",
  },
  {
    id: "adelie-022",
    species: "Adelie",
    island: "Biscoe",
    flipper: 183,
    mass: 3550,
    bill: 40.6,
    sex: "male",
  },
  {
    id: "adelie-023",
    species: "Adelie",
    island: "Biscoe",
    flipper: 187,
    mass: 3200,
    bill: 40.5,
    sex: "female",
  },
  {
    id: "adelie-024",
    species: "Adelie",
    island: "Biscoe",
    flipper: 172,
    mass: 3150,
    bill: 37.9,
    sex: "female",
  },
  {
    id: "adelie-025",
    species: "Adelie",
    island: "Biscoe",
    flipper: 180,
    mass: 3950,
    bill: 40.5,
    sex: "male",
  },
  {
    id: "adelie-026",
    species: "Adelie",
    island: "Dream",
    flipper: 178,
    mass: 3250,
    bill: 39.5,
    sex: "female",
  },
  {
    id: "adelie-027",
    species: "Adelie",
    island: "Dream",
    flipper: 178,
    mass: 3900,
    bill: 37.2,
    sex: "male",
  },
  {
    id: "adelie-028",
    species: "Adelie",
    island: "Dream",
    flipper: 188,
    mass: 3300,
    bill: 39.5,
    sex: "female",
  },
  {
    id: "adelie-029",
    species: "Adelie",
    island: "Dream",
    flipper: 184,
    mass: 3900,
    bill: 40.9,
    sex: "male",
  },
  {
    id: "adelie-030",
    species: "Adelie",
    island: "Dream",
    flipper: 195,
    mass: 3325,
    bill: 36.4,
    sex: "female",
  },
  {
    id: "adelie-031",
    species: "Adelie",
    island: "Dream",
    flipper: 196,
    mass: 4150,
    bill: 39.2,
    sex: "male",
  },
  {
    id: "adelie-032",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 3950,
    bill: 38.8,
    sex: "male",
  },
  {
    id: "adelie-033",
    species: "Adelie",
    island: "Dream",
    flipper: 180,
    mass: 3550,
    bill: 42.2,
    sex: "female",
  },
  {
    id: "adelie-034",
    species: "Adelie",
    island: "Dream",
    flipper: 181,
    mass: 3300,
    bill: 37.6,
    sex: "female",
  },
  {
    id: "adelie-035",
    species: "Adelie",
    island: "Dream",
    flipper: 184,
    mass: 4650,
    bill: 39.8,
    sex: "male",
  },
  {
    id: "adelie-036",
    species: "Adelie",
    island: "Dream",
    flipper: 182,
    mass: 3150,
    bill: 36.5,
    sex: "female",
  },
  {
    id: "adelie-037",
    species: "Adelie",
    island: "Dream",
    flipper: 195,
    mass: 3900,
    bill: 40.8,
    sex: "male",
  },
  {
    id: "adelie-038",
    species: "Adelie",
    island: "Dream",
    flipper: 186,
    mass: 3100,
    bill: 36,
    sex: "female",
  },
  {
    id: "adelie-039",
    species: "Adelie",
    island: "Dream",
    flipper: 196,
    mass: 4400,
    bill: 44.1,
    sex: "male",
  },
  {
    id: "adelie-040",
    species: "Adelie",
    island: "Dream",
    flipper: 185,
    mass: 3000,
    bill: 37,
    sex: "female",
  },
  {
    id: "adelie-041",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 4600,
    bill: 39.6,
    sex: "male",
  },
  {
    id: "adelie-042",
    species: "Adelie",
    island: "Dream",
    flipper: 182,
    mass: 3425,
    bill: 41.1,
    sex: "male",
  },
  {
    id: "adelie-043",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 3450,
    bill: 36,
    sex: "female",
  },
  {
    id: "adelie-044",
    species: "Adelie",
    island: "Dream",
    flipper: 191,
    mass: 4150,
    bill: 42.3,
    sex: "male",
  },
  {
    id: "adelie-045",
    species: "Adelie",
    island: "Biscoe",
    flipper: 186,
    mass: 3500,
    bill: 39.6,
    sex: "female",
  },
  {
    id: "adelie-046",
    species: "Adelie",
    island: "Biscoe",
    flipper: 188,
    mass: 4300,
    bill: 40.1,
    sex: "male",
  },
  {
    id: "adelie-047",
    species: "Adelie",
    island: "Biscoe",
    flipper: 190,
    mass: 3450,
    bill: 35,
    sex: "female",
  },
  {
    id: "adelie-048",
    species: "Adelie",
    island: "Biscoe",
    flipper: 200,
    mass: 4050,
    bill: 42,
    sex: "male",
  },
  {
    id: "adelie-049",
    species: "Adelie",
    island: "Biscoe",
    flipper: 187,
    mass: 2900,
    bill: 34.5,
    sex: "female",
  },
  {
    id: "adelie-050",
    species: "Adelie",
    island: "Biscoe",
    flipper: 191,
    mass: 3700,
    bill: 41.4,
    sex: "male",
  },
  {
    id: "adelie-051",
    species: "Adelie",
    island: "Biscoe",
    flipper: 186,
    mass: 3550,
    bill: 39,
    sex: "female",
  },
  {
    id: "adelie-052",
    species: "Adelie",
    island: "Biscoe",
    flipper: 193,
    mass: 3800,
    bill: 40.6,
    sex: "male",
  },
  {
    id: "adelie-053",
    species: "Adelie",
    island: "Biscoe",
    flipper: 181,
    mass: 2850,
    bill: 36.5,
    sex: "female",
  },
  {
    id: "adelie-054",
    species: "Adelie",
    island: "Biscoe",
    flipper: 194,
    mass: 3750,
    bill: 37.6,
    sex: "male",
  },
  {
    id: "adelie-055",
    species: "Adelie",
    island: "Biscoe",
    flipper: 185,
    mass: 3150,
    bill: 35.7,
    sex: "female",
  },
  {
    id: "adelie-056",
    species: "Adelie",
    island: "Biscoe",
    flipper: 195,
    mass: 4400,
    bill: 41.3,
    sex: "male",
  },
  {
    id: "adelie-057",
    species: "Adelie",
    island: "Biscoe",
    flipper: 185,
    mass: 3600,
    bill: 37.6,
    sex: "female",
  },
  {
    id: "adelie-058",
    species: "Adelie",
    island: "Biscoe",
    flipper: 192,
    mass: 4050,
    bill: 41.1,
    sex: "male",
  },
  {
    id: "adelie-059",
    species: "Adelie",
    island: "Biscoe",
    flipper: 184,
    mass: 2850,
    bill: 36.4,
    sex: "female",
  },
  {
    id: "adelie-060",
    species: "Adelie",
    island: "Biscoe",
    flipper: 192,
    mass: 3950,
    bill: 41.6,
    sex: "male",
  },
  {
    id: "adelie-061",
    species: "Adelie",
    island: "Biscoe",
    flipper: 195,
    mass: 3350,
    bill: 35.5,
    sex: "female",
  },
  {
    id: "adelie-062",
    species: "Adelie",
    island: "Biscoe",
    flipper: 188,
    mass: 4100,
    bill: 41.1,
    sex: "male",
  },
  {
    id: "adelie-063",
    species: "Adelie",
    island: "Torgersen",
    flipper: 190,
    mass: 3050,
    bill: 35.9,
    sex: "female",
  },
  {
    id: "adelie-064",
    species: "Adelie",
    island: "Torgersen",
    flipper: 198,
    mass: 4450,
    bill: 41.8,
    sex: "male",
  },
  {
    id: "adelie-065",
    species: "Adelie",
    island: "Torgersen",
    flipper: 190,
    mass: 3600,
    bill: 33.5,
    sex: "female",
  },
  {
    id: "adelie-066",
    species: "Adelie",
    island: "Torgersen",
    flipper: 190,
    mass: 3900,
    bill: 39.7,
    sex: "male",
  },
  {
    id: "adelie-067",
    species: "Adelie",
    island: "Torgersen",
    flipper: 196,
    mass: 3550,
    bill: 39.6,
    sex: "female",
  },
  {
    id: "adelie-068",
    species: "Adelie",
    island: "Torgersen",
    flipper: 197,
    mass: 4150,
    bill: 45.8,
    sex: "male",
  },
  {
    id: "adelie-069",
    species: "Adelie",
    island: "Torgersen",
    flipper: 190,
    mass: 3700,
    bill: 35.5,
    sex: "female",
  },
  {
    id: "adelie-070",
    species: "Adelie",
    island: "Torgersen",
    flipper: 195,
    mass: 4250,
    bill: 42.8,
    sex: "male",
  },
  {
    id: "adelie-071",
    species: "Adelie",
    island: "Torgersen",
    flipper: 191,
    mass: 3700,
    bill: 40.9,
    sex: "female",
  },
  {
    id: "adelie-072",
    species: "Adelie",
    island: "Torgersen",
    flipper: 184,
    mass: 3900,
    bill: 37.2,
    sex: "male",
  },
  {
    id: "adelie-073",
    species: "Adelie",
    island: "Torgersen",
    flipper: 187,
    mass: 3550,
    bill: 36.2,
    sex: "female",
  },
  {
    id: "adelie-074",
    species: "Adelie",
    island: "Torgersen",
    flipper: 195,
    mass: 4000,
    bill: 42.1,
    sex: "male",
  },
  {
    id: "adelie-075",
    species: "Adelie",
    island: "Torgersen",
    flipper: 189,
    mass: 3200,
    bill: 34.6,
    sex: "female",
  },
  {
    id: "adelie-076",
    species: "Adelie",
    island: "Torgersen",
    flipper: 196,
    mass: 4700,
    bill: 42.9,
    sex: "male",
  },
  {
    id: "adelie-077",
    species: "Adelie",
    island: "Torgersen",
    flipper: 187,
    mass: 3800,
    bill: 36.7,
    sex: "female",
  },
  {
    id: "adelie-078",
    species: "Adelie",
    island: "Torgersen",
    flipper: 193,
    mass: 4200,
    bill: 35.1,
    sex: "male",
  },
  {
    id: "adelie-079",
    species: "Adelie",
    island: "Dream",
    flipper: 191,
    mass: 3350,
    bill: 37.3,
    sex: "female",
  },
  {
    id: "adelie-080",
    species: "Adelie",
    island: "Dream",
    flipper: 194,
    mass: 3550,
    bill: 41.3,
    sex: "male",
  },
  {
    id: "adelie-081",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 3800,
    bill: 36.3,
    sex: "male",
  },
  {
    id: "adelie-082",
    species: "Adelie",
    island: "Dream",
    flipper: 189,
    mass: 3500,
    bill: 36.9,
    sex: "female",
  },
  {
    id: "adelie-083",
    species: "Adelie",
    island: "Dream",
    flipper: 189,
    mass: 3950,
    bill: 38.3,
    sex: "male",
  },
  {
    id: "adelie-084",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 3600,
    bill: 38.9,
    sex: "female",
  },
  {
    id: "adelie-085",
    species: "Adelie",
    island: "Dream",
    flipper: 202,
    mass: 3550,
    bill: 35.7,
    sex: "female",
  },
  {
    id: "adelie-086",
    species: "Adelie",
    island: "Dream",
    flipper: 205,
    mass: 4300,
    bill: 41.1,
    sex: "male",
  },
  {
    id: "adelie-087",
    species: "Adelie",
    island: "Dream",
    flipper: 185,
    mass: 3400,
    bill: 34,
    sex: "female",
  },
  {
    id: "adelie-088",
    species: "Adelie",
    island: "Dream",
    flipper: 186,
    mass: 4450,
    bill: 39.6,
    sex: "male",
  },
  {
    id: "adelie-089",
    species: "Adelie",
    island: "Dream",
    flipper: 187,
    mass: 3300,
    bill: 36.2,
    sex: "female",
  },
  {
    id: "adelie-090",
    species: "Adelie",
    island: "Dream",
    flipper: 208,
    mass: 4300,
    bill: 40.8,
    sex: "male",
  },
  {
    id: "adelie-091",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 3700,
    bill: 38.1,
    sex: "female",
  },
  {
    id: "adelie-092",
    species: "Adelie",
    island: "Dream",
    flipper: 196,
    mass: 4350,
    bill: 40.3,
    sex: "male",
  },
  {
    id: "adelie-093",
    species: "Adelie",
    island: "Dream",
    flipper: 178,
    mass: 2900,
    bill: 33.1,
    sex: "female",
  },
  {
    id: "adelie-094",
    species: "Adelie",
    island: "Dream",
    flipper: 192,
    mass: 4100,
    bill: 43.2,
    sex: "male",
  },
  {
    id: "adelie-095",
    species: "Adelie",
    island: "Biscoe",
    flipper: 192,
    mass: 3725,
    bill: 35,
    sex: "female",
  },
  {
    id: "adelie-096",
    species: "Adelie",
    island: "Biscoe",
    flipper: 203,
    mass: 4725,
    bill: 41,
    sex: "male",
  },
  {
    id: "adelie-097",
    species: "Adelie",
    island: "Biscoe",
    flipper: 183,
    mass: 3075,
    bill: 37.7,
    sex: "female",
  },
  {
    id: "adelie-098",
    species: "Adelie",
    island: "Biscoe",
    flipper: 190,
    mass: 4250,
    bill: 37.8,
    sex: "male",
  },
  {
    id: "adelie-099",
    species: "Adelie",
    island: "Biscoe",
    flipper: 193,
    mass: 2925,
    bill: 37.9,
    sex: "female",
  },
  {
    id: "adelie-100",
    species: "Adelie",
    island: "Biscoe",
    flipper: 184,
    mass: 3550,
    bill: 39.7,
    sex: "male",
  },
  {
    id: "adelie-101",
    species: "Adelie",
    island: "Biscoe",
    flipper: 199,
    mass: 3750,
    bill: 38.6,
    sex: "female",
  },
  {
    id: "adelie-102",
    species: "Adelie",
    island: "Biscoe",
    flipper: 190,
    mass: 3900,
    bill: 38.2,
    sex: "male",
  },
  {
    id: "adelie-103",
    species: "Adelie",
    island: "Biscoe",
    flipper: 181,
    mass: 3175,
    bill: 38.1,
    sex: "female",
  },
  {
    id: "adelie-104",
    species: "Adelie",
    island: "Biscoe",
    flipper: 197,
    mass: 4775,
    bill: 43.2,
    sex: "male",
  },
  {
    id: "adelie-105",
    species: "Adelie",
    island: "Biscoe",
    flipper: 198,
    mass: 3825,
    bill: 38.1,
    sex: "female",
  },
  {
    id: "adelie-106",
    species: "Adelie",
    island: "Biscoe",
    flipper: 191,
    mass: 4600,
    bill: 45.6,
    sex: "male",
  },
  {
    id: "adelie-107",
    species: "Adelie",
    island: "Biscoe",
    flipper: 193,
    mass: 3200,
    bill: 39.7,
    sex: "female",
  },
  {
    id: "adelie-108",
    species: "Adelie",
    island: "Biscoe",
    flipper: 197,
    mass: 4275,
    bill: 42.2,
    sex: "male",
  },
  {
    id: "adelie-109",
    species: "Adelie",
    island: "Biscoe",
    flipper: 191,
    mass: 3900,
    bill: 39.6,
    sex: "female",
  },
  {
    id: "adelie-110",
    species: "Adelie",
    island: "Biscoe",
    flipper: 196,
    mass: 4075,
    bill: 42.7,
    sex: "male",
  },
  {
    id: "adelie-111",
    species: "Adelie",
    island: "Torgersen",
    flipper: 188,
    mass: 2900,
    bill: 38.6,
    sex: "female",
  },
  {
    id: "adelie-112",
    species: "Adelie",
    island: "Torgersen",
    flipper: 199,
    mass: 3775,
    bill: 37.3,
    sex: "male",
  },
  {
    id: "adelie-113",
    species: "Adelie",
    island: "Torgersen",
    flipper: 189,
    mass: 3350,
    bill: 35.7,
    sex: "female",
  },
  {
    id: "adelie-114",
    species: "Adelie",
    island: "Torgersen",
    flipper: 189,
    mass: 3325,
    bill: 41.1,
    sex: "male",
  },
  {
    id: "adelie-115",
    species: "Adelie",
    island: "Torgersen",
    flipper: 187,
    mass: 3150,
    bill: 36.2,
    sex: "female",
  },
  {
    id: "adelie-116",
    species: "Adelie",
    island: "Torgersen",
    flipper: 198,
    mass: 3500,
    bill: 37.7,
    sex: "male",
  },
  {
    id: "adelie-117",
    species: "Adelie",
    island: "Torgersen",
    flipper: 176,
    mass: 3450,
    bill: 40.2,
    sex: "female",
  },
  {
    id: "adelie-118",
    species: "Adelie",
    island: "Torgersen",
    flipper: 202,
    mass: 3875,
    bill: 41.4,
    sex: "male",
  },
  {
    id: "adelie-119",
    species: "Adelie",
    island: "Torgersen",
    flipper: 186,
    mass: 3050,
    bill: 35.2,
    sex: "female",
  },
  {
    id: "adelie-120",
    species: "Adelie",
    island: "Torgersen",
    flipper: 199,
    mass: 4000,
    bill: 40.6,
    sex: "male",
  },
  {
    id: "adelie-121",
    species: "Adelie",
    island: "Torgersen",
    flipper: 191,
    mass: 3275,
    bill: 38.8,
    sex: "female",
  },
  {
    id: "adelie-122",
    species: "Adelie",
    island: "Torgersen",
    flipper: 195,
    mass: 4300,
    bill: 41.5,
    sex: "male",
  },
  {
    id: "adelie-123",
    species: "Adelie",
    island: "Torgersen",
    flipper: 191,
    mass: 3050,
    bill: 39,
    sex: "female",
  },
  {
    id: "adelie-124",
    species: "Adelie",
    island: "Torgersen",
    flipper: 210,
    mass: 4000,
    bill: 44.1,
    sex: "male",
  },
  {
    id: "adelie-125",
    species: "Adelie",
    island: "Torgersen",
    flipper: 190,
    mass: 3325,
    bill: 38.5,
    sex: "female",
  },
  {
    id: "adelie-126",
    species: "Adelie",
    island: "Torgersen",
    flipper: 197,
    mass: 3500,
    bill: 43.1,
    sex: "male",
  },
  {
    id: "adelie-127",
    species: "Adelie",
    island: "Dream",
    flipper: 193,
    mass: 3500,
    bill: 36.8,
    sex: "female",
  },
  {
    id: "adelie-128",
    species: "Adelie",
    island: "Dream",
    flipper: 199,
    mass: 4475,
    bill: 37.5,
    sex: "male",
  },
  {
    id: "adelie-129",
    species: "Adelie",
    island: "Dream",
    flipper: 187,
    mass: 3425,
    bill: 38.1,
    sex: "female",
  },
  {
    id: "adelie-130",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 3900,
    bill: 41.1,
    sex: "male",
  },
  {
    id: "adelie-131",
    species: "Adelie",
    island: "Dream",
    flipper: 191,
    mass: 3175,
    bill: 35.6,
    sex: "female",
  },
  {
    id: "adelie-132",
    species: "Adelie",
    island: "Dream",
    flipper: 200,
    mass: 3975,
    bill: 40.2,
    sex: "male",
  },
  {
    id: "adelie-133",
    species: "Adelie",
    island: "Dream",
    flipper: 185,
    mass: 3400,
    bill: 37,
    sex: "female",
  },
  {
    id: "adelie-134",
    species: "Adelie",
    island: "Dream",
    flipper: 193,
    mass: 4250,
    bill: 39.7,
    sex: "male",
  },
  {
    id: "adelie-135",
    species: "Adelie",
    island: "Dream",
    flipper: 193,
    mass: 3400,
    bill: 40.2,
    sex: "female",
  },
  {
    id: "adelie-136",
    species: "Adelie",
    island: "Dream",
    flipper: 187,
    mass: 3475,
    bill: 40.6,
    sex: "male",
  },
  {
    id: "adelie-137",
    species: "Adelie",
    island: "Dream",
    flipper: 188,
    mass: 3050,
    bill: 32.1,
    sex: "female",
  },
  {
    id: "adelie-138",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 3725,
    bill: 40.7,
    sex: "male",
  },
  {
    id: "adelie-139",
    species: "Adelie",
    island: "Dream",
    flipper: 192,
    mass: 3000,
    bill: 37.3,
    sex: "female",
  },
  {
    id: "adelie-140",
    species: "Adelie",
    island: "Dream",
    flipper: 185,
    mass: 3650,
    bill: 39,
    sex: "male",
  },
  {
    id: "adelie-141",
    species: "Adelie",
    island: "Dream",
    flipper: 190,
    mass: 4250,
    bill: 39.2,
    sex: "male",
  },
  {
    id: "adelie-142",
    species: "Adelie",
    island: "Dream",
    flipper: 184,
    mass: 3475,
    bill: 36.6,
    sex: "female",
  },
  {
    id: "adelie-143",
    species: "Adelie",
    island: "Dream",
    flipper: 195,
    mass: 3450,
    bill: 36,
    sex: "female",
  },
  {
    id: "adelie-144",
    species: "Adelie",
    island: "Dream",
    flipper: 193,
    mass: 3750,
    bill: 37.8,
    sex: "male",
  },
  {
    id: "adelie-145",
    species: "Adelie",
    island: "Dream",
    flipper: 187,
    mass: 3700,
    bill: 36,
    sex: "female",
  },
  {
    id: "adelie-146",
    species: "Adelie",
    island: "Dream",
    flipper: 201,
    mass: 4000,
    bill: 41.5,
    sex: "male",
  },
  {
    id: "gentoo-001",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 211,
    mass: 4500,
    bill: 46.1,
    sex: "female",
  },
  {
    id: "gentoo-002",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 230,
    mass: 5700,
    bill: 50,
    sex: "male",
  },
  {
    id: "gentoo-003",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4450,
    bill: 48.7,
    sex: "female",
  },
  {
    id: "gentoo-004",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 218,
    mass: 5700,
    bill: 50,
    sex: "male",
  },
  {
    id: "gentoo-005",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5400,
    bill: 47.6,
    sex: "male",
  },
  {
    id: "gentoo-006",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4550,
    bill: 46.5,
    sex: "female",
  },
  {
    id: "gentoo-007",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 211,
    mass: 4800,
    bill: 45.4,
    sex: "female",
  },
  {
    id: "gentoo-008",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 219,
    mass: 5200,
    bill: 46.7,
    sex: "male",
  },
  {
    id: "gentoo-009",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 209,
    mass: 4400,
    bill: 43.3,
    sex: "female",
  },
  {
    id: "gentoo-010",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5150,
    bill: 46.8,
    sex: "male",
  },
  {
    id: "gentoo-011",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 214,
    mass: 4650,
    bill: 40.9,
    sex: "female",
  },
  {
    id: "gentoo-012",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 216,
    mass: 5550,
    bill: 49,
    sex: "male",
  },
  {
    id: "gentoo-013",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 214,
    mass: 4650,
    bill: 45.5,
    sex: "female",
  },
  {
    id: "gentoo-014",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 213,
    mass: 5850,
    bill: 48.4,
    sex: "male",
  },
  {
    id: "gentoo-015",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4200,
    bill: 45.8,
    sex: "female",
  },
  {
    id: "gentoo-016",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 217,
    mass: 5850,
    bill: 49.3,
    sex: "male",
  },
  {
    id: "gentoo-017",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4150,
    bill: 42,
    sex: "female",
  },
  {
    id: "gentoo-018",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 221,
    mass: 6300,
    bill: 49.2,
    sex: "male",
  },
  {
    id: "gentoo-019",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 209,
    mass: 4800,
    bill: 46.2,
    sex: "female",
  },
  {
    id: "gentoo-020",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 222,
    mass: 5350,
    bill: 48.7,
    sex: "male",
  },
  {
    id: "gentoo-021",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 218,
    mass: 5700,
    bill: 50.2,
    sex: "male",
  },
  {
    id: "gentoo-022",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5000,
    bill: 45.1,
    sex: "female",
  },
  {
    id: "gentoo-023",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 213,
    mass: 4400,
    bill: 46.5,
    sex: "female",
  },
  {
    id: "gentoo-024",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5050,
    bill: 46.3,
    sex: "male",
  },
  {
    id: "gentoo-025",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5000,
    bill: 42.9,
    sex: "female",
  },
  {
    id: "gentoo-026",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5100,
    bill: 46.1,
    sex: "male",
  },
  {
    id: "gentoo-027",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5650,
    bill: 47.8,
    sex: "male",
  },
  {
    id: "gentoo-028",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4600,
    bill: 48.2,
    sex: "female",
  },
  {
    id: "gentoo-029",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 5550,
    bill: 50,
    sex: "male",
  },
  {
    id: "gentoo-030",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 222,
    mass: 5250,
    bill: 47.3,
    sex: "male",
  },
  {
    id: "gentoo-031",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 209,
    mass: 4700,
    bill: 42.8,
    sex: "female",
  },
  {
    id: "gentoo-032",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 207,
    mass: 5050,
    bill: 45.1,
    sex: "female",
  },
  {
    id: "gentoo-033",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 230,
    mass: 6050,
    bill: 59.6,
    sex: "male",
  },
  {
    id: "gentoo-034",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 5150,
    bill: 49.1,
    sex: "female",
  },
  {
    id: "gentoo-035",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 5400,
    bill: 48.4,
    sex: "male",
  },
  {
    id: "gentoo-036",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 213,
    mass: 4950,
    bill: 42.6,
    sex: "female",
  },
  {
    id: "gentoo-037",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 219,
    mass: 5250,
    bill: 44.4,
    sex: "male",
  },
  {
    id: "gentoo-038",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 208,
    mass: 4350,
    bill: 44,
    sex: "female",
  },
  {
    id: "gentoo-039",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 208,
    mass: 5350,
    bill: 48.7,
    sex: "male",
  },
  {
    id: "gentoo-040",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 208,
    mass: 3950,
    bill: 42.7,
    sex: "female",
  },
  {
    id: "gentoo-041",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 225,
    mass: 5700,
    bill: 49.6,
    sex: "male",
  },
  {
    id: "gentoo-042",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4300,
    bill: 45.3,
    sex: "female",
  },
  {
    id: "gentoo-043",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 216,
    mass: 4750,
    bill: 49.6,
    sex: "male",
  },
  {
    id: "gentoo-044",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 222,
    mass: 5550,
    bill: 50.5,
    sex: "male",
  },
  {
    id: "gentoo-045",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 217,
    mass: 4900,
    bill: 43.6,
    sex: "female",
  },
  {
    id: "gentoo-046",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4200,
    bill: 45.5,
    sex: "female",
  },
  {
    id: "gentoo-047",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 225,
    mass: 5400,
    bill: 50.5,
    sex: "male",
  },
  {
    id: "gentoo-048",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 213,
    mass: 5100,
    bill: 44.9,
    sex: "female",
  },
  {
    id: "gentoo-049",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5300,
    bill: 45.2,
    sex: "male",
  },
  {
    id: "gentoo-050",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4850,
    bill: 46.6,
    sex: "female",
  },
  {
    id: "gentoo-051",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 5300,
    bill: 48.5,
    sex: "male",
  },
  {
    id: "gentoo-052",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4400,
    bill: 45.1,
    sex: "female",
  },
  {
    id: "gentoo-053",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 225,
    mass: 5000,
    bill: 50.1,
    sex: "male",
  },
  {
    id: "gentoo-054",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 217,
    mass: 4900,
    bill: 46.5,
    sex: "female",
  },
  {
    id: "gentoo-055",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 5050,
    bill: 45,
    sex: "male",
  },
  {
    id: "gentoo-056",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 208,
    mass: 4300,
    bill: 43.8,
    sex: "female",
  },
  {
    id: "gentoo-057",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 5000,
    bill: 45.5,
    sex: "male",
  },
  {
    id: "gentoo-058",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 208,
    mass: 4450,
    bill: 43.2,
    sex: "female",
  },
  {
    id: "gentoo-059",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 224,
    mass: 5550,
    bill: 50.4,
    sex: "male",
  },
  {
    id: "gentoo-060",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 208,
    mass: 4200,
    bill: 45.3,
    sex: "female",
  },
  {
    id: "gentoo-061",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 221,
    mass: 5300,
    bill: 46.2,
    sex: "male",
  },
  {
    id: "gentoo-062",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 214,
    mass: 4400,
    bill: 45.7,
    sex: "female",
  },
  {
    id: "gentoo-063",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 231,
    mass: 5650,
    bill: 54.3,
    sex: "male",
  },
  {
    id: "gentoo-064",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 219,
    mass: 4700,
    bill: 45.8,
    sex: "female",
  },
  {
    id: "gentoo-065",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 230,
    mass: 5700,
    bill: 49.8,
    sex: "male",
  },
  {
    id: "gentoo-066",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 229,
    mass: 5800,
    bill: 49.5,
    sex: "male",
  },
  {
    id: "gentoo-067",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 4700,
    bill: 43.5,
    sex: "female",
  },
  {
    id: "gentoo-068",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 223,
    mass: 5550,
    bill: 50.7,
    sex: "male",
  },
  {
    id: "gentoo-069",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 216,
    mass: 4750,
    bill: 47.7,
    sex: "female",
  },
  {
    id: "gentoo-070",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 221,
    mass: 5000,
    bill: 46.4,
    sex: "male",
  },
  {
    id: "gentoo-071",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 221,
    mass: 5100,
    bill: 48.2,
    sex: "male",
  },
  {
    id: "gentoo-072",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 217,
    mass: 5200,
    bill: 46.5,
    sex: "female",
  },
  {
    id: "gentoo-073",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 216,
    mass: 4700,
    bill: 46.4,
    sex: "female",
  },
  {
    id: "gentoo-074",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 230,
    mass: 5800,
    bill: 48.6,
    sex: "male",
  },
  {
    id: "gentoo-075",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 209,
    mass: 4600,
    bill: 47.5,
    sex: "female",
  },
  {
    id: "gentoo-076",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 220,
    mass: 6000,
    bill: 51.1,
    sex: "male",
  },
  {
    id: "gentoo-077",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 4750,
    bill: 45.2,
    sex: "female",
  },
  {
    id: "gentoo-078",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 223,
    mass: 5950,
    bill: 45.2,
    sex: "male",
  },
  {
    id: "gentoo-079",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 212,
    mass: 4625,
    bill: 49.1,
    sex: "female",
  },
  {
    id: "gentoo-080",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 221,
    mass: 5450,
    bill: 52.5,
    sex: "male",
  },
  {
    id: "gentoo-081",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 212,
    mass: 4725,
    bill: 47.4,
    sex: "female",
  },
  {
    id: "gentoo-082",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 224,
    mass: 5350,
    bill: 50,
    sex: "male",
  },
  {
    id: "gentoo-083",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 212,
    mass: 4750,
    bill: 44.9,
    sex: "female",
  },
  {
    id: "gentoo-084",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 228,
    mass: 5600,
    bill: 50.8,
    sex: "male",
  },
  {
    id: "gentoo-085",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 218,
    mass: 4600,
    bill: 43.4,
    sex: "female",
  },
  {
    id: "gentoo-086",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 218,
    mass: 5300,
    bill: 51.3,
    sex: "male",
  },
  {
    id: "gentoo-087",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 212,
    mass: 4875,
    bill: 47.5,
    sex: "female",
  },
  {
    id: "gentoo-088",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 230,
    mass: 5550,
    bill: 52.1,
    sex: "male",
  },
  {
    id: "gentoo-089",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 218,
    mass: 4950,
    bill: 47.5,
    sex: "female",
  },
  {
    id: "gentoo-090",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 228,
    mass: 5400,
    bill: 52.2,
    sex: "male",
  },
  {
    id: "gentoo-091",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 212,
    mass: 4750,
    bill: 45.5,
    sex: "female",
  },
  {
    id: "gentoo-092",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 224,
    mass: 5650,
    bill: 49.5,
    sex: "male",
  },
  {
    id: "gentoo-093",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 214,
    mass: 4850,
    bill: 44.5,
    sex: "female",
  },
  {
    id: "gentoo-094",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 226,
    mass: 5200,
    bill: 50.8,
    sex: "male",
  },
  {
    id: "gentoo-095",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 216,
    mass: 4925,
    bill: 49.4,
    sex: "male",
  },
  {
    id: "gentoo-096",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 222,
    mass: 4875,
    bill: 46.9,
    sex: "female",
  },
  {
    id: "gentoo-097",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 203,
    mass: 4625,
    bill: 48.4,
    sex: "female",
  },
  {
    id: "gentoo-098",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 225,
    mass: 5250,
    bill: 51.1,
    sex: "male",
  },
  {
    id: "gentoo-099",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 219,
    mass: 4850,
    bill: 48.5,
    sex: "female",
  },
  {
    id: "gentoo-100",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 228,
    mass: 5600,
    bill: 55.9,
    sex: "male",
  },
  {
    id: "gentoo-101",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 4975,
    bill: 47.2,
    sex: "female",
  },
  {
    id: "gentoo-102",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 228,
    mass: 5500,
    bill: 49.1,
    sex: "male",
  },
  {
    id: "gentoo-103",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 5500,
    bill: 46.8,
    sex: "male",
  },
  {
    id: "gentoo-104",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 210,
    mass: 4700,
    bill: 41.7,
    sex: "female",
  },
  {
    id: "gentoo-105",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 219,
    mass: 5500,
    bill: 53.4,
    sex: "male",
  },
  {
    id: "gentoo-106",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 208,
    mass: 4575,
    bill: 43.3,
    sex: "female",
  },
  {
    id: "gentoo-107",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 209,
    mass: 5500,
    bill: 48.1,
    sex: "male",
  },
  {
    id: "gentoo-108",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 216,
    mass: 5000,
    bill: 50.5,
    sex: "female",
  },
  {
    id: "gentoo-109",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 229,
    mass: 5950,
    bill: 49.8,
    sex: "male",
  },
  {
    id: "gentoo-110",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 213,
    mass: 4650,
    bill: 43.5,
    sex: "female",
  },
  {
    id: "gentoo-111",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 230,
    mass: 5500,
    bill: 51.5,
    sex: "male",
  },
  {
    id: "gentoo-112",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 217,
    mass: 4375,
    bill: 46.2,
    sex: "female",
  },
  {
    id: "gentoo-113",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 230,
    mass: 5850,
    bill: 55.1,
    sex: "male",
  },
  {
    id: "gentoo-114",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 222,
    mass: 6000,
    bill: 48.8,
    sex: "male",
  },
  {
    id: "gentoo-115",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 214,
    mass: 4925,
    bill: 47.2,
    sex: "female",
  },
  {
    id: "gentoo-116",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 215,
    mass: 4850,
    bill: 46.8,
    sex: "female",
  },
  {
    id: "gentoo-117",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 222,
    mass: 5750,
    bill: 50.4,
    sex: "male",
  },
  {
    id: "gentoo-118",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 212,
    mass: 5200,
    bill: 45.2,
    sex: "female",
  },
  {
    id: "gentoo-119",
    species: "Gentoo",
    island: "Biscoe",
    flipper: 213,
    mass: 5400,
    bill: 49.9,
    sex: "male",
  },
  {
    id: "chinstrap-001",
    species: "Chinstrap",
    island: "Dream",
    flipper: 192,
    mass: 3500,
    bill: 46.5,
    sex: "female",
  },
  {
    id: "chinstrap-002",
    species: "Chinstrap",
    island: "Dream",
    flipper: 196,
    mass: 3900,
    bill: 50,
    sex: "male",
  },
  {
    id: "chinstrap-003",
    species: "Chinstrap",
    island: "Dream",
    flipper: 193,
    mass: 3650,
    bill: 51.3,
    sex: "male",
  },
  {
    id: "chinstrap-004",
    species: "Chinstrap",
    island: "Dream",
    flipper: 188,
    mass: 3525,
    bill: 45.4,
    sex: "female",
  },
  {
    id: "chinstrap-005",
    species: "Chinstrap",
    island: "Dream",
    flipper: 197,
    mass: 3725,
    bill: 52.7,
    sex: "male",
  },
  {
    id: "chinstrap-006",
    species: "Chinstrap",
    island: "Dream",
    flipper: 198,
    mass: 3950,
    bill: 45.2,
    sex: "female",
  },
  {
    id: "chinstrap-007",
    species: "Chinstrap",
    island: "Dream",
    flipper: 178,
    mass: 3250,
    bill: 46.1,
    sex: "female",
  },
  {
    id: "chinstrap-008",
    species: "Chinstrap",
    island: "Dream",
    flipper: 197,
    mass: 3750,
    bill: 51.3,
    sex: "male",
  },
  {
    id: "chinstrap-009",
    species: "Chinstrap",
    island: "Dream",
    flipper: 195,
    mass: 4150,
    bill: 46,
    sex: "female",
  },
  {
    id: "chinstrap-010",
    species: "Chinstrap",
    island: "Dream",
    flipper: 198,
    mass: 3700,
    bill: 51.3,
    sex: "male",
  },
  {
    id: "chinstrap-011",
    species: "Chinstrap",
    island: "Dream",
    flipper: 193,
    mass: 3800,
    bill: 46.6,
    sex: "female",
  },
  {
    id: "chinstrap-012",
    species: "Chinstrap",
    island: "Dream",
    flipper: 194,
    mass: 3775,
    bill: 51.7,
    sex: "male",
  },
  {
    id: "chinstrap-013",
    species: "Chinstrap",
    island: "Dream",
    flipper: 185,
    mass: 3700,
    bill: 47,
    sex: "female",
  },
  {
    id: "chinstrap-014",
    species: "Chinstrap",
    island: "Dream",
    flipper: 201,
    mass: 4050,
    bill: 52,
    sex: "male",
  },
  {
    id: "chinstrap-015",
    species: "Chinstrap",
    island: "Dream",
    flipper: 190,
    mass: 3575,
    bill: 45.9,
    sex: "female",
  },
  {
    id: "chinstrap-016",
    species: "Chinstrap",
    island: "Dream",
    flipper: 201,
    mass: 4050,
    bill: 50.5,
    sex: "male",
  },
  {
    id: "chinstrap-017",
    species: "Chinstrap",
    island: "Dream",
    flipper: 197,
    mass: 3300,
    bill: 50.3,
    sex: "male",
  },
  {
    id: "chinstrap-018",
    species: "Chinstrap",
    island: "Dream",
    flipper: 181,
    mass: 3700,
    bill: 58,
    sex: "female",
  },
  {
    id: "chinstrap-019",
    species: "Chinstrap",
    island: "Dream",
    flipper: 190,
    mass: 3450,
    bill: 46.4,
    sex: "female",
  },
  {
    id: "chinstrap-020",
    species: "Chinstrap",
    island: "Dream",
    flipper: 195,
    mass: 4400,
    bill: 49.2,
    sex: "male",
  },
  {
    id: "chinstrap-021",
    species: "Chinstrap",
    island: "Dream",
    flipper: 181,
    mass: 3600,
    bill: 42.4,
    sex: "female",
  },
  {
    id: "chinstrap-022",
    species: "Chinstrap",
    island: "Dream",
    flipper: 191,
    mass: 3400,
    bill: 48.5,
    sex: "male",
  },
  {
    id: "chinstrap-023",
    species: "Chinstrap",
    island: "Dream",
    flipper: 187,
    mass: 2900,
    bill: 43.2,
    sex: "female",
  },
  {
    id: "chinstrap-024",
    species: "Chinstrap",
    island: "Dream",
    flipper: 193,
    mass: 3800,
    bill: 50.6,
    sex: "male",
  },
  {
    id: "chinstrap-025",
    species: "Chinstrap",
    island: "Dream",
    flipper: 195,
    mass: 3300,
    bill: 46.7,
    sex: "female",
  },
  {
    id: "chinstrap-026",
    species: "Chinstrap",
    island: "Dream",
    flipper: 197,
    mass: 4150,
    bill: 52,
    sex: "male",
  },
  {
    id: "chinstrap-027",
    species: "Chinstrap",
    island: "Dream",
    flipper: 200,
    mass: 3400,
    bill: 50.5,
    sex: "female",
  },
  {
    id: "chinstrap-028",
    species: "Chinstrap",
    island: "Dream",
    flipper: 200,
    mass: 3800,
    bill: 49.5,
    sex: "male",
  },
  {
    id: "chinstrap-029",
    species: "Chinstrap",
    island: "Dream",
    flipper: 191,
    mass: 3700,
    bill: 46.4,
    sex: "female",
  },
  {
    id: "chinstrap-030",
    species: "Chinstrap",
    island: "Dream",
    flipper: 205,
    mass: 4550,
    bill: 52.8,
    sex: "male",
  },
  {
    id: "chinstrap-031",
    species: "Chinstrap",
    island: "Dream",
    flipper: 187,
    mass: 3200,
    bill: 40.9,
    sex: "female",
  },
  {
    id: "chinstrap-032",
    species: "Chinstrap",
    island: "Dream",
    flipper: 201,
    mass: 4300,
    bill: 54.2,
    sex: "male",
  },
  {
    id: "chinstrap-033",
    species: "Chinstrap",
    island: "Dream",
    flipper: 187,
    mass: 3350,
    bill: 42.5,
    sex: "female",
  },
  {
    id: "chinstrap-034",
    species: "Chinstrap",
    island: "Dream",
    flipper: 203,
    mass: 4100,
    bill: 51,
    sex: "male",
  },
  {
    id: "chinstrap-035",
    species: "Chinstrap",
    island: "Dream",
    flipper: 195,
    mass: 3600,
    bill: 49.7,
    sex: "male",
  },
  {
    id: "chinstrap-036",
    species: "Chinstrap",
    island: "Dream",
    flipper: 199,
    mass: 3900,
    bill: 47.5,
    sex: "female",
  },
  {
    id: "chinstrap-037",
    species: "Chinstrap",
    island: "Dream",
    flipper: 195,
    mass: 3850,
    bill: 47.6,
    sex: "female",
  },
  {
    id: "chinstrap-038",
    species: "Chinstrap",
    island: "Dream",
    flipper: 210,
    mass: 4800,
    bill: 52,
    sex: "male",
  },
  {
    id: "chinstrap-039",
    species: "Chinstrap",
    island: "Dream",
    flipper: 192,
    mass: 2700,
    bill: 46.9,
    sex: "female",
  },
  {
    id: "chinstrap-040",
    species: "Chinstrap",
    island: "Dream",
    flipper: 205,
    mass: 4500,
    bill: 53.5,
    sex: "male",
  },
  {
    id: "chinstrap-041",
    species: "Chinstrap",
    island: "Dream",
    flipper: 210,
    mass: 3950,
    bill: 49,
    sex: "male",
  },
  {
    id: "chinstrap-042",
    species: "Chinstrap",
    island: "Dream",
    flipper: 187,
    mass: 3650,
    bill: 46.2,
    sex: "female",
  },
  {
    id: "chinstrap-043",
    species: "Chinstrap",
    island: "Dream",
    flipper: 196,
    mass: 3550,
    bill: 50.9,
    sex: "male",
  },
  {
    id: "chinstrap-044",
    species: "Chinstrap",
    island: "Dream",
    flipper: 196,
    mass: 3500,
    bill: 45.5,
    sex: "female",
  },
  {
    id: "chinstrap-045",
    species: "Chinstrap",
    island: "Dream",
    flipper: 196,
    mass: 3675,
    bill: 50.9,
    sex: "female",
  },
  {
    id: "chinstrap-046",
    species: "Chinstrap",
    island: "Dream",
    flipper: 201,
    mass: 4450,
    bill: 50.8,
    sex: "male",
  },
  {
    id: "chinstrap-047",
    species: "Chinstrap",
    island: "Dream",
    flipper: 190,
    mass: 3400,
    bill: 50.1,
    sex: "female",
  },
  {
    id: "chinstrap-048",
    species: "Chinstrap",
    island: "Dream",
    flipper: 212,
    mass: 4300,
    bill: 49,
    sex: "male",
  },
  {
    id: "chinstrap-049",
    species: "Chinstrap",
    island: "Dream",
    flipper: 187,
    mass: 3250,
    bill: 51.5,
    sex: "male",
  },
  {
    id: "chinstrap-050",
    species: "Chinstrap",
    island: "Dream",
    flipper: 198,
    mass: 3675,
    bill: 49.8,
    sex: "female",
  },
  {
    id: "chinstrap-051",
    species: "Chinstrap",
    island: "Dream",
    flipper: 199,
    mass: 3325,
    bill: 48.1,
    sex: "female",
  },
  {
    id: "chinstrap-052",
    species: "Chinstrap",
    island: "Dream",
    flipper: 201,
    mass: 3950,
    bill: 51.4,
    sex: "male",
  },
  {
    id: "chinstrap-053",
    species: "Chinstrap",
    island: "Dream",
    flipper: 193,
    mass: 3600,
    bill: 45.7,
    sex: "female",
  },
  {
    id: "chinstrap-054",
    species: "Chinstrap",
    island: "Dream",
    flipper: 203,
    mass: 4050,
    bill: 50.7,
    sex: "male",
  },
  {
    id: "chinstrap-055",
    species: "Chinstrap",
    island: "Dream",
    flipper: 187,
    mass: 3350,
    bill: 42.5,
    sex: "female",
  },
  {
    id: "chinstrap-056",
    species: "Chinstrap",
    island: "Dream",
    flipper: 197,
    mass: 3450,
    bill: 52.2,
    sex: "male",
  },
  {
    id: "chinstrap-057",
    species: "Chinstrap",
    island: "Dream",
    flipper: 191,
    mass: 3250,
    bill: 45.2,
    sex: "female",
  },
  {
    id: "chinstrap-058",
    species: "Chinstrap",
    island: "Dream",
    flipper: 203,
    mass: 4050,
    bill: 49.3,
    sex: "male",
  },
  {
    id: "chinstrap-059",
    species: "Chinstrap",
    island: "Dream",
    flipper: 202,
    mass: 3800,
    bill: 50.2,
    sex: "male",
  },
  {
    id: "chinstrap-060",
    species: "Chinstrap",
    island: "Dream",
    flipper: 194,
    mass: 3525,
    bill: 45.6,
    sex: "female",
  },
  {
    id: "chinstrap-061",
    species: "Chinstrap",
    island: "Dream",
    flipper: 206,
    mass: 3950,
    bill: 51.9,
    sex: "male",
  },
  {
    id: "chinstrap-062",
    species: "Chinstrap",
    island: "Dream",
    flipper: 189,
    mass: 3650,
    bill: 46.8,
    sex: "female",
  },
  {
    id: "chinstrap-063",
    species: "Chinstrap",
    island: "Dream",
    flipper: 195,
    mass: 3650,
    bill: 45.7,
    sex: "female",
  },
  {
    id: "chinstrap-064",
    species: "Chinstrap",
    island: "Dream",
    flipper: 207,
    mass: 4000,
    bill: 55.8,
    sex: "male",
  },
  {
    id: "chinstrap-065",
    species: "Chinstrap",
    island: "Dream",
    flipper: 202,
    mass: 3400,
    bill: 43.5,
    sex: "female",
  },
  {
    id: "chinstrap-066",
    species: "Chinstrap",
    island: "Dream",
    flipper: 193,
    mass: 3775,
    bill: 49.6,
    sex: "male",
  },
  {
    id: "chinstrap-067",
    species: "Chinstrap",
    island: "Dream",
    flipper: 210,
    mass: 4100,
    bill: 50.8,
    sex: "male",
  },
  {
    id: "chinstrap-068",
    species: "Chinstrap",
    island: "Dream",
    flipper: 198,
    mass: 3775,
    bill: 50.2,
    sex: "female",
  },
];
