#!/usr/bin/env bash
# pre-commit guard: generated visual output must not be newly committed on an
# ordinary branch. `pre-commit run --all-files` also passes clean, tracked
# baselines, so only intersect the hook arguments with the staged diff.
set -euo pipefail

branch="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-}}"
if [[ -z "${branch}" ]]; then
  branch="$(git symbolic-ref --quiet --short HEAD || true)"
fi

staged="$(git diff --cached --name-only --diff-filter=ACMR --)"
blocked=()
for f in "$@"; do
  if printf '%s\n' "${staged}" | grep -Fqx -- "${f}"; then
    # Baseline updates are generated by the pinned-container approval flow.
    # The exemption is path-scoped so other generated output stays blocked.
    if [[ "${branch}" =~ ^vr-update/pr-[0-9]+$ ]] &&
      [[ "${f}" =~ ^tests/visual/__screenshots__/ ]]; then
      continue
    fi
    blocked+=("${f}")
  fi
done

if [[ ${#blocked[@]} -eq 0 ]]; then
  exit 0
fi

# printf (not echo) so paths and ASCII-only messages are portable across
# locales and shells; keep the full blocked list on stderr for tests and
# operators.
printf '%s\n' "BLOCKED: generated output paths must not be committed:" >&2
for f in "${blocked[@]}"; do
  printf '  %s\n' "${f}" >&2
done
printf '%s\n' "Unstage them (git restore --staged <path>) - VR baselines land only via the vr-approve workflow." >&2
exit 1
