#!/usr/bin/env bash
# pre-commit guard: generated visual output must not be newly committed on an
# ordinary branch. `pre-commit run --all-files` also passes clean, tracked
# baselines, so only intersect the hook arguments with the staged diff.
set -euo pipefail

branch="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-}}"
if [[ -z "${branch}" ]]; then
  branch="$(git symbolic-ref --quiet --short HEAD || true)"
fi

# Baseline updates are generated by the pinned-container approval flow. The
# separate vr-baseline-guard CI job validates the exact same-repo branch form.
if [[ "${branch}" =~ ^vr-update/pr-[0-9]+$ ]]; then
  exit 0
fi

staged="$(git diff --cached --name-only --diff-filter=ACMR --)"
blocked=()
for f in "$@"; do
  if printf '%s\n' "${staged}" | grep -Fqx -- "${f}"; then
    blocked+=("${f}")
  fi
done

if [[ ${#blocked[@]} -eq 0 ]]; then
  exit 0
fi

echo "BLOCKED: test/visual output paths are generated artifacts and must not be committed:" >&2
for f in "${blocked[@]}"; do
  echo "  $f" >&2
done
echo "Unstage them (git restore --staged <path>) — VR baselines land only via the vr-approve workflow." >&2
exit 1
