<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleColorViridisD, type ViridisScaleOptions } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ViridisScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorViridisD(definedProps(props)));
</script>
