<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleFillGradient2,
    type Gradient2ScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: Gradient2ScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillGradient2(definedProps(props)));
</script>
