<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleYReverse,
    type ContinuousPositionScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: Omit<ContinuousPositionScaleOptions, "transform" | "reverse"> =
    $props();
  createPlotLayer("scale", () => scaleYReverse(definedProps(props)));
</script>
