<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeDiscrete,
    type DiscreteFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: DiscreteFiniteStyleScaleOptions<PointShapeName> = $props();
  createScaleLayer(() => scaleShapeDiscrete(definedProps(props)));
</script>
