<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorManual,
    type ManualColorScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ManualColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorManual(definedProps(props)));
</script>
