<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleYDiscrete,
    type DiscretePositionScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: DiscretePositionScaleOptions = $props();
  createPlotLayer("scale", () => scaleYDiscrete(definedProps(props)));
</script>
