<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleSizeDiscrete,
    type DiscreteNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: DiscreteNumericStyleScaleOptions = $props();
  createScaleLayer(() => scaleSizeDiscrete(definedProps(props)));
</script>
