<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleFillManual,
    type ManualColorScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: ManualColorScaleOptions = $props();
  createScaleLayer(() => scaleFillManual(definedProps(props)));
</script>
