<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeIdentity,
    type IdentityFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: IdentityFiniteStyleScaleOptions<PointShapeName> = $props();
  createScaleLayer(() => scaleShapeIdentity(definedProps(props)));
</script>
