<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleColorHue, type HueScaleOptions } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: HueScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorHue(definedProps(props)));
</script>
