<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinetypeManual,
    type ManualFiniteStyleScaleOptions,
    type LinetypeName,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: ManualFiniteStyleScaleOptions<LinetypeName> = $props();
  createScaleLayer(() => scaleLinetypeManual(definedProps(props)));
</script>
