<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorContinuous,
    type SequentialColorScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: SequentialColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorContinuous(definedProps(props)));
</script>
