<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorViridisB,
    type ViridisContinuousOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ViridisContinuousOptions = $props();
  createPlotLayer("scale", () => scaleColorViridisB(definedProps(props)));
</script>
