<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinewidthDatetime,
    type TemporalNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: TemporalNumericStyleScaleOptions = $props();
  createPlotLayer("scale", () => scaleLinewidthDatetime(definedProps(props)));
</script>
