<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeBinned,
    type BinnedFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: BinnedFiniteStyleScaleOptions<PointShapeName> = $props();
  createScaleLayer(() => scaleShapeBinned(definedProps(props)));
</script>
