<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleFillSteps, type StepsScaleOptions } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: StepsScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillSteps(definedProps(props)));
</script>
