<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleAlphaBinned,
    type SequentialStyleScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: SequentialStyleScaleOptions = $props();
  createScaleLayer(() => scaleAlphaBinned(definedProps(props)));
</script>
