<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleAlphaManual,
    type ManualNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: ManualNumericStyleScaleOptions = $props();
  createScaleLayer(() => scaleAlphaManual(definedProps(props)));
</script>
