<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeDiscrete,
    type DiscreteFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: DiscreteFiniteStyleScaleOptions<PointShapeName> = $props();
  createPlotLayer("scale", () => scaleShapeDiscrete(definedProps(props)));
</script>
