<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleFillGrey, type GreyScaleOptions } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: GreyScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillGrey(definedProps(props)));
</script>
