<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleFillDatetime,
    type TemporalColorScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: TemporalColorScaleOptions = $props();
  createScaleLayer(() => scaleFillDatetime(definedProps(props)));
</script>
