<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleAlphaIdentity,
    type IdentityNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: IdentityNumericStyleScaleOptions = $props();
  createPlotLayer("scale", () => scaleAlphaIdentity(definedProps(props)));
</script>
