<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleXBinned,
    type ContinuousPositionScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: ContinuousPositionScaleOptions = $props();
  createScaleLayer(() => scaleXBinned(definedProps(props)));
</script>
