<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorSqrt,
    type TransformedColorScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: TransformedColorScaleOptions = $props();
  createScaleLayer(() => scaleColorSqrt(definedProps(props)));
</script>
