<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleYReverse,
    type ContinuousPositionScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: Omit<ContinuousPositionScaleOptions, "transform" | "reverse"> =
    $props();
  createScaleLayer(() => scaleYReverse(definedProps(props)));
</script>
