<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleXSqrt,
    type TransformedPositionScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: TransformedPositionScaleOptions = $props();
  createPlotLayer("scale", () => scaleXSqrt(definedProps(props)));
</script>
