<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleSizeIdentity,
    type IdentityNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: IdentityNumericStyleScaleOptions = $props();
  createScaleLayer(() => scaleSizeIdentity(definedProps(props)));
</script>
