<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleFillSteps2, type Steps2ScaleOptions } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: Steps2ScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillSteps2(definedProps(props)));
</script>
