<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeManual,
    type ManualFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: ManualFiniteStyleScaleOptions<PointShapeName> = $props();
  createScaleLayer(() => scaleShapeManual(definedProps(props)));
</script>
