<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleSizeManual,
    type ManualNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ManualNumericStyleScaleOptions = $props();
  createPlotLayer("scale", () => scaleSizeManual(definedProps(props)));
</script>
