<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleXMonthDay, type TemporalScaleOptions } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: TemporalScaleOptions = $props();
  createPlotLayer("scale", () => scaleXMonthDay(definedProps(props)));
</script>
