<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinetypeIdentity,
    type IdentityFiniteStyleScaleOptions,
    type LinetypeName,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: IdentityFiniteStyleScaleOptions<LinetypeName> = $props();
  createPlotLayer("scale", () => scaleLinetypeIdentity(definedProps(props)));
</script>
