<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinetypeManual,
    type ManualFiniteStyleScaleOptions,
    type LinetypeName,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ManualFiniteStyleScaleOptions<LinetypeName> = $props();
  createPlotLayer("scale", () => scaleLinetypeManual(definedProps(props)));
</script>
