<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeManual,
    type ManualFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ManualFiniteStyleScaleOptions<PointShapeName> = $props();
  createPlotLayer("scale", () => scaleShapeManual(definedProps(props)));
</script>
