<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleFillFermenter,
    type ColorFermenterScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ColorFermenterScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillFermenter(definedProps(props)));
</script>
