<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleFillOrdinal,
    type OrdinalColorScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: OrdinalColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillOrdinal(definedProps(props)));
</script>
