<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleSizeDiscrete,
    type DiscreteNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: DiscreteNumericStyleScaleOptions = $props();
  createPlotLayer("scale", () => scaleSizeDiscrete(definedProps(props)));
</script>
