<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorDiscrete,
    type DiscreteColorScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: DiscreteColorScaleOptions = $props();
  createScaleLayer(() => scaleColorDiscrete(definedProps(props)));
</script>
