<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleXDiscrete,
    type DiscretePositionScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: DiscretePositionScaleOptions = $props();
  createScaleLayer(() => scaleXDiscrete(definedProps(props)));
</script>
