<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleFillDistiller,
    type ColorDistillerScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ColorDistillerScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillDistiller(definedProps(props)));
</script>
