<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorBinned,
    type BinnedColorScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: BinnedColorScaleOptions = $props();
  createScaleLayer(() => scaleColorBinned(definedProps(props)));
</script>
