<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinetypeBinned,
    type BinnedFiniteStyleScaleOptions,
    type LinetypeName,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: BinnedFiniteStyleScaleOptions<LinetypeName> = $props();
  createScaleLayer(() => scaleLinetypeBinned(definedProps(props)));
</script>
