<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorGradient,
    type GradientScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: GradientScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorGradient(definedProps(props)));
</script>
