<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinewidthContinuous,
    type SequentialStyleScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: SequentialStyleScaleOptions = $props();
  createPlotLayer("scale", () => scaleLinewidthContinuous(definedProps(props)));
</script>
