<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorBrewer,
    type ColorBrewerScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ColorBrewerScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorBrewer(definedProps(props)));
</script>
