<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinetypeIdentity,
    type IdentityFiniteStyleScaleOptions,
    type LinetypeName,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: IdentityFiniteStyleScaleOptions<LinetypeName> = $props();
  createScaleLayer(() => scaleLinetypeIdentity(definedProps(props)));
</script>
