<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorLog10,
    type TransformedColorScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: TransformedColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorLog10(definedProps(props)));
</script>
