<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleSizeDate,
    type TemporalNumericStyleScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: TemporalNumericStyleScaleOptions = $props();
  createScaleLayer(() => scaleSizeDate(definedProps(props)));
</script>
