<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorIdentity,
    type IdentityColorScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: IdentityColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorIdentity(definedProps(props)));
</script>
