<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorBinned,
    type BinnedColorScaleOptions,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: BinnedColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorBinned(definedProps(props)));
</script>
