<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleXDatetime, type TemporalScaleOptions } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: TemporalScaleOptions = $props();
  createScaleLayer(() => scaleXDatetime(definedProps(props)));
</script>
