<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorIdentity,
    type IdentityColorScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: IdentityColorScaleOptions = $props();
  createScaleLayer(() => scaleColorIdentity(definedProps(props)));
</script>
