<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeBinned,
    type BinnedFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: BinnedFiniteStyleScaleOptions<PointShapeName> = $props();
  createPlotLayer("scale", () => scaleShapeBinned(definedProps(props)));
</script>
