<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleLinetypeBinned,
    type BinnedFiniteStyleScaleOptions,
    type LinetypeName,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: BinnedFiniteStyleScaleOptions<LinetypeName> = $props();
  createPlotLayer("scale", () => scaleLinetypeBinned(definedProps(props)));
</script>
