<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleFillContinuous,
    type SequentialColorScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: SequentialColorScaleOptions = $props();
  createScaleLayer(() => scaleFillContinuous(definedProps(props)));
</script>
