<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleColorStepsn, type StepsnScaleOptions } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: StepsnScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorStepsn(definedProps(props)));
</script>
