<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleShapeIdentity,
    type IdentityFiniteStyleScaleOptions,
    type PointShapeName,
  } from "@ggsvelte/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: IdentityFiniteStyleScaleOptions<PointShapeName> = $props();
  createPlotLayer("scale", () => scaleShapeIdentity(definedProps(props)));
</script>
