<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleYLog10,
    type TransformedPositionScaleOptions,
  } from "@ggsvelte/spec";
  import { createScaleLayer, definedProps } from "./factory.svelte.js";

  const props: TransformedPositionScaleOptions = $props();
  createScaleLayer(() => scaleYLog10(definedProps(props)));
</script>
