/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import "@ggsvelte/core/temporal";
import type { ReactNode } from "react";
import {
  scaleXContinuous,
  scaleYContinuous,
  scaleXLog10,
  scaleYLog10,
  scaleXSqrt,
  scaleYSqrt,
  scaleXReverse,
  scaleYReverse,
  scaleXBinned,
  scaleYBinned,
  scaleXDate,
  scaleXDatetime,
  scaleXTime,
  scaleYDate,
  scaleYDatetime,
  scaleYTime,
  scaleXMonthDay,
  scaleYMonthDay,
  scaleXDiscrete,
  scaleYDiscrete,
  scaleColorContinuous,
  scaleColorDiscrete,
  scaleColorBinned,
  scaleColorBrewer,
  scaleColorDistiller,
  scaleColorFermenter,
  scaleColorSteps,
  scaleColorSteps2,
  scaleColorStepsn,
  scaleColorGradient,
  scaleColorGradient2,
  scaleColorGradientn,
  scaleColorHue,
  scaleColorGrey,
  scaleColorOrdinal,
  scaleColorLog10,
  scaleColorSqrt,
  scaleColorDate,
  scaleColorDatetime,
  scaleColorManual,
  scaleColorIdentity,
  scaleFillContinuous,
  scaleFillDiscrete,
  scaleFillBinned,
  scaleFillSteps,
  scaleFillSteps2,
  scaleFillStepsn,
  scaleFillGradient,
  scaleFillGradient2,
  scaleFillGradientn,
  scaleFillHue,
  scaleFillGrey,
  scaleFillOrdinal,
  scaleFillLog10,
  scaleFillSqrt,
  scaleFillDate,
  scaleFillDatetime,
  scaleFillManual,
  scaleFillIdentity,
  scaleFillBrewer,
  scaleFillDistiller,
  scaleFillFermenter,
  scaleColorViridisC,
  scaleColorViridisD,
  scaleColorViridisB,
  scaleFillViridisC,
  scaleFillViridisD,
  scaleFillViridisB,
  scaleSizeContinuous,
  scaleSizeDiscrete,
  scaleSizeBinned,
  scaleSizeDate,
  scaleSizeDatetime,
  scaleSizeManual,
  scaleSizeIdentity,
  scaleLinewidthContinuous,
  scaleLinewidthDiscrete,
  scaleLinewidthBinned,
  scaleLinewidthDate,
  scaleLinewidthDatetime,
  scaleLinewidthManual,
  scaleLinewidthIdentity,
  scaleAlphaContinuous,
  scaleAlphaDiscrete,
  scaleAlphaBinned,
  scaleAlphaDate,
  scaleAlphaDatetime,
  scaleAlphaManual,
  scaleAlphaIdentity,
  scaleSizeArea,
  scaleSizeBinnedArea,
  scaleRadius,
  scaleShapeDiscrete,
  scaleShapeBinned,
  scaleShapeManual,
  scaleShapeIdentity,
  scaleLinetypeDiscrete,
  scaleLinetypeBinned,
  scaleLinetypeManual,
  scaleLinetypeIdentity,
} from "@ggsvelte/spec";
import { definedProps } from "./defined-props.js";
import { usePlotLayerValue } from "./geom-factory.js";

export function ScaleXContinuous(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXContinuous(definedProps(props) as never));
  return null;
}

export function ScaleYContinuous(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYContinuous(definedProps(props) as never));
  return null;
}

export function ScaleXLog10(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXLog10(definedProps(props) as never));
  return null;
}

export function ScaleYLog10(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYLog10(definedProps(props) as never));
  return null;
}

export function ScaleXSqrt(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXSqrt(definedProps(props) as never));
  return null;
}

export function ScaleYSqrt(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYSqrt(definedProps(props) as never));
  return null;
}

export function ScaleXReverse(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXReverse(definedProps(props) as never));
  return null;
}

export function ScaleYReverse(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYReverse(definedProps(props) as never));
  return null;
}

export function ScaleXBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXBinned(definedProps(props) as never));
  return null;
}

export function ScaleYBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYBinned(definedProps(props) as never));
  return null;
}

export function ScaleXDate(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXDate(definedProps(props) as never));
  return null;
}

export function ScaleXDatetime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXDatetime(definedProps(props) as never));
  return null;
}

export function ScaleXTime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXTime(definedProps(props) as never));
  return null;
}

export function ScaleYDate(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYDate(definedProps(props) as never));
  return null;
}

export function ScaleYDatetime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYDatetime(definedProps(props) as never));
  return null;
}

export function ScaleYTime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYTime(definedProps(props) as never));
  return null;
}

export function ScaleXMonthDay(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXMonthDay(definedProps(props) as never));
  return null;
}

export function ScaleYMonthDay(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYMonthDay(definedProps(props) as never));
  return null;
}

export function ScaleXDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleXDiscrete(definedProps(props) as never));
  return null;
}

export function ScaleYDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleYDiscrete(definedProps(props) as never));
  return null;
}

export function ScaleColorContinuous(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorContinuous(definedProps(props) as never));
  return null;
}
export { ScaleColorContinuous as ScaleColourContinuous };

export function ScaleColorDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDiscrete(definedProps(props) as never));
  return null;
}
export { ScaleColorDiscrete as ScaleColourDiscrete };

export function ScaleColorBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorBinned(definedProps(props) as never));
  return null;
}
export { ScaleColorBinned as ScaleColourBinned };

export function ScaleColorBrewer(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorBrewer(definedProps(props) as never));
  return null;
}
export { ScaleColorBrewer as ScaleColourBrewer };

export function ScaleColorDistiller(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDistiller(definedProps(props) as never));
  return null;
}
export { ScaleColorDistiller as ScaleColourDistiller };

export function ScaleColorFermenter(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorFermenter(definedProps(props) as never));
  return null;
}
export { ScaleColorFermenter as ScaleColourFermenter };

export function ScaleColorSteps(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorSteps(definedProps(props) as never));
  return null;
}
export { ScaleColorSteps as ScaleColourSteps };

export function ScaleColorSteps2(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorSteps2(definedProps(props) as never));
  return null;
}
export { ScaleColorSteps2 as ScaleColourSteps2 };

export function ScaleColorStepsn(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorStepsn(definedProps(props) as never));
  return null;
}
export { ScaleColorStepsn as ScaleColourStepsn };

export function ScaleColorGradient(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGradient(definedProps(props) as never));
  return null;
}
export { ScaleColorGradient as ScaleColourGradient };

export function ScaleColorGradient2(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGradient2(definedProps(props) as never));
  return null;
}
export { ScaleColorGradient2 as ScaleColourGradient2 };

export function ScaleColorGradientn(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGradientn(definedProps(props) as never));
  return null;
}
export { ScaleColorGradientn as ScaleColourGradientn };

export function ScaleColorHue(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorHue(definedProps(props) as never));
  return null;
}
export { ScaleColorHue as ScaleColourHue };

export function ScaleColorGrey(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGrey(definedProps(props) as never));
  return null;
}
export { ScaleColorGrey as ScaleColourGrey };

export function ScaleColorOrdinal(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorOrdinal(definedProps(props) as never));
  return null;
}
export { ScaleColorOrdinal as ScaleColourOrdinal };

export function ScaleColorLog10(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorLog10(definedProps(props) as never));
  return null;
}
export { ScaleColorLog10 as ScaleColourLog10 };

export function ScaleColorSqrt(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorSqrt(definedProps(props) as never));
  return null;
}
export { ScaleColorSqrt as ScaleColourSqrt };

export function ScaleColorDate(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDate(definedProps(props) as never));
  return null;
}
export { ScaleColorDate as ScaleColourDate };

export function ScaleColorDatetime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDatetime(definedProps(props) as never));
  return null;
}
export { ScaleColorDatetime as ScaleColourDatetime };

export function ScaleColorManual(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorManual(definedProps(props) as never));
  return null;
}
export { ScaleColorManual as ScaleColourManual };

export function ScaleColorIdentity(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorIdentity(definedProps(props) as never));
  return null;
}
export { ScaleColorIdentity as ScaleColourIdentity };

export function ScaleFillContinuous(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillContinuous(definedProps(props) as never));
  return null;
}

export function ScaleFillDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDiscrete(definedProps(props) as never));
  return null;
}

export function ScaleFillBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillBinned(definedProps(props) as never));
  return null;
}

export function ScaleFillSteps(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillSteps(definedProps(props) as never));
  return null;
}

export function ScaleFillSteps2(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillSteps2(definedProps(props) as never));
  return null;
}

export function ScaleFillStepsn(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillStepsn(definedProps(props) as never));
  return null;
}

export function ScaleFillGradient(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGradient(definedProps(props) as never));
  return null;
}

export function ScaleFillGradient2(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGradient2(definedProps(props) as never));
  return null;
}

export function ScaleFillGradientn(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGradientn(definedProps(props) as never));
  return null;
}

export function ScaleFillHue(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillHue(definedProps(props) as never));
  return null;
}

export function ScaleFillGrey(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGrey(definedProps(props) as never));
  return null;
}

export function ScaleFillOrdinal(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillOrdinal(definedProps(props) as never));
  return null;
}

export function ScaleFillLog10(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillLog10(definedProps(props) as never));
  return null;
}

export function ScaleFillSqrt(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillSqrt(definedProps(props) as never));
  return null;
}

export function ScaleFillDate(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDate(definedProps(props) as never));
  return null;
}

export function ScaleFillDatetime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDatetime(definedProps(props) as never));
  return null;
}

export function ScaleFillManual(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillManual(definedProps(props) as never));
  return null;
}

export function ScaleFillIdentity(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillIdentity(definedProps(props) as never));
  return null;
}

export function ScaleFillBrewer(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillBrewer(definedProps(props) as never));
  return null;
}

export function ScaleFillDistiller(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDistiller(definedProps(props) as never));
  return null;
}

export function ScaleFillFermenter(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillFermenter(definedProps(props) as never));
  return null;
}

export function ScaleColorViridisC(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorViridisC(definedProps(props) as never));
  return null;
}
export { ScaleColorViridisC as ScaleColourViridisC };

export function ScaleColorViridisD(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorViridisD(definedProps(props) as never));
  return null;
}
export { ScaleColorViridisD as ScaleColourViridisD };

export function ScaleColorViridisB(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleColorViridisB(definedProps(props) as never));
  return null;
}
export { ScaleColorViridisB as ScaleColourViridisB };

export function ScaleFillViridisC(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillViridisC(definedProps(props) as never));
  return null;
}

export function ScaleFillViridisD(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillViridisD(definedProps(props) as never));
  return null;
}

export function ScaleFillViridisB(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleFillViridisB(definedProps(props) as never));
  return null;
}

export function ScaleSizeContinuous(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeContinuous(definedProps(props) as never));
  return null;
}

export function ScaleSizeDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeDiscrete(definedProps(props) as never));
  return null;
}
export { ScaleSizeDiscrete as ScaleSizeOrdinal };

export function ScaleSizeBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeBinned(definedProps(props) as never));
  return null;
}

export function ScaleSizeDate(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeDate(definedProps(props) as never));
  return null;
}

export function ScaleSizeDatetime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeDatetime(definedProps(props) as never));
  return null;
}

export function ScaleSizeManual(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeManual(definedProps(props) as never));
  return null;
}

export function ScaleSizeIdentity(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeIdentity(definedProps(props) as never));
  return null;
}

export function ScaleLinewidthContinuous(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthContinuous(definedProps(props) as never));
  return null;
}

export function ScaleLinewidthDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthDiscrete(definedProps(props) as never));
  return null;
}
export { ScaleLinewidthDiscrete as ScaleLinewidthOrdinal };

export function ScaleLinewidthBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthBinned(definedProps(props) as never));
  return null;
}

export function ScaleLinewidthDate(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthDate(definedProps(props) as never));
  return null;
}

export function ScaleLinewidthDatetime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthDatetime(definedProps(props) as never));
  return null;
}

export function ScaleLinewidthManual(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthManual(definedProps(props) as never));
  return null;
}

export function ScaleLinewidthIdentity(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthIdentity(definedProps(props) as never));
  return null;
}

export function ScaleAlphaContinuous(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaContinuous(definedProps(props) as never));
  return null;
}

export function ScaleAlphaDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaDiscrete(definedProps(props) as never));
  return null;
}
export { ScaleAlphaDiscrete as ScaleAlphaOrdinal };

export function ScaleAlphaBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaBinned(definedProps(props) as never));
  return null;
}

export function ScaleAlphaDate(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaDate(definedProps(props) as never));
  return null;
}

export function ScaleAlphaDatetime(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaDatetime(definedProps(props) as never));
  return null;
}

export function ScaleAlphaManual(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaManual(definedProps(props) as never));
  return null;
}

export function ScaleAlphaIdentity(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaIdentity(definedProps(props) as never));
  return null;
}

export function ScaleSizeArea(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeArea(definedProps(props) as never));
  return null;
}

export function ScaleSizeBinnedArea(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeBinnedArea(definedProps(props) as never));
  return null;
}

export function ScaleRadius(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleRadius(definedProps(props) as never));
  return null;
}

export function ScaleShapeDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeDiscrete(definedProps(props) as never));
  return null;
}
export { ScaleShapeDiscrete as ScaleShapeOrdinal };

export function ScaleShapeBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeBinned(definedProps(props) as never));
  return null;
}

export function ScaleShapeManual(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeManual(definedProps(props) as never));
  return null;
}

export function ScaleShapeIdentity(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeIdentity(definedProps(props) as never));
  return null;
}

export function ScaleLinetypeDiscrete(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeDiscrete(definedProps(props) as never));
  return null;
}

export function ScaleLinetypeBinned(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeBinned(definedProps(props) as never));
  return null;
}

export function ScaleLinetypeManual(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeManual(definedProps(props) as never));
  return null;
}

export function ScaleLinetypeIdentity(props: Record<string, unknown> = {}): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeIdentity(definedProps(props) as never));
  return null;
}
