/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { ThemeName, ThemeSpec } from "@ggsvelte/spec";
import { definedProps } from "./defined-props.js";
import { usePlotLayerValue } from "./geom-factory.js";

type RoleProps = Partial<ThemeSpec>;

function useNamedTheme(name: ThemeName, props: RoleProps): void {
  usePlotLayerValue("theme", () => {
    const roles = definedProps(props);
    return Object.keys(roles).length === 0 ? name : { name, ...roles };
  });
}

export function ThemeDefault(props: RoleProps = {}): ReactNode {
  useNamedTheme("default", props);
  return null;
}

export function ThemeLight(props: RoleProps = {}): ReactNode {
  useNamedTheme("light", props);
  return null;
}

export function ThemeDark(props: RoleProps = {}): ReactNode {
  useNamedTheme("dark", props);
  return null;
}

export function ThemeMinimal(props: RoleProps = {}): ReactNode {
  useNamedTheme("minimal", props);
  return null;
}

export function ThemeGgplot2(props: RoleProps = {}): ReactNode {
  useNamedTheme("ggplot2", props);
  return null;
}

export function ThemeClassic(props: RoleProps = {}): ReactNode {
  useNamedTheme("classic", props);
  return null;
}

export function ThemeBw(props: RoleProps = {}): ReactNode {
  useNamedTheme("bw", props);
  return null;
}

export function ThemeHrbr(props: RoleProps = {}): ReactNode {
  useNamedTheme("hrbr", props);
  return null;
}

export function ThemeFew(props: RoleProps = {}): ReactNode {
  useNamedTheme("few", props);
  return null;
}

export function ThemeClean(props: RoleProps = {}): ReactNode {
  useNamedTheme("clean", props);
  return null;
}

export function ThemeFivethirtyeight(props: RoleProps = {}): ReactNode {
  useNamedTheme("fivethirtyeight", props);
  return null;
}

export function ThemeEconomist(props: RoleProps = {}): ReactNode {
  useNamedTheme("economist", props);
  return null;
}

export function ThemeTufte(props: RoleProps = {}): ReactNode {
  useNamedTheme("tufte", props);
  return null;
}

export function ThemeLinedraw(props: RoleProps = {}): ReactNode {
  useNamedTheme("linedraw", props);
  return null;
}

export function ThemeVoid(props: RoleProps = {}): ReactNode {
  useNamedTheme("void", props);
  return null;
}

export function ThemeStata(props: RoleProps = {}): ReactNode {
  useNamedTheme("stata", props);
  return null;
}

export function ThemeStatas1color(props: RoleProps = {}): ReactNode {
  useNamedTheme("stata_s1color", props);
  return null;
}

export function ThemeSolarized(props: RoleProps = {}): ReactNode {
  useNamedTheme("solarized", props);
  return null;
}

export function ThemeSolarizeddark(props: RoleProps = {}): ReactNode {
  useNamedTheme("solarizeddark", props);
  return null;
}

export function ThemeEconomistwhite(props: RoleProps = {}): ReactNode {
  useNamedTheme("economist_white", props);
  return null;
}

export function ThemeSolarized2(props: RoleProps = {}): ReactNode {
  useNamedTheme("solarized_2", props);
  return null;
}

export function ThemeSolarized2dark(props: RoleProps = {}): ReactNode {
  useNamedTheme("solarized_2dark", props);
  return null;
}

export function ThemeWsj(props: RoleProps = {}): ReactNode {
  useNamedTheme("wsj", props);
  return null;
}

export function ThemeHc(props: RoleProps = {}): ReactNode {
  useNamedTheme("hc", props);
  return null;
}

export function ThemeHcdark(props: RoleProps = {}): ReactNode {
  useNamedTheme("hcdark", props);
  return null;
}

export function ThemePander(props: RoleProps = {}): ReactNode {
  useNamedTheme("pander", props);
  return null;
}

export function ThemeBase(props: RoleProps = {}): ReactNode {
  useNamedTheme("base", props);
  return null;
}

export function ThemeIgray(props: RoleProps = {}): ReactNode {
  useNamedTheme("igray", props);
  return null;
}

export function ThemeMap(props: RoleProps = {}): ReactNode {
  useNamedTheme("map", props);
  return null;
}

export function ThemeSolid(props: RoleProps = {}): ReactNode {
  useNamedTheme("solid", props);
  return null;
}

export function ThemeGrey(props: RoleProps = {}): ReactNode {
  useNamedTheme("grey", props);
  return null;
}

export function ThemeGray(props: RoleProps = {}): ReactNode {
  useNamedTheme("gray", props);
  return null;
}

export function ThemeTest(props: RoleProps = {}): ReactNode {
  useNamedTheme("test", props);
  return null;
}
