/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput } from "@ggsvelte/spec";
import { useGeomLayer, type GeomProps } from "../geom-factory.js";
type ShellProps = GeomProps &
  Record<string, unknown> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomCol(props: ShellProps): ReactNode {
  useGeomLayer("col", props);
  return null;
}
