/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput } from "@ggsvelte/spec";
import { useGeomLayer, type GeomProps } from "../geom-factory.js";
import { registerDensity2dFilled } from "@ggsvelte/core";
registerDensity2dFilled();

type ShellProps = GeomProps &
  Record<string, unknown> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomDensity2dFilled(props: ShellProps): ReactNode {
  useGeomLayer("density_2d_filled", props);
  return null;
}
