/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput } from "@ggsvelte/spec";
import { useGeomLayer, type GeomProps } from "../geom-factory.js";
type ShellProps = GeomProps &
  Record<string, unknown> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomJitter(props: ShellProps): ReactNode {
  const { width, height, seed, positionParams, ...rest } = props;
  useGeomLayer("jitter", {
    ...rest,
    positionParams: {
      ...positionParams,
      ...(typeof width === "number" ? { width } : {}),
      ...(typeof height === "number" ? { height } : {}),
      ...(typeof seed === "number" ? { seed } : {}),
    },
  });
  return null;
}
