/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput } from "@ggsvelte/spec";
import { useGeomLayer, type GeomProps } from "../geom-factory.js";
import { registerBin2d } from "@ggsvelte/core";
registerBin2d();

type ShellProps = GeomProps &
  Record<string, unknown> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomBin2d(props: ShellProps): ReactNode {
  useGeomLayer("bin_2d", props);
  return null;
}
