/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput } from "@ggsvelte/spec";
import { useGeomLayer, type GeomProps } from "../geom-factory.js";
import { registerQqLine } from "@ggsvelte/core";
registerQqLine();

type ShellProps = GeomProps &
  Record<string, unknown> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomQqLine(props: ShellProps): ReactNode {
  useGeomLayer("qq_line", props);
  return null;
}
