/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput } from "@ggsvelte/spec";
import { useGeomLayer, type GeomProps } from "../geom-factory.js";
import { registerLinerange } from "@ggsvelte/core";
registerLinerange();

type ShellProps = GeomProps &
  Record<string, unknown> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomLinerange(props: ShellProps): ReactNode {
  useGeomLayer("linerange", props);
  return null;
}
