<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type { DataInput, RugParams, RugLayerInput } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: RugParams &
    Omit<RugLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("rug", () => props);
</script>
