<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type {
    DataInput,
    SegmentParams,
    SegmentLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: SegmentParams &
    Omit<SegmentLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("segment", () => props);
</script>
