<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type { DataInput, LineParams, LineLayerInput } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: LineParams &
    Omit<LineLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("line", () => props);
</script>
