<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type {
    DataInput,
    AblineParams,
    AblineLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: AblineParams &
    Omit<AblineLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("abline", () => props);
</script>
