<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type {
    DataInput,
    RasterParams,
    RasterLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: RasterParams &
    Omit<RasterLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("raster", () => props);
</script>
