<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type {
    DataInput,
    BarParams,
    HistogramLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: BarParams &
    Omit<HistogramLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("histogram", () => props);
</script>
