<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script module lang="ts">
  import { registerBin } from "@ggsvelte/core";

  // Self-registration (#1420): this component's geom batch + default stat
  // frame enter the bundle (and the core registries) only when the
  // component itself is imported. Idempotent.
  registerBin();
</script>

<script lang="ts">
  import type {
    DataInput,
    LineParams,
    FreqpolyLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: LineParams &
    Omit<FreqpolyLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("freqpoly", () => props);
</script>
