<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type {
    DataInput,
    PositionParams,
    PointParams,
    JitterLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: PointParams &
    Omit<JitterLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
      /** Maximum horizontal jitter (data units / band-step fraction). */
      width?: number;
      /** Maximum vertical jitter (data units / band-step fraction). */
      height?: number;
      /** Seeded RNG seed (ggsvelte jitter is always seeded; default 42). */
      seed?: number;
    } = $props();
  createGeomLayer("jitter", () => {
    const { width, height, seed, positionParams, ...rest } = props;
    const merged: PositionParams = {
      ...positionParams,
      ...(width !== undefined && { width }),
      ...(height !== undefined && { height }),
      ...(seed !== undefined && { seed }),
    };
    return {
      ...rest,
      ...(Object.keys(merged).length > 0 && { positionParams: merged }),
    };
  });
</script>
