<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script module lang="ts">
  import { registerDensity2d } from "@ggsvelte/core";

  // Self-registration (#1420): this component's geom batch + default stat
  // frame enter the bundle (and the core registries) only when the
  // component itself is imported. Idempotent.
  registerDensity2d();
</script>

<script lang="ts">
  import type {
    DataInput,
    Density2dParams,
    Density2dLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: Density2dParams &
    Omit<Density2dLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("density_2d", () => props);
</script>
