<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type { DataInput, TileParams, TileLayerInput } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: TileParams &
    Omit<TileLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("tile", () => props);
</script>
