<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type {
    DataInput,
    CrossbarParams,
    CrossbarLayerInput,
  } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: CrossbarParams &
    Omit<CrossbarLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("crossbar", () => props);
</script>
