<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type { DataInput, CurveParams, CurveLayerInput } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: CurveParams &
    Omit<CurveLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("curve", () => props);
</script>
