<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script lang="ts">
  import type { DataInput, TextParams, TextLayerInput } from "@ggsvelte/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: TextParams &
    Omit<TextLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("text", () => props);
</script>
