/**
 * AUTO-GENERATED by scripts/gen-builder-geoms.ts — do not edit by hand.
 * Regenerate: bun run builder:geoms:gen
 *
 * Fluent builder geom sugar methods (thin wrappers over layerFrom).
 * Source of truth: KNOWN_GEOMS. Core builder: builder-core.ts.
 * Public GGBuilder: builder.ts (WithBuilderScales(WithBuilderGeoms(Core))).
 */
import type { GGBuilder } from "./builder.js";
import type {
  GeomAblineOptions,
  GeomAreaOptions,
  GeomBarOptions,
  GeomBin2dOptions,
  GeomBlankOptions,
  GeomBoxplotOptions,
  GeomColOptions,
  GeomContourOptions,
  GeomCountOptions,
  GeomCrossbarOptions,
  GeomCurveOptions,
  GeomDensity2dFilledOptions,
  GeomDensity2dOptions,
  GeomDensityOptions,
  GeomDotplotOptions,
  GeomErrorbarOptions,
  GeomFreqpolyOptions,
  GeomFunctionOptions,
  GeomHexOptions,
  GeomHistogramOptions,
  GeomHlineOptions,
  GeomJitterOptions,
  GeomLabelOptions,
  GeomLineOptions,
  GeomLinerangeOptions,
  GeomMapOptions,
  GeomPathOptions,
  GeomPointOptions,
  GeomPointrangeOptions,
  GeomPolygonOptions,
  GeomQqLineOptions,
  GeomQqOptions,
  GeomQuantileOptions,
  GeomRasterOptions,
  GeomRectOptions,
  GeomRibbonOptions,
  GeomRugOptions,
  GeomRuleOptions,
  GeomSegmentOptions,
  GeomSfLabelOptions,
  GeomSfOptions,
  GeomSfTextOptions,
  GeomSmoothOptions,
  GeomSpokeOptions,
  GeomStepOptions,
  GeomTextOptions,
  GeomTileOptions,
  GeomViolinOptions,
  GeomVlineOptions,
} from "./builder-options.js";
import { layerFrom } from "./builder-core.js";
import type { LayerInput } from "./normalize.js";

/** Host must expose layer() returning the public fluent builder type. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- mixin host constructor
type GeomHostConstructor = new (...args: any[]) => {
  layer(layer: LayerInput): GGBuilder;
};

/**
 * Mixin that adds geom* sugar methods for every KNOWN_GEOMS entry.
 * Every method is annotated to return GGBuilder so fluent chains keep full typing.
 */
export function WithBuilderGeoms<TBase extends GeomHostConstructor>(Base: TBase) {
  return class extends Base {
    /** Sugar for .layer({ geom: 'point', ... }). */
    geomPoint(options: GeomPointOptions = {}): GGBuilder {
      return this.layer(layerFrom("point", options));
    }
    /** Sugar for .layer({ geom: 'line', ... }). */
    geomLine(options: GeomLineOptions = {}): GGBuilder {
      return this.layer(layerFrom("line", options));
    }
    /** Sugar for .layer({ geom: 'path', ... }). */
    geomPath(options: GeomPathOptions = {}): GGBuilder {
      return this.layer(layerFrom("path", options));
    }
    /** Sugar for .layer({ geom: 'col', ... }). */
    geomCol(options: GeomColOptions = {}): GGBuilder {
      return this.layer(layerFrom("col", options));
    }
    /** Sugar for .layer({ geom: 'bar', ... }). */
    geomBar(options: GeomBarOptions = {}): GGBuilder {
      return this.layer(layerFrom("bar", options));
    }
    /** Sugar for .layer({ geom: 'histogram', ... }). */
    geomHistogram(options: GeomHistogramOptions = {}): GGBuilder {
      return this.layer(layerFrom("histogram", options));
    }
    /** Sugar for .layer({ geom: 'freqpoly', ... }). */
    geomFreqpoly(options: GeomFreqpolyOptions = {}): GGBuilder {
      return this.layer(layerFrom("freqpoly", options));
    }
    /** Sugar for .layer({ geom: 'area', ... }). */
    geomArea(options: GeomAreaOptions = {}): GGBuilder {
      return this.layer(layerFrom("area", options));
    }
    /** Sugar for .layer({ geom: 'rule', ... }). */
    geomRule(options: GeomRuleOptions = {}): GGBuilder {
      return this.layer(layerFrom("rule", options));
    }
    /** Sugar for .layer({ geom: 'hline', ... }). */
    geomHline(options: GeomHlineOptions = {}): GGBuilder {
      return this.layer(layerFrom("hline", options));
    }
    /** Sugar for .layer({ geom: 'vline', ... }). */
    geomVline(options: GeomVlineOptions = {}): GGBuilder {
      return this.layer(layerFrom("vline", options));
    }
    /** Sugar for .layer({ geom: 'text', ... }). */
    geomText(options: GeomTextOptions = {}): GGBuilder {
      return this.layer(layerFrom("text", options));
    }
    /** Sugar for .layer({ geom: 'label', ... }). */
    geomLabel(options: GeomLabelOptions = {}): GGBuilder {
      return this.layer(layerFrom("label", options));
    }
    /** Sugar for .layer({ geom: 'smooth', ... }). */
    geomSmooth(options: GeomSmoothOptions = {}): GGBuilder {
      return this.layer(layerFrom("smooth", options));
    }
    /** Sugar for .layer({ geom: 'quantile', ... }). */
    geomQuantile(options: GeomQuantileOptions = {}): GGBuilder {
      return this.layer(layerFrom("quantile", options));
    }
    /** Sugar for .layer({ geom: 'boxplot', ... }). */
    geomBoxplot(options: GeomBoxplotOptions = {}): GGBuilder {
      return this.layer(layerFrom("boxplot", options));
    }
    /** Sugar for .layer({ geom: 'density', ... }). */
    geomDensity(options: GeomDensityOptions = {}): GGBuilder {
      return this.layer(layerFrom("density", options));
    }
    /** Sugar for .layer({ geom: 'errorbar', ... }). */
    geomErrorbar(options: GeomErrorbarOptions = {}): GGBuilder {
      return this.layer(layerFrom("errorbar", options));
    }
    /** Sugar for .layer({ geom: 'linerange', ... }). */
    geomLinerange(options: GeomLinerangeOptions = {}): GGBuilder {
      return this.layer(layerFrom("linerange", options));
    }
    /** Sugar for .layer({ geom: 'pointrange', ... }). */
    geomPointrange(options: GeomPointrangeOptions = {}): GGBuilder {
      return this.layer(layerFrom("pointrange", options));
    }
    /** Sugar for .layer({ geom: 'crossbar', ... }). */
    geomCrossbar(options: GeomCrossbarOptions = {}): GGBuilder {
      return this.layer(layerFrom("crossbar", options));
    }
    /** Sugar for .layer({ geom: 'rect', ... }). */
    geomRect(options: GeomRectOptions = {}): GGBuilder {
      return this.layer(layerFrom("rect", options));
    }
    /** Sugar for .layer({ geom: 'tile', ... }). */
    geomTile(options: GeomTileOptions = {}): GGBuilder {
      return this.layer(layerFrom("tile", options));
    }
    /** Sugar for .layer({ geom: 'raster', ... }). */
    geomRaster(options: GeomRasterOptions = {}): GGBuilder {
      return this.layer(layerFrom("raster", options));
    }
    /** Sugar for .layer({ geom: 'ribbon', ... }). */
    geomRibbon(options: GeomRibbonOptions = {}): GGBuilder {
      return this.layer(layerFrom("ribbon", options));
    }
    /** Sugar for .layer({ geom: 'segment', ... }). */
    geomSegment(options: GeomSegmentOptions = {}): GGBuilder {
      return this.layer(layerFrom("segment", options));
    }
    /** Sugar for .layer({ geom: 'count', ... }). */
    geomCount(options: GeomCountOptions = {}): GGBuilder {
      return this.layer(layerFrom("count", options));
    }
    /** Sugar for .layer({ geom: 'violin', ... }). */
    geomViolin(options: GeomViolinOptions = {}): GGBuilder {
      return this.layer(layerFrom("violin", options));
    }
    /** Sugar for .layer({ geom: 'function', ... }). */
    geomFunction(options: GeomFunctionOptions): GGBuilder {
      return this.layer(layerFrom("function", options));
    }
    /** Sugar for .layer({ geom: 'polygon', ... }). */
    geomPolygon(options: GeomPolygonOptions = {}): GGBuilder {
      return this.layer(layerFrom("polygon", options));
    }
    /** Sugar for .layer({ geom: 'hex', ... }). */
    geomHex(options: GeomHexOptions = {}): GGBuilder {
      return this.layer(layerFrom("hex", options));
    }
    /** Sugar for .layer({ geom: 'bin_2d', ... }). */
    geomBin2d(options: GeomBin2dOptions = {}): GGBuilder {
      return this.layer(layerFrom("bin_2d", options));
    }
    /** Sugar for .layer({ geom: 'abline', ... }). */
    geomAbline(options: GeomAblineOptions = {}): GGBuilder {
      return this.layer(layerFrom("abline", options));
    }
    /** Sugar for .layer({ geom: 'curve', ... }). */
    geomCurve(options: GeomCurveOptions = {}): GGBuilder {
      return this.layer(layerFrom("curve", options));
    }
    /** Sugar for .layer({ geom: 'contour', ... }). */
    geomContour(options: GeomContourOptions = {}): GGBuilder {
      return this.layer(layerFrom("contour", options));
    }
    /** Sugar for .layer({ geom: 'density_2d', ... }). */
    geomDensity2d(options: GeomDensity2dOptions = {}): GGBuilder {
      return this.layer(layerFrom("density_2d", options));
    }
    /** Sugar for .layer({ geom: 'density_2d_filled', ... }). */
    geomDensity2dFilled(options: GeomDensity2dFilledOptions = {}): GGBuilder {
      return this.layer(layerFrom("density_2d_filled", options));
    }
    /** Sugar for .layer({ geom: 'dotplot', ... }). */
    geomDotplot(options: GeomDotplotOptions = {}): GGBuilder {
      return this.layer(layerFrom("dotplot", options));
    }
    /** Sugar for .layer({ geom: 'map', ... }). */
    geomMap(options: GeomMapOptions): GGBuilder {
      return this.layer(layerFrom("map", options));
    }
    /** Sugar for .layer({ geom: 'sf', ... }). */
    geomSf(options: GeomSfOptions = {}): GGBuilder {
      return this.layer(layerFrom("sf", options));
    }
    /** Sugar for .layer({ geom: 'sf_text', ... }). */
    geomSfText(options: GeomSfTextOptions = {}): GGBuilder {
      return this.layer(layerFrom("sf_text", options));
    }
    /** Sugar for .layer({ geom: 'sf_label', ... }). */
    geomSfLabel(options: GeomSfLabelOptions = {}): GGBuilder {
      return this.layer(layerFrom("sf_label", options));
    }
    /** Sugar for .layer({ geom: 'blank', ... }). */
    geomBlank(options: GeomBlankOptions = {}): GGBuilder {
      return this.layer(layerFrom("blank", options));
    }
    /**
     * Sugar for .layer({ geom: 'jitter', ... }) — points with position jitter
     * (ggplot2 geom_jitter; normalize() → point + position jitter). Flat
     * width/height/seed are assembled into positionParams here (not by normalize).
     */
    geomJitter(options: GeomJitterOptions = {}): GGBuilder {
      const { width, height, seed, positionParams, ...rest } = options;
      const mergedPositionParams = {
        ...positionParams,
        ...(width !== undefined && { width }),
        ...(height !== undefined && { height }),
        ...(seed !== undefined && { seed }),
      };
      const hasPositionParams = Object.keys(mergedPositionParams).length > 0;
      return this.layer(
        layerFrom("jitter", {
          ...rest,
          ...(hasPositionParams && { positionParams: mergedPositionParams }),
        }),
      );
    }
    /** Sugar for .layer({ geom: 'spoke', ... }). */
    geomSpoke(options: GeomSpokeOptions = {}): GGBuilder {
      return this.layer(layerFrom("spoke", options));
    }
    /** Sugar for .layer({ geom: 'rug', ... }). */
    geomRug(options: GeomRugOptions = {}): GGBuilder {
      return this.layer(layerFrom("rug", options));
    }
    /** Sugar for .layer({ geom: 'step', ... }). */
    geomStep(options: GeomStepOptions = {}): GGBuilder {
      return this.layer(layerFrom("step", options));
    }
    /** Sugar for .layer({ geom: 'qq', ... }). */
    geomQq(options: GeomQqOptions = {}): GGBuilder {
      return this.layer(layerFrom("qq", options));
    }
    /** Sugar for .layer({ geom: 'qq_line', ... }). */
    geomQqLine(options: GeomQqLineOptions = {}): GGBuilder {
      return this.layer(layerFrom("qq_line", options));
    }
  };
}
