/**
 * Checked geom-consumption facade + re-export surface for the capability
 * ledger.
 *
 * `SCALE_CAPABILITIES` (raw ledger data) lives in `capabilities-data.ts`;
 * the derived helper views live in `capabilities-helpers.ts`. This module
 * owns the `STYLE_AESTHETIC_GEOMS` table and re-exports every previously
 * exported symbol so existing `'./capabilities.js'` import sites are
 * unchanged.
 */
export { SCALE_CAPABILITIES } from "./capabilities-data.js";
export {
  builderScaleHelperNames,
  scaleCapabilityCamelHelpers,
  STYLE_ORDINAL_SCALE_HELPERS,
} from "./capabilities-helpers.js";
export type { ScaleCapability, StyleAesthetic } from "./capabilities-helpers.js";

/** One checked geom-consumption table for mapped style channels. */
export const STYLE_AESTHETIC_GEOMS = {
  // blank trains style scales without marks; jitter is sugar for point.
  size: [
    "point",
    "jitter",
    "count",
    "text",
    "dotplot",
    "pointrange",
    "sf",
    "sf_text",
    "sf_label",
    "label",
    "blank",
    "qq",
  ],
  linewidth: [
    "line",
    "function",
    "qq_line",
    "path",
    "step",
    "freqpoly",
    "rule",
    "hline",
    "vline",
    "abline",
    "smooth",
    "quantile",
    "contour",
    "boxplot",
    "violin",
    "errorbar",
    "linerange",
    "pointrange",
    "crossbar",
    "rect",
    "tile",
    "hex",
    "bin_2d",
    "ribbon",
    "polygon",
    "segment",
    "spoke",
    "curve",
    "density_2d",
    "density_2d_filled",
    "map",
    "sf",
    "blank",
    "rug",
    "label",
  ],
  alpha: [
    "point",
    "jitter",
    "count",
    "line",
    "function",
    "qq",
    "qq_line",
    "path",
    "step",
    "freqpoly",
    "col",
    "bar",
    "histogram",
    "area",
    "rule",
    "hline",
    "vline",
    "abline",
    "text",
    "sf_text",
    "sf_label",
    "label",
    "smooth",
    "quantile",
    "contour",
    "boxplot",
    "violin",
    "density",
    "density_2d",
    "density_2d_filled",
    "dotplot",
    "errorbar",
    "linerange",
    "pointrange",
    "crossbar",
    "rect",
    "tile",
    "hex",
    "bin_2d",
    "raster",
    "ribbon",
    "polygon",
    "segment",
    "spoke",
    "curve",
    "map",
    "sf",
    "blank",
    "rug",
  ],
  shape: ["point", "jitter", "count", "dotplot", "pointrange", "sf", "blank", "qq"],
  linetype: [
    "line",
    "function",
    "qq_line",
    "path",
    "step",
    "freqpoly",
    "rule",
    "hline",
    "vline",
    "abline",
    "smooth",
    "quantile",
    "contour",
    "boxplot",
    "violin",
    "errorbar",
    "linerange",
    "pointrange",
    "crossbar",
    "rect",
    "tile",
    "ribbon",
    "polygon",
    "segment",
    "spoke",
    "curve",
    "density_2d",
    "density_2d_filled",
    "map",
    "sf",
    "blank",
    "rug",
  ],
} as const;
