// @ggsvelte/spec — spec types, schemas, normalize(), validate(), portability,
// fluent builder. Zero d3, zero DOM. TypeBox is the schema source of truth
// (decision 0004): the same definitions provide the TS types (Static<>), the
// runtime validator, and the published JSON Schema artifact (schema/v0.json).
//
// Lifecycle (Hadley lesson 13; meanings in CONTRIBUTING.md): every export
// carries a lifecycle tag, collected into the generated lifecycle.json by
// scripts/gen-lifecycle.ts. Untagged exports inherit the file default below;
// statements tag themselves with a one-line "@lifecycle <tag>" JSDoc marker;
// individual names use a trailing "@lifecycle <tag>" line comment.
// @lifecycle-default experimental

// Schemas + Static types
export {
  AesSchema,
  AreaLayerSchema,
  BarLayerSchema,
  BoxplotLayerSchema,
  CATEGORICAL_SCHEME_NAMES,
  CHANNELS,
  COLOR_SCHEME_NAMES,
  ChannelValueSchema,
  ColLayerSchema,
  CoordSpecSchema,
  CoordFixedSpecSchema,
  CoordSfSpecSchema,
  CoordTransformAxisSpecSchema,
  CoordTransformSpecSchema,
  CURRENT_EDITION,
  DataRefSchema,
  DensityLayerSchema,
  DotplotLayerSchema,
  ErrorbarLayerSchema,
  LinerangeLayerSchema,
  PointrangeLayerSchema,
  CrossbarLayerSchema,
  RectLayerSchema,
  TileLayerSchema,
  Bin2dLayerSchema,
  RasterLayerSchema,
  HexLayerSchema,
  RibbonLayerSchema,
  SegmentLayerSchema,
  CountLayerSchema,
  ViolinLayerSchema,
  FunctionLayerSchema,
  PolygonLayerSchema,
  AblineLayerSchema,
  CurveLayerSchema,
  RugLayerSchema,
  StepLayerSchema,
  QqLayerSchema,
  QqLineLayerSchema,
  FacetFieldRefSchema,
  FacetStripSpecSchema,
  FacetSpecSchema,
  GEOM_DEFAULTS,
  HistogramLayerSchema,
  FreqpolyLayerSchema,
  HlineLayerSchema,
  JitterLayerSchema,
  KNOWN_GEOMS,
  KNOWN_POSITIONS,
  KNOWN_STATS,
  LayerSpecSchema,
  LineLayerSchema,
  PathLayerSchema,
  LINETYPE_NAMES,
  MAX_BINNED_BREAKS,
  MAX_GLOW_RADIUS,
  MAX_PAINT_STOPS,
  POINT_SHAPE_NAMES,
  PlotSpecSchema,
  PointLayerSchema,
  RuleLayerSchema,
  VlineLayerSchema,
  ScalesSchema,
  SEQUENTIAL_SCHEME_NAMES,
  TemporalParserSpecSchemaRef,
  SmoothLayerSchema,
  SpecModule,
  TextLayerSchema,
  LabelLayerSchema,
  THEME_NAMES,
  THEME_NAME_ALIASES,
} from "./schema.js";
export type {
  A11yMode,
  Aes,
  AreaLayer,
  AreaParams,
  BarLayer,
  BarParams,
  BoxplotLayer,
  BoxplotParams,
  CellValue,
  ChannelName,
  ChannelValue,
  ColorStop,
  ColLayer,
  ColorScaleSpec,
  GradientPaint,
  GlowSpec,
  LinearGradientPaint,
  PaintSpace,
  RadialGradientPaint,
  AlphaScaleSpec,
  ColParams,
  CoordSpec,
  CoordFixedSpec,
  CoordSfSpec,
  CoordTransformAxisSpec,
  CoordTransformSpec,
  DataColumns,
  DataName,
  DataRef,
  DataValues,
  DensityLayer,
  DensityParams,
  Density2dParams,
  Density2dLayer,
  Density2dFilledLayer,
  DotplotLayer,
  DotplotParams,
  ErrorbarLayer,
  ErrorbarParams,
  LinerangeLayer,
  LinerangeParams,
  PointrangeLayer,
  PointrangeParams,
  CrossbarLayer,
  CrossbarParams,
  RectLayer,
  RectParams,
  TileLayer,
  TileParams,
  Bin2dLayer,
  Bin2dParams,
  RasterLayer,
  RasterParams,
  HexLayer,
  HexParams,
  RibbonLayer,
  RibbonParams,
  FacetFieldRef,
  FacetScales,
  FacetSpec,
  FacetStripSpec,
  GeomName,
  GuideSpec,
  GuidesSpec,
  GuideThemeSpec,
  AxisGuideSpec,
  LegendGuideSpec,
  ColorbarGuideSpec,
  ColorstepsGuideSpec,
  NoneGuideSpec,
  HistogramLayer,
  FreqpolyLayer,
  HlineLayer,
  HlineParams,
  InlineData,
  JitterLayer,
  Labs,
  LayerSpec,
  LegendSpec,
  LineLayer,
  LineParams,
  PathParams,
  PathLayer,
  StepLayer,
  StepParams,
  PointLayer,
  PointParams,
  PointPosition,
  PortableSpec, // @lifecycle stable-intent
  PositionName,
  PositionParams,
  PositionScaleSpec,
  PositiveStyleScaleSpec,
  ShapeScaleSpec,
  LinetypeScaleSpec,
  LinetypeName,
  PointShapeName,
  RenderBackend,
  RuleLayer,
  RuleParams,
  VlineLayer,
  VlineParams,
  SegmentLayer,
  CurveLayer,
  SfLayer,
  SfTextLayer,
  SfLabelLayer,
  SpokeLayer,
  SpokeParams,
  SegmentParams,
  CountLayer,
  ViolinLayer,
  ViolinParams,
  FunctionLayer,
  FunctionParams,
  FunctionRegistryName,
  FunctionArgs,
  PolygonLayer,
  PolygonParams,
  AblineLayer,
  AblineParams,
  CurveParams,
  MapParams,
  SfParams,
  MapLayer,
  SfTextParams,
  SfLabelParams,
  BlankLayer,
  BlankParams,
  RugLayer,
  RugParams,
  QqLayer,
  QqParams,
  QqLineLayer,
  QqLineParams,
  ScaleExpansion,
  Scales,
  QuantileLayer,
  QuantileParams,
  ContourParams,
  ContourLayer,
  SmoothLayer,
  SmoothParams,
  StackablePosition,
  StatName,
  SummaryFun,
  TextLayer,
  LabelLayer,
  TemporalParserSpec,
  TextParams,
  LabelParams,
  ThemeName,
  ThemeSpec,
} from "./schema.js";

export {
  guideAxis,
  guideColorbar,
  guideColorsteps,
  guideLegend,
  guideNone,
  guides,
  guide_axis,
  guide_colorbar,
  guide_colorsteps,
  guide_legend,
  guide_none,
} from "./guide-helpers.js";
export type {
  AxisGuideOptions,
  ColorbarGuideOptions,
  ColorstepsGuideOptions,
  LegendGuideOptions,
} from "./guide-helpers.js";

// Checked public capability ledger
export {
  buildGreyPalette,
  buildHuePalette,
  GREY_PALETTE_10,
  HUE_PALETTE_10,
  hslToHex,
} from "./hue-grey-palettes.js";
export { SCALE_CAPABILITIES, STYLE_AESTHETIC_GEOMS } from "./capabilities.js";
export type { ScaleCapability, StyleAesthetic } from "./capabilities.js";
/** @lifecycle experimental */
export { GEOM_PARAM_KEYS } from "./geom-params.js";

// Temporal parsing, inference, and authoring conversions
export {
  canonicalTemporalParserKey,
  dmy,
  dmy_hm,
  dmy_hms,
  dym,
  dym_hm,
  dym_hms,
  fromEpochMilliseconds,
  fromEpochSeconds,
  inferTemporalColumn,
  mdy,
  mdy_hm,
  mdy_hms,
  my,
  myd,
  myd_hm,
  myd_hms,
  parseTemporal,
  parseTemporalColumn,
  parseTemporalFormat,
  TEMPORAL_PARSER_NAMES,
  temporalParserConfigurationError,
  TemporalParseError,
  TemporalParserSpecSchema,
  ydm,
  ydm_hm,
  ydm_hms,
  ym,
  ymd,
  ymd_hm,
  ymd_hms,
  yq,
} from "./temporal.js";
export type {
  TemporalDecision,
  TemporalDisambiguation,
  TemporalFailure,
  TemporalKind,
  ParsedTemporalColumn,
  TemporalParseOptions,
  TemporalParseResult,
  TemporalParserName,
  TemporalPrecision,
} from "./temporal.js";
export {
  MAX_TEMPORAL_CANDIDATES,
  MAX_TEMPORAL_MAJOR_TICKS,
  MAX_TEMPORAL_MINOR_TICKS,
  MIN_TEMPORAL_LABEL_GAP_PX,
  parseTemporalInterval,
  TEMPORAL_INTERVAL_UNITS,
  TEMPORAL_LABEL_TOKENS,
  TEMPORAL_WEEKDAYS,
  TemporalIntervalError,
  TemporalIntervalSpecSchema,
  TemporalLabelSpecSchema,
  temporalIntervalTicks,
  temporalLabelConfigurationError,
  temporalLocaleConfigurationError,
  TemporalWeekStartSchema,
} from "./temporal-guides.js";
export type {
  TemporalInterval,
  TemporalIntervalSpec,
  TemporalIntervalUnit,
  TemporalWeekStart,
} from "./temporal-guides.js";

// Coordinate helpers
export {
  coord_equal,
  coord_fixed,
  coord_sf,
  coord_transform,
  coordEqual,
  coordFixed,
  coordSf,
  coordTransform,
} from "./coord-helpers.js";
export type {
  CoordFixedOptions,
  CoordSfOptions,
  CoordTransformAxisOptions,
  CoordTransformName,
  CoordTransformOptions,
} from "./coord-helpers.js";

// Scale helpers
export {
  configuredColorScaleType,
  canonicalMultiScaleChannel,
  scaleContinuousIdentity,
  scaleDiscreteIdentity,
  scaleDiscreteManual,
  scaleType,
  scale_continuous_identity,
  scale_discrete_identity,
  scale_discrete_manual,
  scale_type,
  scaleColorBinned,
  scaleColorBrewer,
  scaleColorContinuous,
  scaleColorDate,
  scaleColorDatetime,
  scaleColorDiscrete,
  scaleColorDistiller,
  scaleColorFermenter,
  scaleColorGradient,
  scaleColorGradient2,
  scaleColorGradientn,
  scaleColorIdentity,
  scaleColorLog10,
  scaleColorManual,
  scaleColorSqrt,
  scaleColorSteps,
  scaleColorSteps2,
  scaleColorStepsn,
  scaleColorHue,
  scaleColorGrey,
  scaleColorGray,
  scaleColorOrdinal,
  scaleColourBinned,
  scaleColourBrewer,
  scaleColourContinuous,
  scaleColourDate,
  scaleColourDatetime,
  scaleColourDiscrete,
  scaleColourDistiller,
  scaleColourFermenter,
  scaleColourGradient,
  scaleColourGradient2,
  scaleColourGradientn,
  scaleColourIdentity,
  scaleColourLog10,
  scaleColourManual,
  scaleColourSqrt,
  scaleColourSteps,
  scaleColourSteps2,
  scaleColourStepsn,
  scaleColourHue,
  scaleColourGrey,
  scaleColourGray,
  scaleColourOrdinal,
  scaleFillBinned,
  scaleFillBrewer,
  scaleFillContinuous,
  scaleFillDate,
  scaleFillDatetime,
  scaleFillDiscrete,
  scaleFillDistiller,
  scaleFillFermenter,
  scaleFillGradient,
  scaleFillGradient2,
  scaleFillGradientn,
  scaleFillIdentity,
  scaleFillLog10,
  scaleFillManual,
  scaleFillSqrt,
  scaleFillSteps,
  scaleFillSteps2,
  scaleFillStepsn,
  scaleColorViridisB,
  scaleColorViridisC,
  scaleColorViridisD,
  scaleColourViridisB,
  scaleColourViridisC,
  scaleColourViridisD,
  scaleFillViridisB,
  scaleFillViridisC,
  scaleFillViridisD,
  scaleFillHue,
  scaleFillGrey,
  scaleFillGray,
  scaleFillOrdinal,
  scale_color_binned,
  scale_color_brewer,
  scale_color_continuous,
  scale_color_date,
  scale_color_datetime,
  scale_color_discrete,
  scale_color_distiller,
  scale_color_fermenter,
  scale_color_gradient,
  scale_color_gradient2,
  scale_color_gradientn,
  scale_color_identity,
  scale_color_log10,
  scale_color_manual,
  scale_color_sqrt,
  scale_color_steps,
  scale_color_steps2,
  scale_color_stepsn,
  scale_color_viridis_b,
  scale_color_viridis_c,
  scale_color_viridis_d,
  scale_color_hue,
  scale_color_grey,
  scale_color_gray,
  scale_color_ordinal,
  scale_colour_binned,
  scale_colour_brewer,
  scale_colour_continuous,
  scale_colour_date,
  scale_colour_datetime,
  scale_colour_discrete,
  scale_colour_distiller,
  scale_colour_fermenter,
  scale_colour_gradient,
  scale_colour_gradient2,
  scale_colour_gradientn,
  scale_colour_identity,
  scale_colour_log10,
  scale_colour_manual,
  scale_colour_sqrt,
  scale_colour_steps,
  scale_colour_steps2,
  scale_colour_stepsn,
  scale_colour_viridis_b,
  scale_colour_viridis_c,
  scale_colour_viridis_d,
  scale_colour_hue,
  scale_colour_grey,
  scale_colour_gray,
  scale_colour_ordinal,
  scale_fill_binned,
  scale_fill_brewer,
  scale_fill_continuous,
  scale_fill_date,
  scale_fill_datetime,
  scale_fill_discrete,
  scale_fill_distiller,
  scale_fill_fermenter,
  scale_fill_gradient,
  scale_fill_gradient2,
  scale_fill_gradientn,
  scale_fill_identity,
  scale_fill_log10,
  scale_fill_manual,
  scale_fill_sqrt,
  scale_fill_steps,
  scale_fill_steps2,
  scale_fill_stepsn,
  scale_fill_viridis_b,
  scale_fill_viridis_c,
  scale_fill_viridis_d,
  scale_fill_hue,
  scale_fill_grey,
  scale_fill_gray,
  scale_fill_ordinal,
  scaleXBinned,
  scaleXContinuous,
  scaleXDate,
  scaleXDatetime,
  scaleXTime,
  scaleXDiscrete,
  scaleXLog10,
  scaleXReverse,
  scaleXSqrt,
  scaleYBinned,
  scaleYContinuous,
  scaleYDate,
  scaleYDatetime,
  scaleYTime,
  scaleYDiscrete,
  scaleYLog10,
  scaleYReverse,
  scaleYSqrt,
  scale_x_binned,
  scale_x_continuous,
  scale_x_date,
  scale_x_datetime,
  scale_x_time,
  scale_x_discrete,
  scale_x_log10,
  scale_x_reverse,
  scale_x_sqrt,
  scale_y_binned,
  scale_y_continuous,
  scale_y_date,
  scale_y_datetime,
  scale_y_time,
  scale_y_discrete,
  scale_y_log10,
  scale_y_reverse,
  scale_y_sqrt,
} from "./scale-helpers.js";
export {
  scaleAlpha,
  scaleAlphaBinned,
  scaleAlphaContinuous,
  scaleAlphaDate,
  scaleAlphaDatetime,
  scaleAlphaDiscrete,
  scaleAlphaIdentity,
  scaleAlphaManual,
  scaleAlphaOrdinal,
  scaleLinewidth,
  scaleLinewidthBinned,
  scaleLinewidthContinuous,
  scaleLinewidthDate,
  scaleLinewidthDatetime,
  scaleLinewidthDiscrete,
  scaleLinewidthIdentity,
  scaleLinewidthManual,
  scaleLinewidthOrdinal,
  scaleLinetype,
  scaleLinetypeBinned,
  scaleLinetypeDiscrete,
  scaleLinetypeIdentity,
  scaleLinetypeManual,
  scaleShape,
  scaleShapeBinned,
  scaleShapeDiscrete,
  scaleShapeIdentity,
  scaleShapeManual,
  scaleShapeOrdinal,
  scaleSize,
  scaleSizeArea,
  scaleSizeBinned,
  scaleSizeBinnedArea,
  scaleSizeContinuous,
  scaleSizeDate,
  scaleSizeDatetime,
  scaleSizeDiscrete,
  scaleSizeIdentity,
  scaleSizeManual,
  scaleSizeOrdinal,
  scaleRadius,
  scale_alpha,
  scale_alpha_binned,
  scale_alpha_continuous,
  scale_alpha_date,
  scale_alpha_datetime,
  scale_alpha_discrete,
  scale_alpha_identity,
  scale_alpha_manual,
  scale_alpha_ordinal,
  scale_linetype,
  scale_linetype_binned,
  scale_linetype_discrete,
  scale_linetype_identity,
  scale_linetype_manual,
  scale_linewidth,
  scale_linewidth_binned,
  scale_linewidth_continuous,
  scale_linewidth_date,
  scale_linewidth_datetime,
  scale_linewidth_discrete,
  scale_linewidth_identity,
  scale_linewidth_manual,
  scale_linewidth_ordinal,
  scale_shape,
  scale_shape_binned,
  scale_shape_discrete,
  scale_shape_identity,
  scale_shape_manual,
  scale_shape_ordinal,
  scale_size,
  scale_size_area,
  scale_size_binned,
  scale_size_binned_area,
  scale_size_continuous,
  scale_size_date,
  scale_size_datetime,
  scale_size_discrete,
  scale_size_identity,
  scale_size_manual,
  scale_size_ordinal,
  scale_radius,
} from "./scale-helpers.js";
export type {
  BinnedColorScaleOptions,
  ColorBrewerScaleOptions,
  ColorDistillerScaleOptions,
  ColorFermenterScaleOptions,
  ColorScaleOptions,
  ContinuousPositionScaleOptions,
  DiscreteColorScaleOptions,
  IdentityColorScaleOptions,
  StepsScaleOptions,
  Steps2ScaleOptions,
  StepsnScaleOptions,
  GradientScaleOptions,
  Gradient2ScaleOptions,
  GradientnScaleOptions,
  HueScaleOptions,
  GreyScaleOptions,
  OrdinalColorScaleOptions,
  ManualColorScaleOptions,
  ViridisOptionName,
  ViridisScaleOptions,
  MultiIdentityScaleOptions,
  MultiManualScaleOptions,
  MultiScaleAesthetic,
  MultiScaleChannel,
  RecommendedScaleType,
  ScaleTypeAesthetic,
  DiscreteNumericStyleScaleOptions,
  BinnedFiniteStyleScaleOptions,
  DiscreteFiniteStyleScaleOptions,
  FiniteStyleScaleOptions,
  IdentityFiniteStyleScaleOptions,
  IdentityNumericStyleScaleOptions,
  ManualFiniteStyleScaleOptions,
  ManualNumericStyleScaleOptions,
  NumericStyleScaleOptions,
  SequentialStyleScaleOptions,
  SizeAreaScaleOptions,
  SizeSequentialStyleScaleOptions,
  SizeTemporalNumericStyleScaleOptions,
  TemporalNumericStyleScaleOptions,
  SequentialColorScaleOptions,
  TemporalColorScaleOptions,
  TransformedColorScaleOptions,
  DiscretePositionScaleOptions,
  TemporalScaleOptions,
  TransformedPositionScaleOptions,
} from "./scale-helpers.js";

// Portability (PortableSpec vs RuntimeSpec)
export {
  isPortable,
  portabilityIssues,
  toPortable,
  toPortableLossy,
  UnportableSpecError,
} from "./portability.js";
export type { JSONValue, LossyResult, PortabilityIssue } from "./portability.js";
export type {
  ChannelFn,
  RuntimeAes,
  RuntimeAreaLayer,
  RuntimeBarLayer,
  RuntimeBoxplotLayer,
  RuntimeChannelValue,
  RuntimeColLayer,
  RuntimeDensityLayer,
  RuntimeErrorbarLayer,
  RuntimeLinerangeLayer,
  RuntimePointrangeLayer,
  RuntimeCrossbarLayer,
  RuntimeRibbonLayer,
  RuntimeHistogramLayer,
  RuntimeFreqpolyLayer,
  RuntimeHlineLayer,
  RuntimeJitterLayer,
  RuntimeLayerSpec,
  RuntimeLineLayer,
  RuntimePathLayer,
  RuntimePointLayer,
  RuntimeRasterLayer,
  RuntimeHexLayer,
  RuntimeRectLayer,
  RuntimeSegmentLayer,
  RuntimeCountLayer,
  RuntimeViolinLayer,
  RuntimeFunctionLayer,
  RuntimePolygonLayer,
  RuntimeAblineLayer,
  RuntimeContourLayer,
  RuntimeDensity2dLayer,
  RuntimeDensity2dFilledLayer,
  RuntimeDotplotLayer,
  RuntimeMapLayer,
  RuntimeBlankLayer,
  RuntimeSpokeLayer,
  RuntimeRugLayer,
  RuntimeSfLayer,
  RuntimeSfTextLayer,
  RuntimeSfLabelLayer,
  RuntimeCurveLayer,
  RuntimeStepLayer,
  RuntimeQqLayer,
  RuntimeQqLineLayer,
  RuntimeRuleLayer,
  RuntimeSmoothLayer,
  RuntimeQuantileLayer,
  RuntimeSpec,
  RuntimeTextLayer,
  RuntimeLabelLayer,
  RuntimeTileLayer,
  RuntimeBin2dLayer,
  RuntimeVlineLayer,
} from "./runtime.js";

// Canonicalizer
/** @lifecycle stable-intent */
export { normalize } from "./normalize.js";
export { normalizeChannel } from "./normalize.js";
export type {
  AesInput,
  AreaLayerInput,
  BarLayerInput,
  BoxplotLayerInput,
  ChannelInput,
  ColLayerInput,
  DensityLayerInput,
  ErrorbarLayerInput,
  LinerangeLayerInput,
  PointrangeLayerInput,
  CrossbarLayerInput,
  RibbonLayerInput,
  SegmentLayerInput,
  CountLayerInput,
  ViolinLayerInput,
  FunctionLayerInput,
  PolygonLayerInput,
  AblineLayerInput,
  ContourLayerInput,
  Density2dLayerInput,
  Density2dFilledLayerInput,
  DotplotLayerInput,
  MapLayerInput,
  BlankLayerInput,
  SpokeLayerInput,
  RugLayerInput,
  SfLayerInput,
  SfTextLayerInput,
  SfLabelLayerInput,
  CurveLayerInput,
  StepLayerInput,
  QqLayerInput,
  QqLineLayerInput,
  FacetFieldInput,
  FacetInput,
  HistogramLayerInput,
  FreqpolyLayerInput,
  HlineLayerInput,
  JitterLayerInput,
  LayerInput,
  LineLayerInput,
  PathLayerInput,
  PointLayerInput,
  RasterLayerInput,
  HexLayerInput,
  RectLayerInput,
  RuleLayerInput,
  QuantileLayerInput,
  SmoothLayerInput,
  TileLayerInput,
  Bin2dLayerInput,
  SpecInput,
  TextLayerInput,
  LabelLayerInput,
  VlineLayerInput,
} from "./normalize.js";

// Validation + agent error contract
/** @lifecycle stable-intent */
export { validate } from "./validate.js";
/** @lifecycle stable-intent */
export type { ValidateResult } from "./validate.js";
export { LINT_CATALOG, lintSpec } from "./lint.js";
export type { LintAdvisoryCode, LintCatalogEntry, SpecAdvisory } from "./lint.js";
export { ERROR_CATALOG } from "./errors.js";
export type { ErrorCatalogEntry } from "./errors.js";
export { PIPELINE_ERROR_CATALOG } from "./pipeline-error-catalog.js";
export type { PipelineErrorCatalogEntry, PipelineErrorCode } from "./pipeline-error-catalog.js";
export { DEFAULT_VALIDATE_LIMITS, effectiveChannel, STAT_COLUMNS } from "./validate-data.js";
export type {
  DataProfile,
  DataProfileField,
  ProfileFieldType,
  ValidateLimits,
  ValidateOptions,
} from "./validate-data.js";
export {
  didYouMean,
  ERROR_CODES,
  levenshtein,
  SpecValidationError, // @lifecycle stable-intent
} from "./errors.js";
/** @lifecycle stable-intent */
export type { SpecError, SpecErrorCode, SpecErrorFix } from "./errors.js";

// Fluent builder
export { aes, gg, GGBuilder } from "./builder.js";
export type {
  AuthoringCellValue,
  AuthoringColumns,
  AuthoringDataRef,
  AuthoringRows,
  DataInput,
  GeomAreaOptions,
  GeomBarOptions,
  GeomBoxplotOptions,
  GeomColOptions,
  GeomDensityOptions,
  GeomDensity2dOptions,
  GeomDensity2dFilledOptions,
  GeomDotplotOptions,
  GeomErrorbarOptions,
  GeomLinerangeOptions,
  GeomPointrangeOptions,
  GeomCrossbarOptions,
  GeomHistogramOptions,
  GeomFreqpolyOptions,
  GeomHlineOptions,
  GeomJitterOptions,
  GeomLineOptions,
  GeomPathOptions,
  GeomPointOptions,
  GeomQuantileOptions,
  GeomContourOptions,
  GeomRasterOptions,
  GeomHexOptions,
  GeomRectOptions,
  GeomRuleOptions,
  GeomRugOptions,
  GeomSegmentOptions,
  GeomCountOptions,
  GeomViolinOptions,
  GeomFunctionOptions,
  GeomPolygonOptions,
  GeomAblineOptions,
  GeomCurveOptions,
  GeomMapOptions,
  GeomBlankOptions,
  GeomSpokeOptions,
  GeomSfOptions,
  GeomSfTextOptions,
  GeomSfLabelOptions,
  GeomStepOptions,
  GeomQqOptions,
  GeomQqLineOptions,
  GeomSmoothOptions,
  GeomTextOptions,
  GeomLabelOptions,
  GeomTileOptions,
  GeomBin2dOptions,
  GeomVlineOptions,
} from "./builder.js";

// Within-mark paint helpers (#591)
export {
  fillPaintLinear,
  fillPaintRadial,
  glow,
  strokePaintLinear,
  strokePaintRadial,
} from "./paint-helpers.js";
export type {
  ColorStopInput,
  GlowOptions,
  LinearPaintOptions,
  RadialPaintOptions,
} from "./paint-helpers.js";

// Schema artifact (schema/v0.json)
export { buildSchemaArtifact, SCHEMA_VERSION, schemaArtifactJSON } from "./artifact.js";
