// @ggsvelte/spec — spec types, schemas, normalize(), validate(), portability,
// fluent builder. Zero d3, zero DOM. TypeBox is the schema source of truth
// (decision 0004): the same definitions provide the TS types (Static<>), the
// runtime validator, and the published JSON Schema artifact (schema/v0.json).
//
// Lifecycle (Hadley lesson 13; meanings in CONTRIBUTING.md): every export
// carries a lifecycle tag, collected into the generated lifecycle.json by
// scripts/gen-lifecycle.ts. Untagged exports inherit the file default below;
// statements tag themselves with a one-line "@lifecycle <tag>" JSDoc marker;
// individual names use a trailing "@lifecycle <tag>" line comment.
// @lifecycle-default experimental

// Schemas + Static types
export {
  AesSchema,
  AreaLayerSchema,
  BarLayerSchema,
  BoxplotLayerSchema,
  CATEGORICAL_SCHEME_NAMES,
  CHANNELS,
  COLOR_SCHEME_NAMES,
  ChannelValueSchema,
  ColLayerSchema,
  CoordSpecSchema,
  CoordFixedSpecSchema,
  CoordTransformAxisSpecSchema,
  CoordTransformSpecSchema,
  CURRENT_EDITION,
  DataRefSchema,
  DensityLayerSchema,
  ErrorbarLayerSchema,
  RectLayerSchema,
  TileLayerSchema,
  RasterLayerSchema,
  RibbonLayerSchema,
  SegmentLayerSchema,
  FacetSpecSchema,
  GEOM_DEFAULTS,
  HistogramLayerSchema,
  KNOWN_GEOMS,
  KNOWN_POSITIONS,
  KNOWN_STATS,
  LayerSpecSchema,
  LineLayerSchema,
  LINETYPE_NAMES,
  MAX_BINNED_BREAKS,
  MAX_GLOW_RADIUS,
  MAX_PAINT_STOPS,
  POINT_SHAPE_NAMES,
  PlotSpecSchema,
  PointLayerSchema,
  RuleLayerSchema,
  ScalesSchema,
  SEQUENTIAL_SCHEME_NAMES,
  TemporalParserSpecSchemaRef,
  SmoothLayerSchema,
  SpecModule,
  TextLayerSchema,
  THEME_NAMES,
} from "./schema.js";
export type {
  A11yMode,
  Aes,
  AreaLayer,
  AreaParams,
  BarLayer,
  BarParams,
  BoxplotLayer,
  BoxplotParams,
  CellValue,
  ChannelName,
  ChannelValue,
  ColorStop,
  ColLayer,
  ColorScaleSpec,
  GradientPaint,
  GlowSpec,
  LinearGradientPaint,
  PaintSpace,
  RadialGradientPaint,
  AlphaScaleSpec,
  ColParams,
  CoordSpec,
  CoordFixedSpec,
  CoordTransformAxisSpec,
  CoordTransformSpec,
  DataColumns,
  DataName,
  DataRef,
  DataValues,
  DensityLayer,
  DensityParams,
  ErrorbarLayer,
  ErrorbarParams,
  RectLayer,
  RectParams,
  TileLayer,
  TileParams,
  RasterLayer,
  RasterParams,
  RibbonLayer,
  RibbonParams,
  FacetScales,
  FacetSpec,
  GeomName,
  GuideSpec,
  GuidesSpec,
  GuideThemeSpec,
  AxisGuideSpec,
  LegendGuideSpec,
  ColorbarGuideSpec,
  ColorstepsGuideSpec,
  NoneGuideSpec,
  HistogramLayer,
  InlineData,
  Labs,
  LayerSpec,
  LegendSpec,
  LineLayer,
  LineParams,
  PointLayer,
  PointParams,
  PointPosition,
  PortableSpec, // @lifecycle stable-intent
  PositionName,
  PositionParams,
  PositionScaleSpec,
  PositiveStyleScaleSpec,
  ShapeScaleSpec,
  LinetypeScaleSpec,
  LinetypeName,
  PointShapeName,
  RenderBackend,
  RuleLayer,
  RuleParams,
  SegmentLayer,
  SegmentParams,
  ScaleExpansion,
  Scales,
  SmoothLayer,
  SmoothParams,
  StackablePosition,
  StatName,
  SummaryFun,
  TextLayer,
  TemporalParserSpec,
  TextParams,
  ThemeName,
  ThemeSpec,
} from "./schema.js";

export {
  guideAxis,
  guideColorbar,
  guideColorsteps,
  guideLegend,
  guideNone,
  guides,
  guide_axis,
  guide_colorbar,
  guide_colorsteps,
  guide_legend,
  guide_none,
} from "./guide-helpers.js";
export type {
  AxisGuideOptions,
  ColorbarGuideOptions,
  ColorstepsGuideOptions,
  LegendGuideOptions,
} from "./guide-helpers.js";

// Checked public capability ledger
export { SCALE_CAPABILITIES, STYLE_AESTHETIC_GEOMS } from "./capabilities.js";
export type { ScaleCapability, StyleAesthetic } from "./capabilities.js";

// Temporal parsing, inference, and authoring conversions
export {
  canonicalTemporalParserKey,
  dmy,
  dmy_hm,
  dmy_hms,
  dym,
  dym_hm,
  dym_hms,
  fromEpochMilliseconds,
  fromEpochSeconds,
  inferTemporalColumn,
  mdy,
  mdy_hm,
  mdy_hms,
  my,
  myd,
  myd_hm,
  myd_hms,
  parseTemporal,
  parseTemporalColumn,
  parseTemporalFormat,
  TEMPORAL_PARSER_NAMES,
  temporalParserConfigurationError,
  TemporalParseError,
  TemporalParserSpecSchema,
  ydm,
  ydm_hm,
  ydm_hms,
  ym,
  ymd,
  ymd_hm,
  ymd_hms,
  yq,
} from "./temporal.js";
export type {
  TemporalDecision,
  TemporalDisambiguation,
  TemporalFailure,
  TemporalKind,
  ParsedTemporalColumn,
  TemporalParseOptions,
  TemporalParseResult,
  TemporalParserName,
  TemporalPrecision,
} from "./temporal.js";
export {
  MAX_TEMPORAL_CANDIDATES,
  MAX_TEMPORAL_MAJOR_TICKS,
  MAX_TEMPORAL_MINOR_TICKS,
  MIN_TEMPORAL_LABEL_GAP_PX,
  parseTemporalInterval,
  TEMPORAL_INTERVAL_UNITS,
  TEMPORAL_LABEL_TOKENS,
  TEMPORAL_WEEKDAYS,
  TemporalIntervalError,
  TemporalIntervalSpecSchema,
  TemporalLabelSpecSchema,
  temporalIntervalTicks,
  temporalLabelConfigurationError,
  temporalLocaleConfigurationError,
  TemporalWeekStartSchema,
} from "./temporal-guides.js";
export type {
  TemporalInterval,
  TemporalIntervalSpec,
  TemporalIntervalUnit,
  TemporalWeekStart,
} from "./temporal-guides.js";

// Coordinate helpers
export {
  coord_equal,
  coord_fixed,
  coord_transform,
  coordEqual,
  coordFixed,
  coordTransform,
} from "./coord-helpers.js";
export type {
  CoordFixedOptions,
  CoordTransformAxisOptions,
  CoordTransformName,
  CoordTransformOptions,
} from "./coord-helpers.js";

// Scale helpers
export {
  configuredColorScaleType,
  scaleColorBinned,
  scaleColorContinuous,
  scaleColorDate,
  scaleColorDatetime,
  scaleColorDiscrete,
  scaleColorIdentity,
  scaleColorLog10,
  scaleColorManual,
  scaleColorSqrt,
  scaleColourBinned,
  scaleColourContinuous,
  scaleColourDate,
  scaleColourDatetime,
  scaleColourDiscrete,
  scaleColourIdentity,
  scaleColourLog10,
  scaleColourManual,
  scaleColourSqrt,
  scaleFillBinned,
  scaleFillContinuous,
  scaleFillDate,
  scaleFillDatetime,
  scaleFillDiscrete,
  scaleFillIdentity,
  scaleFillLog10,
  scaleFillManual,
  scaleFillSqrt,
  scale_color_binned,
  scale_color_continuous,
  scale_color_date,
  scale_color_datetime,
  scale_color_discrete,
  scale_color_identity,
  scale_color_log10,
  scale_color_manual,
  scale_color_sqrt,
  scale_colour_binned,
  scale_colour_continuous,
  scale_colour_date,
  scale_colour_datetime,
  scale_colour_discrete,
  scale_colour_identity,
  scale_colour_log10,
  scale_colour_manual,
  scale_colour_sqrt,
  scale_fill_binned,
  scale_fill_continuous,
  scale_fill_date,
  scale_fill_datetime,
  scale_fill_discrete,
  scale_fill_identity,
  scale_fill_log10,
  scale_fill_manual,
  scale_fill_sqrt,
  scaleXBinned,
  scaleXContinuous,
  scaleXDate,
  scaleXDatetime,
  scaleXDiscrete,
  scaleXLog10,
  scaleXReverse,
  scaleXSqrt,
  scaleYBinned,
  scaleYContinuous,
  scaleYDate,
  scaleYDatetime,
  scaleYDiscrete,
  scaleYLog10,
  scaleYReverse,
  scaleYSqrt,
  scale_x_binned,
  scale_x_continuous,
  scale_x_date,
  scale_x_datetime,
  scale_x_discrete,
  scale_x_log10,
  scale_x_reverse,
  scale_x_sqrt,
  scale_y_binned,
  scale_y_continuous,
  scale_y_date,
  scale_y_datetime,
  scale_y_discrete,
  scale_y_log10,
  scale_y_reverse,
  scale_y_sqrt,
} from "./scale-helpers.js";
export {
  scaleAlpha,
  scaleAlphaBinned,
  scaleAlphaContinuous,
  scaleAlphaDate,
  scaleAlphaDatetime,
  scaleAlphaDiscrete,
  scaleAlphaIdentity,
  scaleAlphaManual,
  scaleLinewidth,
  scaleLinewidthBinned,
  scaleLinewidthContinuous,
  scaleLinewidthDate,
  scaleLinewidthDatetime,
  scaleLinewidthDiscrete,
  scaleLinewidthIdentity,
  scaleLinewidthManual,
  scaleLinetype,
  scaleLinetypeBinned,
  scaleLinetypeDiscrete,
  scaleLinetypeIdentity,
  scaleLinetypeManual,
  scaleShape,
  scaleShapeBinned,
  scaleShapeDiscrete,
  scaleShapeIdentity,
  scaleShapeManual,
  scaleSize,
  scaleSizeBinned,
  scaleSizeContinuous,
  scaleSizeDate,
  scaleSizeDatetime,
  scaleSizeDiscrete,
  scaleSizeIdentity,
  scaleSizeManual,
  scale_alpha_binned,
  scale_alpha_continuous,
  scale_alpha_date,
  scale_alpha_datetime,
  scale_alpha_discrete,
  scale_alpha_identity,
  scale_alpha_manual,
  scale_linetype,
  scale_linetype_binned,
  scale_linetype_discrete,
  scale_linetype_identity,
  scale_linetype_manual,
  scale_linewidth_binned,
  scale_linewidth_continuous,
  scale_linewidth_date,
  scale_linewidth_datetime,
  scale_linewidth_discrete,
  scale_linewidth_identity,
  scale_linewidth_manual,
  scale_shape,
  scale_shape_binned,
  scale_shape_discrete,
  scale_shape_identity,
  scale_shape_manual,
  scale_size_binned,
  scale_size_continuous,
  scale_size_date,
  scale_size_datetime,
  scale_size_discrete,
  scale_size_identity,
  scale_size_manual,
} from "./scale-helpers.js";
export type {
  BinnedColorScaleOptions,
  ColorScaleOptions,
  ContinuousPositionScaleOptions,
  DiscreteColorScaleOptions,
  IdentityColorScaleOptions,
  ManualColorScaleOptions,
  DiscreteNumericStyleScaleOptions,
  BinnedFiniteStyleScaleOptions,
  DiscreteFiniteStyleScaleOptions,
  FiniteStyleScaleOptions,
  IdentityFiniteStyleScaleOptions,
  IdentityNumericStyleScaleOptions,
  ManualFiniteStyleScaleOptions,
  ManualNumericStyleScaleOptions,
  NumericStyleScaleOptions,
  SequentialStyleScaleOptions,
  TemporalNumericStyleScaleOptions,
  SequentialColorScaleOptions,
  TemporalColorScaleOptions,
  TransformedColorScaleOptions,
  DiscretePositionScaleOptions,
  TemporalScaleOptions,
  TransformedPositionScaleOptions,
} from "./scale-helpers.js";

// Portability (PortableSpec vs RuntimeSpec)
export {
  isPortable,
  portabilityIssues,
  toPortable,
  toPortableLossy,
  UnportableSpecError,
} from "./portability.js";
export type { JSONValue, LossyResult, PortabilityIssue } from "./portability.js";
export type {
  ChannelFn,
  RuntimeAes,
  RuntimeAreaLayer,
  RuntimeBarLayer,
  RuntimeBoxplotLayer,
  RuntimeChannelValue,
  RuntimeColLayer,
  RuntimeDensityLayer,
  RuntimeErrorbarLayer,
  RuntimeRibbonLayer,
  RuntimeHistogramLayer,
  RuntimeLayerSpec,
  RuntimeLineLayer,
  RuntimePointLayer,
  RuntimeRasterLayer,
  RuntimeRectLayer,
  RuntimeSegmentLayer,
  RuntimeRuleLayer,
  RuntimeSmoothLayer,
  RuntimeSpec,
  RuntimeTextLayer,
  RuntimeTileLayer,
} from "./runtime.js";

// Canonicalizer
/** @lifecycle stable-intent */
export { normalize } from "./normalize.js";
export { normalizeChannel } from "./normalize.js";
export type {
  AesInput,
  AreaLayerInput,
  BarLayerInput,
  BoxplotLayerInput,
  ChannelInput,
  ColLayerInput,
  DensityLayerInput,
  ErrorbarLayerInput,
  RibbonLayerInput,
  SegmentLayerInput,
  FacetInput,
  HistogramLayerInput,
  LayerInput,
  LineLayerInput,
  PointLayerInput,
  RasterLayerInput,
  RectLayerInput,
  RuleLayerInput,
  SmoothLayerInput,
  TileLayerInput,
  SpecInput,
  TextLayerInput,
} from "./normalize.js";

// Validation + agent error contract
/** @lifecycle stable-intent */
export { validate } from "./validate.js";
/** @lifecycle stable-intent */
export type { ValidateResult } from "./validate.js";
export { LINT_CATALOG, lintSpec } from "./lint.js";
export type { LintAdvisoryCode, LintCatalogEntry, SpecAdvisory } from "./lint.js";
export { ERROR_CATALOG } from "./errors.js";
export type { ErrorCatalogEntry } from "./errors.js";
export { DEFAULT_VALIDATE_LIMITS, effectiveChannel, STAT_COLUMNS } from "./validate-data.js";
export type {
  DataProfile,
  DataProfileField,
  ProfileFieldType,
  ValidateLimits,
  ValidateOptions,
} from "./validate-data.js";
export {
  didYouMean,
  ERROR_CODES,
  levenshtein,
  SpecValidationError, // @lifecycle stable-intent
} from "./errors.js";
/** @lifecycle stable-intent */
export type { SpecError, SpecErrorCode, SpecErrorFix } from "./errors.js";

// Fluent builder
export { aes, gg, GGBuilder } from "./builder.js";
export type {
  AuthoringCellValue,
  AuthoringColumns,
  AuthoringDataRef,
  AuthoringRows,
  DataInput,
  GeomAreaOptions,
  GeomBarOptions,
  GeomBoxplotOptions,
  GeomColOptions,
  GeomDensityOptions,
  GeomErrorbarOptions,
  GeomHistogramOptions,
  GeomLineOptions,
  GeomPointOptions,
  GeomRasterOptions,
  GeomRectOptions,
  GeomRuleOptions,
  GeomSegmentOptions,
  GeomSmoothOptions,
  GeomTextOptions,
  GeomTileOptions,
} from "./builder.js";

// Within-mark paint helpers (#591)
export {
  fillPaintLinear,
  fillPaintRadial,
  glow,
  strokePaintLinear,
  strokePaintRadial,
} from "./paint-helpers.js";
export type {
  ColorStopInput,
  GlowOptions,
  LinearPaintOptions,
  RadialPaintOptions,
} from "./paint-helpers.js";

// Schema artifact (schema/v0.json)
export { buildSchemaArtifact, SCHEMA_VERSION, schemaArtifactJSON } from "./artifact.js";
