/**
 * Scale authoring helpers facade — position, color/fill, and style families.
 *
 * Implementation:
 *  - scale-position-helpers.ts — temporal, discrete, continuous, binned, reverse
 *  - scale-color-helpers.ts — color/fill families + configuredColorScaleType
 *  - scale-style-helpers.ts — numeric and finite-symbol style families
 *  - scale-multi-helpers.ts — multi-aes identity/manual + scaleType (#833)
 *
 * Public package imports continue through this module for stable paths.
 */

export {
  scaleXDate,
  scaleXDatetime,
  scaleXTime,
  scaleYDate,
  scaleYDatetime,
  scaleYTime,
  scaleXDiscrete,
  scaleYDiscrete,
  scale_x_date,
  scale_x_datetime,
  scale_x_time,
  scale_y_date,
  scale_y_datetime,
  scale_y_time,
  scale_x_discrete,
  scale_y_discrete,
  scaleXContinuous,
  scaleYContinuous,
  scaleXLog10,
  scaleYLog10,
  scaleXSqrt,
  scaleYSqrt,
  scaleXReverse,
  scaleYReverse,
  scaleXBinned,
  scaleYBinned,
  scale_x_continuous,
  scale_y_continuous,
  scale_x_log10,
  scale_y_log10,
  scale_x_sqrt,
  scale_y_sqrt,
  scale_x_reverse,
  scale_y_reverse,
  scale_x_binned,
  scale_y_binned,
  type TemporalScaleOptions,
  type ContinuousPositionScaleOptions,
  type TransformedPositionScaleOptions,
  type DiscretePositionScaleOptions,
} from "./scale-position-helpers.js";

export {
  configuredColorScaleType,
  scaleColorContinuous,
  scaleColorDiscrete,
  scaleColorBinned,
  scaleColorLog10,
  scaleColorSqrt,
  scaleColorDate,
  scaleColorDatetime,
  scaleColorManual,
  scaleColorIdentity,
  scaleColorBrewer,
  scaleColorDistiller,
  scaleColorFermenter,
  scaleColorSteps,
  scaleColorSteps2,
  scaleColorStepsn,
  scaleColorGradient,
  scaleColorGradient2,
  scaleColorGradientn,
  scaleColorHue,
  scaleColorGrey,
  scaleColorGray,
  scaleColorOrdinal,
  scaleColourContinuous,
  scaleColourDiscrete,
  scaleColourBinned,
  scaleColourLog10,
  scaleColourSqrt,
  scaleColourDate,
  scaleColourDatetime,
  scaleColourManual,
  scaleColourIdentity,
  scaleColourBrewer,
  scaleColourDistiller,
  scaleColourFermenter,
  scaleColourSteps,
  scaleColourSteps2,
  scaleColourStepsn,
  scaleColourGradient,
  scaleColourGradient2,
  scaleColourGradientn,
  scaleColourHue,
  scaleColourGrey,
  scaleColourGray,
  scaleColourOrdinal,
  scale_color_continuous,
  scale_color_discrete,
  scale_color_binned,
  scale_color_log10,
  scale_color_sqrt,
  scale_color_date,
  scale_color_datetime,
  scale_color_manual,
  scale_color_identity,
  scale_color_brewer,
  scale_color_distiller,
  scale_color_fermenter,
  scale_color_steps,
  scale_color_steps2,
  scale_color_stepsn,
  scale_color_gradient,
  scale_color_gradient2,
  scale_color_gradientn,
  scale_color_hue,
  scale_color_grey,
  scale_color_gray,
  scale_color_ordinal,
  scale_colour_continuous,
  scale_colour_discrete,
  scale_colour_binned,
  scale_colour_log10,
  scale_colour_sqrt,
  scale_colour_date,
  scale_colour_datetime,
  scale_colour_manual,
  scale_colour_identity,
  scale_colour_brewer,
  scale_colour_distiller,
  scale_colour_fermenter,
  scale_colour_steps,
  scale_colour_steps2,
  scale_colour_stepsn,
  scale_colour_gradient,
  scale_colour_gradient2,
  scale_colour_gradientn,
  scale_colour_hue,
  scale_colour_grey,
  scale_colour_gray,
  scale_colour_ordinal,
  scaleFillContinuous,
  scaleFillDiscrete,
  scaleFillBinned,
  scaleFillLog10,
  scaleFillSqrt,
  scaleFillDate,
  scaleFillDatetime,
  scaleFillManual,
  scaleFillIdentity,
  scaleFillBrewer,
  scaleFillDistiller,
  scaleFillFermenter,
  scaleFillSteps,
  scaleFillSteps2,
  scaleFillStepsn,
  scaleFillGradient,
  scaleFillGradient2,
  scaleFillGradientn,
  scaleFillHue,
  scaleFillGrey,
  scaleFillGray,
  scaleFillOrdinal,
  scale_fill_continuous,
  scale_fill_discrete,
  scale_fill_binned,
  scale_fill_log10,
  scale_fill_sqrt,
  scale_fill_date,
  scale_fill_datetime,
  scale_fill_manual,
  scale_fill_identity,
  scale_fill_brewer,
  scale_fill_distiller,
  scale_fill_fermenter,
  scale_fill_steps,
  scale_fill_steps2,
  scale_fill_stepsn,
  scaleColorViridisC,
  scaleColorViridisD,
  scaleColorViridisB,
  scaleColourViridisC,
  scaleColourViridisD,
  scaleColourViridisB,
  scaleFillViridisC,
  scaleFillViridisD,
  scaleFillViridisB,
  scale_color_viridis_c,
  scale_color_viridis_d,
  scale_color_viridis_b,
  scale_colour_viridis_c,
  scale_colour_viridis_d,
  scale_colour_viridis_b,
  scale_fill_viridis_c,
  scale_fill_viridis_d,
  scale_fill_viridis_b,
  scale_fill_gradient,
  scale_fill_gradient2,
  scale_fill_gradientn,
  scale_fill_hue,
  scale_fill_grey,
  scale_fill_gray,
  scale_fill_ordinal,
  type ColorScaleOptions,
  type SequentialColorScaleOptions,
  type BinnedColorScaleOptions,
  type DiscreteColorScaleOptions,
  type TransformedColorScaleOptions,
  type TemporalColorScaleOptions,
  type ManualColorScaleOptions,
  type IdentityColorScaleOptions,
  type ColorBrewerScaleOptions,
  type ColorDistillerScaleOptions,
  type ColorFermenterScaleOptions,
  type StepsScaleOptions,
  type Steps2ScaleOptions,
  type StepsnScaleOptions,
  type ViridisScaleOptions,
  type ViridisOptionName,
  type GradientScaleOptions,
  type Gradient2ScaleOptions,
  type GradientnScaleOptions,
  type HueScaleOptions,
  type GreyScaleOptions,
  type OrdinalColorScaleOptions,
} from "./scale-color-helpers.js";

export * from "./scale-style-helpers.js";

export {
  scaleContinuousIdentity,
  scaleDiscreteIdentity,
  scaleDiscreteManual,
  scaleType,
  scale_continuous_identity,
  scale_discrete_identity,
  scale_discrete_manual,
  scale_type,
  canonicalMultiScaleChannel,
  type MultiScaleAesthetic,
  type MultiScaleChannel,
  type MultiIdentityScaleOptions,
  type MultiManualScaleOptions,
  type ScaleTypeAesthetic,
  type RecommendedScaleType,
} from "./scale-multi-helpers.js";
