/**
 * Scale authoring helpers facade — position, color/fill, and style families.
 *
 * Implementation:
 *  - scale-position-helpers.ts — temporal, discrete, continuous, binned, reverse
 *  - scale-color-helpers.ts — color/fill families + configuredColorScaleType
 *  - scale-style-helpers.ts — numeric and finite-symbol style families
 *  - scale-multi-helpers.ts — multi-aes identity/manual + scaleType (#833)
 *
 * Public package imports continue through this module for stable paths.
 */

export {
  scaleXDate,
  scaleXDatetime,
  scaleYDate,
  scaleYDatetime,
  scaleXDiscrete,
  scaleYDiscrete,
  scale_x_date,
  scale_x_datetime,
  scale_y_date,
  scale_y_datetime,
  scale_x_discrete,
  scale_y_discrete,
  scaleXContinuous,
  scaleYContinuous,
  scaleXLog10,
  scaleYLog10,
  scaleXSqrt,
  scaleYSqrt,
  scaleXReverse,
  scaleYReverse,
  scaleXBinned,
  scaleYBinned,
  scale_x_continuous,
  scale_y_continuous,
  scale_x_log10,
  scale_y_log10,
  scale_x_sqrt,
  scale_y_sqrt,
  scale_x_reverse,
  scale_y_reverse,
  scale_x_binned,
  scale_y_binned,
  type TemporalScaleOptions,
  type ContinuousPositionScaleOptions,
  type TransformedPositionScaleOptions,
  type DiscretePositionScaleOptions,
} from "./scale-position-helpers.js";

export {
  configuredColorScaleType,
  scaleColorContinuous,
  scaleColorDiscrete,
  scaleColorBinned,
  scaleColorLog10,
  scaleColorSqrt,
  scaleColorDate,
  scaleColorDatetime,
  scaleColorManual,
  scaleColorIdentity,
  scaleColorGradient,
  scaleColorGradient2,
  scaleColorGradientn,
  scaleColourContinuous,
  scaleColourDiscrete,
  scaleColourBinned,
  scaleColourLog10,
  scaleColourSqrt,
  scaleColourDate,
  scaleColourDatetime,
  scaleColourManual,
  scaleColourIdentity,
  scaleColourGradient,
  scaleColourGradient2,
  scaleColourGradientn,
  scale_color_continuous,
  scale_color_discrete,
  scale_color_binned,
  scale_color_log10,
  scale_color_sqrt,
  scale_color_date,
  scale_color_datetime,
  scale_color_manual,
  scale_color_identity,
  scale_color_gradient,
  scale_color_gradient2,
  scale_color_gradientn,
  scale_colour_continuous,
  scale_colour_discrete,
  scale_colour_binned,
  scale_colour_log10,
  scale_colour_sqrt,
  scale_colour_date,
  scale_colour_datetime,
  scale_colour_manual,
  scale_colour_identity,
  scale_colour_gradient,
  scale_colour_gradient2,
  scale_colour_gradientn,
  scaleFillContinuous,
  scaleFillDiscrete,
  scaleFillBinned,
  scaleFillLog10,
  scaleFillSqrt,
  scaleFillDate,
  scaleFillDatetime,
  scaleFillManual,
  scaleFillIdentity,
  scaleFillGradient,
  scaleFillGradient2,
  scaleFillGradientn,
  scale_fill_continuous,
  scale_fill_discrete,
  scale_fill_binned,
  scale_fill_log10,
  scale_fill_sqrt,
  scale_fill_date,
  scale_fill_datetime,
  scale_fill_manual,
  scale_fill_identity,
  scale_fill_gradient,
  scale_fill_gradient2,
  scale_fill_gradientn,
  type ColorScaleOptions,
  type SequentialColorScaleOptions,
  type BinnedColorScaleOptions,
  type DiscreteColorScaleOptions,
  type TransformedColorScaleOptions,
  type TemporalColorScaleOptions,
  type ManualColorScaleOptions,
  type IdentityColorScaleOptions,
  type GradientScaleOptions,
  type Gradient2ScaleOptions,
  type GradientnScaleOptions,
} from "./scale-color-helpers.js";

export * from "./scale-style-helpers.js";

export {
  scaleContinuousIdentity,
  scaleDiscreteIdentity,
  scaleDiscreteManual,
  scaleType,
  scale_continuous_identity,
  scale_discrete_identity,
  scale_discrete_manual,
  scale_type,
  canonicalMultiScaleChannel,
  type MultiScaleAesthetic,
  type MultiScaleChannel,
  type MultiIdentityScaleOptions,
  type MultiManualScaleOptions,
  type ScaleTypeAesthetic,
  type RecommendedScaleType,
} from "./scale-multi-helpers.js";
