/**
 * `$defs` partial — data family (CellValue…Aes).
 * Composed by schema-declarations.ts via spread; key insertion order is load-bearing.
 */

import Type from "typebox";

export const DataDecls = {
  CellValue: Type.Union([Type.String(), Type.Number(), Type.Boolean(), Type.Null()], {
    description:
      'A single data cell: string, number, boolean, or null. Dates travel as ISO 8601 strings (e.g. "2026-07-10"); non-finite numbers travel as null.',
  }),

  DataValues: Type.Object(
    {
      values: Type.Array(
        Type.Object(
          {},
          {
            additionalProperties: Type.Ref("CellValue"),
            description: "One data row: an object mapping field names to cell values.",
          },
        ),
        {
          description: "Row-oriented inline data: an array of row objects sharing field names.",
        },
      ),
    },
    {
      additionalProperties: false,
      description: 'Inline row-oriented data. Example: {"values": [{"x": 1, "y": 2}]}.',
    },
  ),

  DataColumns: Type.Object(
    {
      columns: Type.Record(Type.String(), Type.Array(Type.Ref("CellValue")), {
        description:
          "Column-oriented inline data: an object mapping each field name to an array of cell values. All arrays must have the same length.",
      }),
    },
    {
      additionalProperties: false,
      description: 'Inline column-oriented data. Example: {"columns": {"x": [1, 2], "y": [3, 4]}}.',
    },
  ),

  DataName: Type.Object(
    {
      name: Type.String({
        description:
          "Name of a dataset provided out-of-band: either a key of the spec's top-level `datasets`, or a dataset passed by the host at render time.",
      }),
    },
    {
      additionalProperties: false,
      description: 'A reference to a named dataset. Example: {"name": "cars"}.',
    },
  ),

  DataRef: Type.Union([Type.Ref("DataValues"), Type.Ref("DataColumns"), Type.Ref("DataName")], {
    description:
      "Where a plot's data comes from: inline rows ({values}), inline columns ({columns}), or a named dataset ({name}). Exactly one form.",
  }),

  InlineData: Type.Union([Type.Ref("DataValues"), Type.Ref("DataColumns")], {
    description: "Inline data only ({values} or {columns}); used for entries of `datasets`.",
  }),

  FieldRef: Type.Object(
    {
      field: Type.String({
        description: "Name of the data column this channel reads from.",
      }),
    },
    {
      additionalProperties: false,
      description:
        'Map this channel to a data field (column). Example: {"field": "displ"}. This is the canonical form — bare strings are NOT valid channel values.',
    },
  ),

  ValueRef: Type.Object(
    {
      value: Type.Union([Type.String(), Type.Number(), Type.Boolean()], {
        description: "The constant value applied to every mark.",
      }),
      scale: Type.Optional(
        Type.Boolean({
          description:
            "If true, the constant is passed THROUGH the channel's scale (like a data value). Default false: the constant is used literally (e.g. a CSS color).",
        }),
      ),
    },
    {
      additionalProperties: false,
      description:
        'Map this channel to a constant. Example: {"value": "steelblue"} sets a literal color; {"value": "treatment", "scale": true} routes the constant through the scale.',
    },
  ),

  StatRef: Type.Object(
    {
      stat: Type.String({
        description:
          'Name of a stat-generated column computed after the layer\'s stat runs (e.g. "count" for the count stat). after_stat.',
      }),
    },
    {
      additionalProperties: false,
      description:
        'Map this channel to a column generated by the layer\'s stat (after-stat form). Example: {"stat": "count"}.',
    },
  ),

  ChannelValue: Type.Union(
    [Type.Ref("FieldRef"), Type.Ref("ValueRef"), Type.Ref("StatRef"), Type.Null()],
    {
      description:
        "How one aesthetic channel gets its value: a data field ({field}), a constant ({value, scale?}), a stat output ({stat}), or null to UNSET a channel inherited from the plot-level mapping. Bare strings are not valid.",
    },
  ),

  Aes: Type.Object(
    {
      x: Type.Optional(Type.Ref("ChannelValue", { description: "Horizontal position channel." })),
      y: Type.Optional(Type.Ref("ChannelValue", { description: "Vertical position channel." })),
      color: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Stroke/point color channel. Discrete fields get a categorical palette; quantitative fields get a sequential ramp.",
        }),
      ),
      fill: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Fill color channel (areas, bars, filled shapes). Discrete fields get a categorical palette; quantitative fields get a sequential ramp.",
        }),
      ),
      size: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Mark size channel (AREA-scaled — sqrt scale; use `linewidth` for stroke width, which scales linearly).",
        }),
      ),
      linewidth: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Stroke width channel (LENGTH-scaled — linear; distinct from `size`, which scales by area).",
        }),
      ),
      alpha: Type.Optional(
        Type.Ref("ChannelValue", {
          description: "Opacity channel, 0 (transparent) to 1 (opaque).",
        }),
      ),
      shape: Type.Optional(
        Type.Ref("ChannelValue", {
          description: "Finite point-symbol channel. Continuous values require a binned scale.",
        }),
      ),
      linetype: Type.Optional(
        Type.Ref("ChannelValue", {
          description: "Finite stroke-pattern channel. Continuous values require a binned scale.",
        }),
      ),
      group: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            'Explicit grouping channel. Overrides the default grouping (the interaction of all discrete mapped aesthetics). A constant (e.g. {"value": 1}) forces a single group.',
        }),
      ),
      label: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Text label channel (used by the text geom; never participates in grouping).",
        }),
      ),
      weight: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Statistical weight channel. The count, bin, and density stats sum weights instead of counting rows. Never participates in grouping.",
        }),
      ),
      sample: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Sample distribution channel for Q–Q plots. The qq / qq_line stats read this column; x/y become theoretical and sample quantiles after the stat. Never participates in grouping.",
        }),
      ),
      ymin: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Lower y bound (errorbar identity, rect edges, ribbon x-orientation). Quantitative values only.",
        }),
      ),
      ymax: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Upper y bound (errorbar identity, rect edges, ribbon x-orientation). Quantitative values only.",
        }),
      ),
      xmin: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Left edge / lower x bound (geom rect; ribbon y-orientation). Quantitative values only.",
        }),
      ),
      xmax: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Right edge / upper x bound (geom rect; ribbon y-orientation). Quantitative values only.",
        }),
      ),
      xend: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Segment end x (geom segment). Trains the x scale together with aes.x; may be discrete or continuous.",
        }),
      ),
      yend: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Segment end y (geom segment). Trains the y scale together with aes.y; may be discrete or continuous.",
        }),
      ),
      width: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Cell width for geom tile (data units after position transform; not a trained position scale). Prefer params.width for a constant.",
        }),
      ),
      height: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Cell height for geom tile (data units after position transform; not a trained position scale). Prefer params.height for a constant.",
        }),
      ),
      z: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Surface height for geom contour / stat contour (quantitative grid values over continuous x×y;).",
        }),
      ),
      map_id: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Region join key for geom_map (value-table column matched to the map data id column;).",
        }),
      ),
      angle: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Spoke direction in radians (geom spoke; 0 = +x, π/2 = +y). Quantitative only. May also be set as params.angle.",
        }),
      ),
      radius: Type.Optional(
        Type.Ref("ChannelValue", {
          description:
            "Spoke length in data units (geom spoke). Quantitative only. May also be set as params.radius.",
        }),
      ),
    },
    {
      additionalProperties: false,
      description:
        "Aesthetic mapping: which channels read which data fields/constants. Plot-level aes is inherited by every layer; a layer's aes overrides per channel, and null unsets an inherited channel.",
    },
  ),

  // --- within-mark paint (#591) ----------------------------------------------
};
