/**
 * The ggsvelte spec schema — TypeBox is the source of truth (decision 0004).
 *
 * These definitions ARE the published JSON Schema (via `Type.Cyclic` for named
 * `$defs`, emitted to `schema/v0.json` by `scripts/emit-schema.ts`) AND the TS
 * types (via `Static<>`) AND the runtime validator input (`Value.Check`).
 * One artifact, no drift.
 *
 * Authoring rules (from decision 0004):
 * - Strict objects everywhere (`additionalProperties: false`).
 * - Every field carries a description written for LLMs; numeric constraints
 *   are ALSO stated in descriptions because constrained-decoding grammars may
 *   drop or reject numeric keywords.
 * - No bare-string channel shorthand in the schema: agents emit canonical
 *   channel forms only. The shorthand exists only in the TS builder/adapter.
 * - Unions are `anyOf` by construction (TypeBox default) — the form OpenAI
 *   structured outputs accept.
 * - `Type.Record` is used for `data.columns`/`datasets` only; the artifact
 *   emitter rewrites its `patternProperties` to `additionalProperties`
 *   (semantically identical for the `^(.*)$` pattern) so the published
 *   schema stays inside portable JSON Schema.
 *
 * Layout: name registries (`schema-names.ts`), ordered `$defs` bag
 * (`schema-declarations.ts`), pipeline catalogs (`schema-catalog.ts`), the
 * Cyclic/Module assembly + imported schemas (`schema-imports.ts`), and the
 * public Static type bag (`schema-types.ts`). This module is a pure
 * re-export facade.
 * `$defs` key **insertion order** in the declarations bag is load-bearing for
 * the byte-stable `schema/v0.json` artifact.
 */
export {
  CATEGORICAL_SCHEME_NAMES,
  COLOR_SCHEME_NAMES,
  CYCLIC_SCHEME_NAMES,
  LINETYPE_NAMES,
  MAX_BINNED_BREAKS,
  MAX_GLOW_RADIUS,
  MAX_PAINT_STOPS,
  POINT_SHAPE_NAMES,
  SEQUENTIAL_SCHEME_NAMES,
  THEME_NAMES,
  THEME_NAME_ALIASES,
} from "./schema-names.js";
export type { LinetypeName, PointShapeName } from "./schema-names.js";

export {
  ALIAS_GEOMS,
  CHANNELS,
  CURRENT_EDITION,
  GEOM_ALIASES,
  GEOM_DEFAULTS,
  KNOWN_GEOMS,
  KNOWN_POSITIONS,
  KNOWN_STATS,
} from "./schema-catalog.js";
export type {
  AliasGeomName,
  ChannelName,
  GeomName,
  NormalizedGeomName,
  PositionName,
  StatName,
} from "./schema-catalog.js";

export {
  AesSchema,
  AblineLayerSchema,
  AreaLayerSchema,
  BarLayerSchema,
  Bin2dLayerSchema,
  BlankLayerSchema,
  BoxplotLayerSchema,
  ChannelValueSchema,
  ColLayerSchema,
  ContourLayerSchema,
  CoordFixedSpecSchema,
  CoordRadialSpecSchema,
  CoordSfSpecSchema,
  CoordSpecSchema,
  CoordTransformAxisSpecSchema,
  CoordTransformSpecSchema,
  CountLayerSchema,
  CrossbarLayerSchema,
  CurveLayerSchema,
  DataRefSchema,
  Density2dFilledLayerSchema,
  Density2dLayerSchema,
  DensityLayerSchema,
  DotplotLayerSchema,
  ErrorbarLayerSchema,
  FacetFieldRefSchema,
  FacetSpecSchema,
  FacetStripSpecSchema,
  FreqpolyLayerSchema,
  FunctionLayerSchema,
  HexLayerSchema,
  HistogramLayerSchema,
  HlineLayerSchema,
  JitterLayerSchema,
  LabelLayerSchema,
  LayerSpecSchema,
  LinerangeLayerSchema,
  LineLayerSchema,
  MapLayerSchema,
  PathLayerSchema,
  PlotSpecSchema,
  PointLayerSchema,
  PointrangeLayerSchema,
  PolygonLayerSchema,
  QuantileLayerSchema,
  QqLayerSchema,
  QqLineLayerSchema,
  RasterLayerSchema,
  RectLayerSchema,
  RibbonLayerSchema,
  RuleLayerSchema,
  RugLayerSchema,
  ScalesSchema,
  SegmentLayerSchema,
  SfLabelLayerSchema,
  SfLayerSchema,
  SfTextLayerSchema,
  SmoothLayerSchema,
  SpokeLayerSchema,
  StepLayerSchema,
  TemporalParserSpecSchemaRef,
  TextLayerSchema,
  TileLayerSchema,
  VlineLayerSchema,
  ViolinLayerSchema,
  SpecModule,
} from "./schema-imports.js";
export type { SpecImportSchema } from "./schema-imports.js";

export type {
  A11yMode,
  AblineLayer,
  AblineParams,
  Aes,
  AlphaScaleSpec,
  AreaLayer,
  AreaParams,
  AxisGuideSpec,
  BandAxisGuideSpec,
  BarLayer,
  BarParams,
  Bin2dLayer,
  Bin2dParams,
  BlankLayer,
  BlankParams,
  BoxplotLayer,
  BoxplotParams,
  CellValue,
  ChannelValue,
  ColorScaleSpec,
  ColorStop,
  ColorbarGuideSpec,
  ColorstepsGuideSpec,
  ContourLayer,
  ContourParams,
  CoordFixedSpec,
  CoordRadialSpec,
  CoordSfSpec,
  CoordSpec,
  CoordTransformAxisSpec,
  CoordTransformSpec,
  CountLayer,
  CrossbarLayer,
  CrossbarParams,
  CurveLayer,
  CurveParams,
  DataColumns,
  DataName,
  DataRef,
  DataValues,
  Density2dFilledLayer,
  Density2dLayer,
  Density2dParams,
  DensityLayer,
  DensityParams,
  DotplotLayer,
  DotplotParams,
  ErrorbarLayer,
  ErrorbarParams,
  FacetFieldRef,
  FacetScales,
  FacetSpec,
  FacetStripSpec,
  FreqpolyLayer,
  FunctionArgs,
  FunctionLayer,
  FunctionParams,
  FunctionRegistryName,
  GlowSpec,
  GuideSpec,
  GuideThemeSpec,
  GuidesSpec,
  HexLayer,
  HexParams,
  HlineLayer,
  HlineParams,
  InlineData,
  JitterLayer,
  LabelLayer,
  LabelParams,
  Labs,
  LayerSpec,
  LegendGuideSpec,
  LegendSpec,
  LinerangeLayer,
  LinerangeParams,
  LineLayer,
  LineParams,
  LinetypeScaleSpec,
  LinearGradientPaint,
  MapLayer,
  MapParams,
  NoneGuideSpec,
  NormalizedLayerSpec,
  NormalizedSpec,
  PaintSpace,
  PointLayer,
  PathLayer,
  ColLayer,
  HistogramLayer,
  PathParams,
  ColParams,
  PointParams,
  PointPosition,
  PointrangeLayer,
  PointrangeParams,
  PolygonLayer,
  PolygonParams,
  PortableSpec,
  PositionParams,
  PositionScaleSpec,
  PositiveStyleScaleSpec,
  QuantileLayer,
  QuantileParams,
  QqLayer,
  QqLineLayer,
  QqLineParams,
  QqParams,
  RadialGradientPaint,
  GradientPaint,
  RasterLayer,
  RasterParams,
  RectLayer,
  RectParams,
  RenderBackend,
  RibbonLayer,
  RibbonParams,
  RuleLayer,
  RuleParams,
  RugLayer,
  RugParams,
  ScaleExpansion,
  Scales,
  SegmentLayer,
  SegmentParams,
  SfLabelLayer,
  SfLabelParams,
  SfLayer,
  SfParams,
  SfTextLayer,
  SfTextParams,
  ShapeScaleSpec,
  SmoothLayer,
  SmoothParams,
  SpokeLayer,
  SpokeParams,
  StackablePosition,
  StepLayer,
  StepParams,
  SummaryFun,
  TemporalParserSpec,
  TextLayer,
  TextParams,
  ThemeName,
  ThemeSpec,
  TileLayer,
  TileParams,
  VlineLayer,
  VlineParams,
  ViolinLayer,
  ViolinParams,
} from "./schema-types.js";
