/**
 * Tier-2 data-aware walk — field existence, all-null columns, {stat} columns,
 * geom/stat type rules, and scale/type compatibility. Consumes a FieldEvidenceMap
 * built by validate-data-evidence.ts (or builds one when not pre-resolved).
 */
import type { SpecError } from "./errors.js";
import { didYouMean } from "./errors.js";
import type { Aes, ChannelName, ColorScaleSpec, PositionScaleSpec } from "./schema.js";
import { CHANNELS, GEOM_DEFAULTS, SEQUENTIAL_SCHEME_NAMES } from "./schema.js";
import type { ProfileFieldType, ValidateLimits, ValidateOptions } from "./validate-data.js";
import { parseTemporalColumn, temporalParserConfigurationError } from "./temporal.js";
import {
  parseTemporalInterval,
  temporalLabelConfigurationError,
  temporalLocaleConfigurationError,
} from "./temporal-guides.js";
import {
  effectiveChannel,
  resolveFieldEvidence,
  type ResolveFieldEvidenceResult,
} from "./validate-data-evidence.js";

/** Columns generated by each stat ({ stat } channel resolution contract).
 *  Documented per stat in its @ggsvelte/core module header. */
export const STAT_COLUMNS: Record<string, readonly string[]> = {
  identity: [],
  count: ["count"],
  bin: ["count", "density", "ncount", "ndensity"],
  density: ["density", "count", "scaled", "ndensity"],
  smooth: ["y", "ymin", "ymax", "se"],
  boxplot: ["ymin", "lower", "middle", "upper", "ymax"],
  summary: ["y", "ymin", "ymax"],
};

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function appendTemporalKindMismatch(
  errors: SpecError[],
  input: {
    axis: "x" | "y";
    path: string;
    field: string;
    expected: "date" | "datetime" | undefined;
    actual: "date" | "datetime" | null;
  },
): void {
  const { axis, path, field, expected, actual } = input;
  if (expected === undefined || actual === null || actual === expected) return;
  errors.push({
    code: "scale-type-mismatch",
    path,
    message: `scales.${axis}.temporalKind is "${expected}" but field "${field}" parses as ${actual}.`,
    fix: {
      description: `Use temporalKind "${actual}" or choose a parser that produces ${expected} values.`,
    },
  });
}

const AXIS_CHANNELS = ["x", "y"] as const;
const COLOR_CHANNELS = ["color", "fill"] as const;
const SEQUENTIAL_SCHEMES = new Set<string>(SEQUENTIAL_SCHEME_NAMES);

export function dataChecks(
  spec: Record<string, unknown>,
  options: ValidateOptions,
  limits: ValidateLimits,
  /** Pre-resolved evidence from validate() so lint can share the same pass. */
  preResolved?: ResolveFieldEvidenceResult,
): SpecError[] {
  const errors: SpecError[] = [];
  const scales = isRecord(spec["scales"]) ? spec["scales"] : undefined;
  const scaleRequestsTime = (axis: "x" | "y"): boolean => {
    const config = scales?.[axis] as PositionScaleSpec | undefined;
    return (
      config?.type !== "band" &&
      (config?.type === "time" ||
        config?.parse !== undefined ||
        config?.temporalKind !== undefined ||
        config?.timezone !== undefined ||
        config?.disambiguation !== undefined ||
        config?.parseFailure !== undefined ||
        config?.dateBreaks !== undefined ||
        config?.dateMinorBreaks !== undefined ||
        config?.dateLabels !== undefined ||
        config?.locale !== undefined ||
        config?.weekStart !== undefined)
    );
  };
  const invalidTemporalAxes = new Set<"x" | "y">();
  for (const axis of AXIS_CHANNELS) {
    const config = scales?.[axis] as PositionScaleSpec | undefined;
    const hasGuideTemporalOption =
      config?.dateBreaks !== undefined ||
      config?.dateMinorBreaks !== undefined ||
      config?.dateLabels !== undefined ||
      config?.locale !== undefined ||
      config?.weekStart !== undefined;
    if (
      hasGuideTemporalOption &&
      (config?.type === "band" || config?.type === "linear" || config?.type === "log")
    ) {
      invalidTemporalAxes.add(axis);
      errors.push({
        code: "scale-type-mismatch",
        path: `/scales/${axis}`,
        message: `scales.${axis} uses temporal break or label options with explicit type "${config.type}".`,
        fix: {
          description:
            'Use type "time", a date/datetime scale helper, or remove the temporal option.',
        },
      });
      continue;
    }
    if (config?.type === "band" || !scaleRequestsTime(axis)) continue;
    let configurationError = temporalParserConfigurationError(config?.parse ?? "auto", {
      ...(config?.timezone !== undefined && { timezone: config.timezone }),
      ...(config?.disambiguation !== undefined && { disambiguation: config.disambiguation }),
    });
    if (configurationError === null) {
      for (const interval of [config?.dateBreaks, config?.dateMinorBreaks]) {
        if (interval === undefined) continue;
        try {
          parseTemporalInterval(interval);
        } catch (error) {
          configurationError = error instanceof Error ? error.message : "invalid temporal interval";
          break;
        }
      }
    }
    if (configurationError === null && config?.dateLabels !== undefined) {
      configurationError = temporalLabelConfigurationError(config.dateLabels);
    }
    if (configurationError === null && config?.locale !== undefined) {
      configurationError = temporalLocaleConfigurationError(config.locale);
    }
    if (configurationError === null) continue;
    invalidTemporalAxes.add(axis);
    errors.push({
      code: "scale-type-mismatch",
      path: `/scales/${axis}`,
      message: `scales.${axis} has invalid temporal configuration: ${configurationError}.`,
      fix: {
        description: "Correct the parser, interval, label, locale, or timezone configuration.",
      },
    });
  }

  const resolved = preResolved ?? resolveFieldEvidence(spec, options, limits);
  if (resolved.status === "errors") return [...errors, ...resolved.errors];
  if (resolved.status === "none") return errors; // value-dependent checks need data or a profile
  const fields = resolved.fields;

  const available = [...fields.keys()];
  const plotAes = isRecord(spec["aes"]) ? (spec["aes"] as Aes) : undefined;
  const layers = Array.isArray(spec["layers"]) ? (spec["layers"] as unknown[]) : [];
  const scaleRequestsTimeForChannel = (channel: ChannelName): boolean => {
    const axis =
      channel === "x"
        ? "x"
        : channel === "y" || channel === "ymin" || channel === "ymax"
          ? "y"
          : null;
    return axis !== null && scaleRequestsTime(axis);
  };

  interface AxisUse {
    field: string;
    path: string;
  }
  const axisFields: Record<"x" | "y", AxisUse[]> = { x: [], y: [] };
  const colorFields: Record<"color" | "fill", AxisUse[]> = { color: [], fill: [] };

  for (let i = 0; i < layers.length; i++) {
    const layer = layers[i];
    if (!isRecord(layer)) continue;
    const geom = typeof layer["geom"] === "string" ? layer["geom"] : "";
    const layerAes = isRecord(layer["aes"]) ? (layer["aes"] as Aes) : undefined;
    const defaultStat = GEOM_DEFAULTS[geom as keyof typeof GEOM_DEFAULTS]?.stat ?? "identity";
    const stat = typeof layer["stat"] === "string" ? layer["stat"] : defaultStat;

    // --- geom/stat field-type rules (M2 statistical layer) -----------------
    const fieldTypeOf = (channel: ChannelName): [string, ProfileFieldType] | null => {
      const m = effectiveChannel(plotAes, layerAes, channel);
      if (m === undefined || !("field" in m)) return null;
      const t = fields.get(m.field)?.type;
      if (t === undefined || t === null) return null;
      // Geom/stat contracts see position values after configured temporal parsing.
      // Parse failures and configuration errors are owned by scale validation below.
      return [m.field, scaleRequestsTimeForChannel(channel) ? "temporal" : t];
    };
    const typeError = (channel: ChannelName, message: string, fixDesc: string) => {
      errors.push({
        code: "channel-type-mismatch",
        path: `/layers/${i}/aes/${channel}`,
        message,
        fix: { description: fixDesc },
      });
    };
    if (geom === "smooth") {
      for (const channel of ["x", "y"] as const) {
        const info = fieldTypeOf(channel);
        if (info !== null && (info[1] === "nominal" || info[1] === "ordinal")) {
          typeError(
            channel,
            `The smooth stat needs quantitative x and y, but field "${info[0]}" (${channel}) is ${info[1]}.`,
            "Map the channel to a numeric field, or use a boxplot for discrete x.",
          );
        }
      }
    }
    if (geom === "boxplot") {
      const x = fieldTypeOf("x");
      if (x !== null && (x[1] === "quantitative" || x[1] === "temporal")) {
        typeError(
          "x",
          `The boxplot geom needs a DISCRETE x this milestone, but field "${x[0]}" is ${x[1]}.`,
          "Map x to a categorical field (strings), or bin the values into labeled categories first.",
        );
      }
      const y = fieldTypeOf("y");
      if (y !== null && (y[1] === "nominal" || y[1] === "ordinal")) {
        typeError(
          "y",
          `The boxplot stat needs a quantitative y, but field "${y[0]}" is ${y[1]}.`,
          "Map y to a numeric field.",
        );
      }
    }
    if (geom === "histogram" || geom === "density" || (geom === "bar" && stat === "bin")) {
      const x = fieldTypeOf("x");
      if (x !== null && (x[1] === "nominal" || x[1] === "ordinal")) {
        typeError(
          "x",
          `The ${geom === "density" ? "density" : "bin"} stat needs a continuous x, but field "${x[0]}" is ${x[1]}.`,
          'Use geom "bar" (the count stat) to count categories instead.',
        );
      }
    }
    if (geom === "errorbar") {
      for (const channel of ["ymin", "ymax"] as const) {
        const info = fieldTypeOf(channel);
        if (
          info !== null &&
          (info[1] === "nominal" || info[1] === "ordinal") &&
          !scaleRequestsTime("y")
        ) {
          typeError(
            channel,
            `The errorbar geom needs quantitative bounds, but field "${info[0]}" (${channel}) is ${info[1]}.`,
            "Map the channel to a numeric field.",
          );
        }
      }
    }

    for (const channel of CHANNELS) {
      const mapped = effectiveChannel(plotAes, layerAes, channel);
      if (mapped === undefined) continue;
      const path = `/layers/${i}/aes/${channel}`;

      if ("stat" in mapped) {
        const generated = STAT_COLUMNS[stat] ?? [];
        if (!generated.includes(mapped.stat)) {
          errors.push({
            code: "unknown-stat-column",
            path,
            message:
              generated.length === 0
                ? `Channel "${channel}" maps stat column "${mapped.stat}", but this layer's stat ("${stat}") generates no columns.`
                : `Channel "${channel}" maps stat column "${mapped.stat}", but this layer's stat ("${stat}") generates: ${generated.join(", ")}.`,
            ...(generated.length > 0 && { allowed: [...generated] }),
          });
        }
        continue;
      }
      if (!("field" in mapped)) continue;

      const info = fields.get(mapped.field);
      if (info === undefined) {
        const suggestion = didYouMean(mapped.field, available);
        errors.push({
          code: "unknown-field",
          path,
          message:
            `Unknown field "${mapped.field}" (available: ${available.join(", ") || "none"}).` +
            (suggestion === undefined ? "" : ` Did you mean "${suggestion}"?`),
          allowed: available,
          ...(suggestion !== undefined && {
            fix: {
              description: `Map "${channel}" to "${suggestion}".`,
              example: { field: suggestion },
            },
          }),
        });
        continue;
      }
      if (info.allNull) {
        errors.push({
          code: "all-null-column",
          path,
          message: `Field "${mapped.field}" contains only null values; the "${channel}" channel cannot be drawn from it.`,
        });
        continue;
      }
      if (channel === "x") axisFields.x.push({ field: mapped.field, path });
      if (channel === "y" || channel === "ymin" || channel === "ymax") {
        axisFields.y.push({ field: mapped.field, path });
      }
      if (channel === "color" || channel === "fill") {
        colorFields[channel].push({ field: mapped.field, path });
      }
    }
  }

  // --- scale/type compatibility ----------------------------------------------
  const typeOf = (field: string) => fields.get(field)?.type ?? null;

  for (const axis of AXIS_CHANNELS) {
    const config = scales?.[axis] as PositionScaleSpec | undefined;
    const declared =
      config?.type === "band" ? "band" : scaleRequestsTime(axis) ? "time" : config?.type;
    if (declared === undefined || declared === "band" || invalidTemporalAxes.has(axis)) continue;
    for (const use of axisFields[axis]) {
      const type = typeOf(use.field);
      if (type === null) continue;
      if (declared === "time") {
        const info = fields.get(use.field);
        const decision =
          info?.values === null || info?.values === undefined
            ? info?.temporal
            : parseTemporalColumn(info.values, config?.parse ?? "auto", {
                ...(config?.timezone !== undefined && { timezone: config.timezone }),
                ...(config?.disambiguation !== undefined && {
                  disambiguation: config.disambiguation,
                }),
              }).decision;
        const censoredInvalid =
          config?.parse !== undefined &&
          config.parseFailure === "censor" &&
          decision?.status === "invalid";
        const profileTemporal = info?.values === null && type === "temporal";
        if (decision?.status === "temporal" || censoredInvalid || profileTemporal) {
          appendTemporalKindMismatch(errors, {
            axis,
            path: use.path,
            field: use.field,
            expected: config?.temporalKind,
            actual: decision?.kind ?? null,
          });
          continue;
        }
        const firstFailure = decision?.failures?.[0];
        const detail =
          firstFailure === undefined
            ? decision?.status === "ambiguous"
              ? ` Automatic temporal inference was ambiguous between: ${decision.candidates.join(", ")}.`
              : decision?.status === "invalid"
                ? ` Automatic temporal inference failed whole-column validation for ${decision.failedCount} value(s).`
                : ""
            : ` Parser ${JSON.stringify(config?.parse ?? "auto")} rejected ${decision?.failedCount ?? 0} value(s), including row ${firstFailure.index}: ${JSON.stringify(firstFailure.value)}.`;
        errors.push({
          code: "scale-type-mismatch",
          path: use.path,
          message: `scales.${axis} requests time but field "${use.field}" is ${type}.${detail}`,
          fix: {
            description:
              config?.parse === undefined
                ? `Set scales.${axis}.parse to an explicit temporal order, or set scales.${axis}.type to "band" to keep categories.`
                : `Correct the rejected values, choose the matching scales.${axis}.parse value, or use parseFailure: "censor" explicitly.`,
          },
        });
        continue;
      }
      if (
        (declared === "log" || declared === "linear") &&
        (type === "nominal" || type === "ordinal")
      ) {
        errors.push({
          code: "scale-type-mismatch",
          path: use.path,
          message: `scales.${axis}.type is "${declared}" but field "${use.field}" is ${type}; use a band scale (or a quantitative field).`,
          fix: { description: `Set scales.${axis}.type to "band".` },
        });
      }
    }
  }

  for (const channel of COLOR_CHANNELS) {
    const config = scales?.[channel] as ColorScaleSpec | undefined;
    const inferredFromSequentialScheme =
      config?.type === undefined &&
      config?.range === undefined &&
      config?.scheme !== undefined &&
      SEQUENTIAL_SCHEMES.has(config.scheme);
    const effectiveType = config?.type ?? (inferredFromSequentialScheme ? "sequential" : undefined);
    if (effectiveType !== "sequential" && effectiveType !== "binned") continue;
    for (const use of colorFields[channel]) {
      const type = typeOf(use.field);
      if (type !== "nominal" && type !== "ordinal") continue;

      const requestsTemporal =
        config?.temporalKind !== undefined ||
        config?.parse !== undefined ||
        config?.timezone !== undefined ||
        config?.disambiguation !== undefined;
      if (!requestsTemporal) {
        errors.push({
          code: "scale-type-mismatch",
          path: use.path,
          message: inferredFromSequentialScheme
            ? `scales.${channel}.scheme is "${config.scheme}" and selects a sequential scale, but field "${use.field}" is ${type}; sequential color ramps need quantitative values.`
            : `scales.${channel}.type is "${effectiveType}" but field "${use.field}" is ${type}; quantitative color scales need quantitative or temporal values.`,
          fix: inferredFromSequentialScheme
            ? {
                description: `Set scales.${channel}.scheme to a categorical scheme, remove it to infer an ordinal scale from "${use.field}", or map a quantitative field.`,
                example: { scheme: "observable10" },
              }
            : { description: `Set scales.${channel}.type to "ordinal".` },
        });
        continue;
      }

      const info = fields.get(use.field);
      const decision =
        info?.values === null || info?.values === undefined
          ? info?.temporal
          : parseTemporalColumn(info.values, config?.parse ?? "auto", {
              ...(config?.timezone !== undefined && { timezone: config.timezone }),
              ...(config?.disambiguation !== undefined && {
                disambiguation: config.disambiguation,
              }),
            }).decision;
      const censoredInvalid =
        config?.parse !== undefined &&
        config.parseFailure === "censor" &&
        decision?.status === "invalid";
      if (decision?.status === "temporal" || censoredInvalid) {
        if (
          decision?.status === "temporal" &&
          config?.temporalKind !== undefined &&
          decision.kind !== config.temporalKind
        ) {
          errors.push({
            code: "scale-type-mismatch",
            path: use.path,
            message: `scales.${channel} requests temporal kind "${config.temporalKind}" but field "${use.field}" parses as "${decision.kind}".`,
            fix: {
              description: `Use the ${decision.kind ?? "matching"} color helper or correct the source precision.`,
            },
          });
        }
        continue;
      }

      const detail =
        decision?.status === "ambiguous"
          ? ` Automatic temporal inference was ambiguous between: ${decision.candidates.join(", ")}.`
          : decision?.status === "invalid"
            ? ` Temporal parsing rejected ${String(decision.failedCount)} value(s).`
            : "";
      errors.push({
        code: "scale-type-mismatch",
        path: use.path,
        message: `scales.${channel} requests temporal colors but field "${use.field}" is ${type}.${detail}`,
        fix: {
          description:
            config?.parse === undefined
              ? `Set scales.${channel}.parse to the exact temporal order, or use type: "ordinal".`
              : `Correct the rejected values, choose the matching parser, or set parseFailure: "censor" explicitly.`,
        },
      });
    }
  }

  return errors;
}
