/**
 * Tier-2 data-aware walk — field existence, all-null columns, {stat} columns,
 * geom/stat type rules, then scale/type compatibility.
 *
 * Implementation:
 *  - validate-data-checks-temporal.ts — shared temporalDecisionForField memoization
 *  - validate-data-checks-position.ts — pre-evidence temporal axis config + x/y scale types
 *  - validate-data-checks-color.ts — color/fill scale types + manual domain/range
 *
 * Consumes a FieldEvidenceMap built by validate-data-evidence.ts (or builds one
 * when not pre-resolved).
 */
import type { SpecError } from "./errors.js";
import { didYouMean } from "./errors.js";
import type { Aes, ChannelName } from "./schema.js";
import { CHANNELS, GEOM_DEFAULTS } from "./schema.js";
import type { ProfileFieldType, ValidateLimits, ValidateOptions } from "./validate-data.js";
import type { TemporalDecision } from "./temporal-column.js";
import {
  effectiveChannel,
  resolveFieldEvidence,
  type ResolveFieldEvidenceResult,
} from "./validate-data-evidence.js";
import { checkColorScaleDataCompatibility } from "./validate-data-checks-color.js";
import {
  checkPositionScaleDataCompatibility,
  scaleRequestsTime,
  validateTemporalAxisConfiguration,
} from "./validate-data-checks-position.js";
import { temporalDecisionForField, type ChannelFieldUse } from "./validate-data-checks-temporal.js";

/** Columns generated by each stat ({ stat } channel resolution contract).
 *  Documented per stat in its @ggsvelte/core module header. */
export const STAT_COLUMNS: Record<string, readonly string[]> = {
  identity: [],
  count: ["count"],
  bin: ["count", "density", "ncount", "ndensity"],
  density: ["density", "count", "scaled", "ndensity"],
  smooth: ["y", "ymin", "ymax", "se"],
  boxplot: ["ymin", "lower", "middle", "upper", "ymax"],
  summary: ["y", "ymin", "ymax"],
};

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

export function dataChecks(
  spec: Record<string, unknown>,
  options: ValidateOptions,
  limits: ValidateLimits,
  /** Pre-resolved evidence from validate() so lint can share the same pass. */
  preResolved?: ResolveFieldEvidenceResult,
): SpecError[] {
  const errors: SpecError[] = [];
  // One cache per dataChecks call — shared by position and color checkers.
  const temporalDecisionCache = new Map<string, TemporalDecision | null | undefined>();
  const scales = isRecord(spec["scales"]) ? spec["scales"] : undefined;

  // Pre-evidence: temporal axis configuration (errors even without data/profile).
  const temporalConfig = validateTemporalAxisConfiguration(scales);
  errors.push(...temporalConfig.errors);
  const { invalidTemporalAxes } = temporalConfig;

  const resolved = preResolved ?? resolveFieldEvidence(spec, options, limits);
  if (resolved.status === "errors") return [...errors, ...resolved.errors];
  if (resolved.status === "none") return errors; // value-dependent checks need data or a profile
  const fields = resolved.fields;

  const available = [...fields.keys()];
  const plotAes = isRecord(spec["aes"]) ? (spec["aes"] as Aes) : undefined;
  const layers = Array.isArray(spec["layers"]) ? (spec["layers"] as unknown[]) : [];
  const scaleRequestsTimeForChannel = (channel: ChannelName): boolean => {
    const axis =
      channel === "x"
        ? "x"
        : channel === "y" || channel === "ymin" || channel === "ymax"
          ? "y"
          : null;
    return axis !== null && scaleRequestsTime(scales, axis);
  };

  const axisFields: Record<"x" | "y", ChannelFieldUse[]> = { x: [], y: [] };
  const colorFields: Record<"color" | "fill", ChannelFieldUse[]> = { color: [], fill: [] };
  const colorScaledConstants: Record<"color" | "fill", unknown[]> = { color: [], fill: [] };
  const finiteStyleFields: Record<"shape" | "linetype", ChannelFieldUse[]> = {
    shape: [],
    linetype: [],
  };
  const numericStyleFields: Record<"size" | "linewidth" | "alpha", ChannelFieldUse[]> = {
    size: [],
    linewidth: [],
    alpha: [],
  };
  const numericStyleScaledConstants: Record<"size" | "linewidth" | "alpha", unknown[]> = {
    size: [],
    linewidth: [],
    alpha: [],
  };

  for (let i = 0; i < layers.length; i++) {
    const layer = layers[i];
    if (!isRecord(layer)) continue;
    const geom = typeof layer["geom"] === "string" ? layer["geom"] : "";
    const layerAes = isRecord(layer["aes"]) ? (layer["aes"] as Aes) : undefined;
    const defaultStat = GEOM_DEFAULTS[geom as keyof typeof GEOM_DEFAULTS]?.stat ?? "identity";
    const stat = typeof layer["stat"] === "string" ? layer["stat"] : defaultStat;

    // --- geom/stat field-type rules (M2 statistical layer) -----------------
    const fieldTypeOf = (channel: ChannelName): [string, ProfileFieldType] | null => {
      const m = effectiveChannel(plotAes, layerAes, channel);
      if (m === undefined || !("field" in m)) return null;
      const t = fields.get(m.field)?.type;
      if (t === undefined || t === null) return null;
      // Geom/stat contracts see position values after configured temporal parsing.
      // Parse failures and configuration errors are owned by scale validation below.
      return [m.field, scaleRequestsTimeForChannel(channel) ? "temporal" : t];
    };
    const typeError = (channel: ChannelName, message: string, fixDesc: string) => {
      errors.push({
        code: "channel-type-mismatch",
        path: `/layers/${i}/aes/${channel}`,
        message,
        fix: { description: fixDesc },
      });
    };
    if (geom === "smooth") {
      for (const channel of ["x", "y"] as const) {
        const info = fieldTypeOf(channel);
        if (info !== null && (info[1] === "nominal" || info[1] === "ordinal")) {
          typeError(
            channel,
            `The smooth stat needs quantitative x and y, but field "${info[0]}" (${channel}) is ${info[1]}.`,
            "Map the channel to a numeric field, or use a boxplot for discrete x.",
          );
        }
      }
    }
    if (geom === "boxplot") {
      const x = fieldTypeOf("x");
      if (x !== null && (x[1] === "quantitative" || x[1] === "temporal")) {
        typeError(
          "x",
          `The boxplot geom needs a DISCRETE x this milestone, but field "${x[0]}" is ${x[1]}.`,
          "Map x to a categorical field (strings), or bin the values into labeled categories first.",
        );
      }
      const y = fieldTypeOf("y");
      if (y !== null && (y[1] === "nominal" || y[1] === "ordinal")) {
        typeError(
          "y",
          `The boxplot stat needs a quantitative y, but field "${y[0]}" is ${y[1]}.`,
          "Map y to a numeric field.",
        );
      }
    }
    if (geom === "histogram" || geom === "density" || (geom === "bar" && stat === "bin")) {
      const x = fieldTypeOf("x");
      if (x !== null && (x[1] === "nominal" || x[1] === "ordinal")) {
        typeError(
          "x",
          `The ${geom === "density" ? "density" : "bin"} stat needs a continuous x, but field "${x[0]}" is ${x[1]}.`,
          'Use geom "bar" (the count stat) to count categories instead.',
        );
      }
    }
    if (geom === "errorbar") {
      for (const channel of ["ymin", "ymax"] as const) {
        const info = fieldTypeOf(channel);
        if (
          info !== null &&
          (info[1] === "nominal" || info[1] === "ordinal") &&
          !scaleRequestsTime(scales, "y")
        ) {
          typeError(
            channel,
            `The errorbar geom needs quantitative bounds, but field "${info[0]}" (${channel}) is ${info[1]}.`,
            "Map the channel to a numeric field.",
          );
        }
      }
    }

    for (const channel of CHANNELS) {
      const mapped = effectiveChannel(plotAes, layerAes, channel);
      if (mapped === undefined) continue;
      const path = `/layers/${i}/aes/${channel}`;

      if ("stat" in mapped) {
        const generated = STAT_COLUMNS[stat] ?? [];
        if (!generated.includes(mapped.stat)) {
          errors.push({
            code: "unknown-stat-column",
            path,
            message:
              generated.length === 0
                ? `Channel "${channel}" maps stat column "${mapped.stat}", but this layer's stat ("${stat}") generates no columns.`
                : `Channel "${channel}" maps stat column "${mapped.stat}", but this layer's stat ("${stat}") generates: ${generated.join(", ")}.`,
            ...(generated.length > 0 && { allowed: [...generated] }),
          });
        }
        continue;
      }
      if ("value" in mapped) {
        // Runtime trains manual/ordinal color domains on scaled constants too.
        if (
          (channel === "color" || channel === "fill") &&
          mapped.scale === true &&
          mapped.value !== null
        ) {
          colorScaledConstants[channel].push(mapped.value);
        }
        // The runtime trains numeric style scales on scaled constants as well, so
        // a scaled string constant on a sequential/binned size/linewidth/alpha
        // scale must face the same scale-family check as a mapped field below.
        if (
          (channel === "size" || channel === "linewidth" || channel === "alpha") &&
          mapped.scale === true &&
          mapped.value !== null
        ) {
          numericStyleScaledConstants[channel].push(mapped.value);
        }
        continue;
      }
      if (!("field" in mapped)) continue;

      const info = fields.get(mapped.field);
      if (info === undefined) {
        const suggestion = didYouMean(mapped.field, available);
        errors.push({
          code: "unknown-field",
          path,
          message:
            `Unknown field "${mapped.field}" (available: ${available.join(", ") || "none"}).` +
            (suggestion === undefined ? "" : ` Did you mean "${suggestion}"?`),
          allowed: available,
          ...(suggestion !== undefined && {
            fix: {
              description: `Map "${channel}" to "${suggestion}".`,
              example: { field: suggestion },
            },
          }),
        });
        continue;
      }
      if (info.allNull) {
        errors.push({
          code: "all-null-column",
          path,
          message: `Field "${mapped.field}" contains only null values; the "${channel}" channel cannot be drawn from it.`,
        });
        continue;
      }
      if (channel === "x") axisFields.x.push({ field: mapped.field, path });
      if (channel === "y" || channel === "ymin" || channel === "ymax") {
        axisFields.y.push({ field: mapped.field, path });
      }
      if (channel === "color" || channel === "fill") {
        colorFields[channel].push({ field: mapped.field, path });
      }
      if (channel === "shape" || channel === "linetype") {
        finiteStyleFields[channel].push({ field: mapped.field, path });
      }
      if (channel === "size" || channel === "linewidth" || channel === "alpha") {
        numericStyleFields[channel].push({ field: mapped.field, path });
      }
    }
  }

  // --- scale/type compatibility (order preserved for diagnostics) ------------
  const typeOf = (field: string) => fields.get(field)?.type ?? null;
  for (const aesthetic of ["shape", "linetype"] as const) {
    const config = scales?.[aesthetic] as { type?: string } | undefined;
    if (config?.type !== undefined) continue;
    for (const use of finiteStyleFields[aesthetic]) {
      const type = typeOf(use.field);
      if (type !== "quantitative" && type !== "temporal") continue;
      // A binned finite style requires numeric values: the runtime rejects
      // temporal (date/datetime) values with `unsupported-aesthetic-scale`
      // ("cannot be mapped to named symbols", scale-style.ts). So only
      // quantitative fields may be directed to "binned"; temporal fields must
      // use "ordinal", which keys arbitrary values (Dates included) to symbols.
      const isTemporal = type === "temporal";
      errors.push({
        code: "scale-type-mismatch",
        path: `/scales/${aesthetic}`,
        message: `Field "${use.field}" is ${type}, but ${aesthetic} has finite symbols and cannot infer continuous interpolation.`,
        fix: {
          description: isTemporal
            ? `Set scales.${aesthetic}.type to "ordinal"; temporal (date/datetime) values cannot be binned onto named symbols.`
            : `Set scales.${aesthetic}.type to "binned", or explicitly choose "ordinal" for identifier-like values.`,
          example: { type: isTemporal ? "ordinal" : "binned" },
        },
      });
    }
  }

  // Numeric style scales (size/linewidth/alpha) mirror the sequential/binned
  // color check: a continuous ramp needs quantitative or temporal values, so a
  // nominal/ordinal field trains no finite domain and the runtime throws
  // `style-domain-empty` (scale-style.ts). Reject it at validation time with the
  // same "use ordinal" guidance color scales give. Fields without an explicit
  // sequential/binned type default to an ordinal numeric style and are fine.
  for (const aesthetic of ["size", "linewidth", "alpha"] as const) {
    const config = scales?.[aesthetic] as
      | {
          type?: string;
          temporalKind?: unknown;
          parse?: unknown;
          timezone?: unknown;
          disambiguation?: unknown;
          domain?: unknown;
          parseFailure?: unknown;
        }
      | undefined;
    if (config?.type !== "sequential" && config?.type !== "binned") continue;
    const requestsTemporal =
      config.temporalKind !== undefined ||
      config.parse !== undefined ||
      config.timezone !== undefined ||
      config.disambiguation !== undefined;
    for (const use of numericStyleFields[aesthetic]) {
      const type = typeOf(use.field);
      // A quantitative field carrying temporal options fails at resolve time
      // unless a working parser (or censor recovery) yields temporal values —
      // mirror the color checker rather than deferring unconditionally.
      if (type === "quantitative" && requestsTemporal) {
        const decision = temporalDecisionForField(
          temporalDecisionCache,
          use.field,
          fields.get(use.field),
          (config.parse ?? "auto") as Parameters<typeof temporalDecisionForField>[3],
          {
            ...(config.timezone !== undefined && { timezone: config.timezone }),
            ...(config.disambiguation !== undefined && {
              disambiguation: config.disambiguation,
            }),
          } as Parameters<typeof temporalDecisionForField>[4],
        );
        const hasExplicitDomain =
          Array.isArray(config.domain) &&
          config.domain.filter((value) => value !== null).length === 2;
        const censoredInvalid =
          config.parse !== undefined &&
          config.parseFailure === "censor" &&
          decision?.status === "invalid" &&
          ((decision.validatedCount ?? 0) > 0 || hasExplicitDomain);
        if (decision?.status !== "temporal" && !censoredInvalid) {
          errors.push({
            code: "scale-type-mismatch",
            path: `/scales/${aesthetic}`,
            message: `scales.${aesthetic} requests temporal values but field "${use.field}" is quantitative (numbers are not treated as temporal without a successful epoch parse).`,
            fix: {
              description: `Map a temporal field, use a working parse: { epoch: "ms" | "s" }, or remove temporal ${aesthetic} options.`,
            },
          });
          continue;
        }
        if (
          config.temporalKind !== undefined &&
          decision?.kind !== null &&
          decision?.kind !== undefined &&
          decision.kind !== config.temporalKind
        ) {
          errors.push({
            code: "scale-type-mismatch",
            path: `/scales/${aesthetic}`,
            message: `scales.${aesthetic} requests temporal kind "${String(config.temporalKind)}" but field "${use.field}" parses as "${decision.kind}".`,
            fix: {
              description: `Use the ${decision.kind ?? "matching"} ${aesthetic} helper or correct the source precision.`,
            },
          });
          continue;
        }
      }
      // A nominal/ordinal field trains no finite domain and the runtime throws
      // `style-domain-empty`; reject it with the same "use ordinal" guidance color
      // scales give. A nominal field carrying temporal options may still resolve
      // to temporal at runtime, so defer (mirror the color checker).
      if (type !== "nominal" && type !== "ordinal") continue;
      if (requestsTemporal) continue;
      errors.push({
        code: "scale-type-mismatch",
        path: `/scales/${aesthetic}`,
        message: `scales.${aesthetic}.type is "${config.type}" but field "${use.field}" is ${type}; ${config.type} ${aesthetic} scales need quantitative or temporal values.`,
        fix: {
          description: `Set scales.${aesthetic}.type to "ordinal", or map a quantitative field.`,
          example: { type: "ordinal" },
        },
      });
    }
    // Scaled constants train the same numeric scale, so a non-numeric one (e.g.
    // { value: "large", scale: true }) throws `style-domain-empty` at runtime.
    // Reject it here too. Temporal-requesting configs defer to scale resolution.
    if (!requestsTemporal) {
      for (const value of numericStyleScaledConstants[aesthetic]) {
        if ((typeof value === "number" && Number.isFinite(value)) || value instanceof Date) {
          continue;
        }
        errors.push({
          code: "scale-type-mismatch",
          path: `/scales/${aesthetic}`,
          message: `scales.${aesthetic}.type is "${config.type}" but the scaled constant ${JSON.stringify(value)} is not numeric; ${config.type} ${aesthetic} scales need quantitative or temporal values.`,
          fix: {
            description: `Use a numeric scaled constant, or set scales.${aesthetic}.type to "ordinal".`,
            example: { type: "ordinal" },
          },
        });
      }
    }
  }

  errors.push(
    ...checkPositionScaleDataCompatibility({
      scales,
      fields,
      axisFields,
      invalidTemporalAxes,
      temporalDecisionCache,
    }),
    ...checkColorScaleDataCompatibility({
      scales,
      fields,
      colorFields,
      colorScaledConstants,
      temporalDecisionCache,
    }),
  );

  return errors;
}
