/**
 * gen-reference-catalogs — precompute schema-derived API catalogs so docs SSR
 * and createGeomLayer never load SpecDeclarations / TypeBox.
 *
 * Usage:
 *   bun run reference:catalogs:gen           # rewrite generated/*.ts
 *   bun run reference:catalogs:check         # exit 1 on drift
 */
import { join } from "node:path";

import { buildGeomParamKeys } from "../packages/spec/src/geom-params-build.ts";
import { buildGeomReference } from "../packages/spec/src/geom-reference-build.ts";
import { buildGuideReference } from "../packages/spec/src/guide-reference-build.ts";
import { buildPositionReference } from "../packages/spec/src/position-reference-build.ts";
import { buildScaleReference } from "../packages/spec/src/scale-reference-build.ts";
import { buildStatReference } from "../packages/spec/src/stat-reference-build.ts";

import { defineArtifact, defineArtifactGroup, formatGeneratedSource } from "./artifact.ts";

export const GENERATED_DIR = "packages/spec/src/generated";

const CATALOGS = [
  {
    file: "geom-param-keys.ts",
    exportName: "GEOM_PARAM_KEYS_DATA",
    build: () => buildGeomParamKeys(),
    summary: "GEOM_PARAM_KEYS — param whitelist per geom (createGeomLayer).",
  },
  {
    file: "geom-reference-data.ts",
    exportName: "GEOM_REFERENCE_DATA",
    build: () => buildGeomReference(),
    summary: "GEOM_REFERENCE — per-geom API docs from SpecDeclarations.",
  },
  {
    file: "scale-reference-data.ts",
    exportName: "SCALE_REFERENCE_DATA",
    build: () => buildScaleReference(),
    summary: "SCALE_REFERENCE — per-scale API docs from SpecDeclarations.",
  },
  {
    file: "stat-reference-data.ts",
    exportName: "STAT_REFERENCE_DATA",
    build: () => buildStatReference(),
    summary: "STAT_REFERENCE — per-stat API docs.",
  },
  {
    file: "position-reference-data.ts",
    exportName: "POSITION_REFERENCE_DATA",
    build: () => buildPositionReference(),
    summary: "POSITION_REFERENCE — per-position API docs.",
  },
  {
    file: "guide-reference-data.ts",
    exportName: "GUIDE_REFERENCE_DATA",
    build: () => buildGuideReference(),
    summary: "GUIDE_REFERENCE — per-guide API docs.",
  },
] as const;

function renderCatalogSource(opts: {
  file: string;
  exportName: string;
  summary: string;
  data: unknown;
}): string {
  const json = JSON.stringify(opts.data, null, 2);
  return `/**
 * AUTO-GENERATED by scripts/gen-reference-catalogs.ts — do not edit by hand.
 * Regenerate: bun run reference:catalogs:gen
 *
 * ${opts.summary}
 */
export const ${opts.exportName} = ${json} as const;
`;
}

export function referenceCatalogArtifacts(repoRoot: string) {
  const members = CATALOGS.map((catalog) => {
    const rel = `${GENERATED_DIR}/${catalog.file}`;
    return defineArtifact({
      path: join(repoRoot, rel),
      label: rel,
      regenerateWith: "reference:catalogs:gen",
      build: async () => {
        const raw = renderCatalogSource({
          file: catalog.file,
          exportName: catalog.exportName,
          summary: catalog.summary,
          data: catalog.build(),
        });
        return formatGeneratedSource(join(repoRoot, rel), raw);
      },
    });
  });
  return defineArtifactGroup({
    regenerateWith: "reference:catalogs:gen",
    members,
  });
}

if (import.meta.main) {
  const repoRoot = join(import.meta.dir, "..");
  await referenceCatalogArtifacts(repoRoot).cli();
}
