/**
 * gen-builder-geoms unit tests + staleness guard
 * (CI parity for `bun run builder:geoms:check`).
 */
import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { KNOWN_GEOMS } from "@ggsvelte/spec";

import {
  BUILDER_GEOMS_PATH,
  methodNameForGeom,
  optionsTypeForGeom,
  renderBuilderGeomsSource,
} from "./gen-builder-geoms.ts";

const repoRoot = join(import.meta.dir, "..");

describe("builder geom helper set", () => {
  it("names every KNOWN_GEOMS entry as geomPascal", () => {
    expect(methodNameForGeom("point")).toBe("geomPoint");
    expect(methodNameForGeom("bin_2d")).toBe("geomBin2d");
    expect(methodNameForGeom("density_2d_filled")).toBe("geomDensity2dFilled");
    expect(methodNameForGeom("qq_line")).toBe("geomQqLine");
    expect(optionsTypeForGeom("sf_text")).toBe("GeomSfTextOptions");
  });

  it("render emits every catalog method and jitter special assembly", () => {
    const src = renderBuilderGeomsSource();
    expect(src).toContain("AUTO-GENERATED by scripts/gen-builder-geoms.ts");
    expect(src).toContain("export function WithBuilderGeoms");
    for (const geom of KNOWN_GEOMS) {
      const method = methodNameForGeom(geom);
      expect(src.includes(`${method}(options:`), method).toBe(true);
      if (geom === "jitter") {
        expect(src).toContain("mergedPositionParams");
      } else {
        expect(src.includes(`layerFrom("${geom}", options)`), geom).toBe(true);
      }
    }
  });
});

describe("builder-geoms.ts staleness", () => {
  it("committed file matches render (regenerate with bun run builder:geoms:gen)", async () => {
    const { builderGeomsArtifact } = await import("./gen-builder-geoms.ts");
    await builderGeomsArtifact(repoRoot).check();
    const current = readFileSync(join(repoRoot, BUILDER_GEOMS_PATH), "utf8");
    expect(current.length).toBeGreaterThan(500);
  });
});
