import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";

import { format } from "oxfmt";

import { EXAMPLES, type ExampleManifestEntry } from "../examples/manifest.js";

const ROOT = resolve(import.meta.dir, "..");
// Gallery lights are owned by the published previews tree, not the VR smoke
// baseline dir (tests/visual/__screenshots__). Smoke may lag; previews may lag.
const DEFAULT_SOURCE = join(ROOT, "apps", "docs", "static", "previews");
const DEFAULT_OUTPUT = join(ROOT, "apps", "docs", "static", "previews");
const DEFAULT_PROJECTION = join(
  ROOT,
  "apps",
  "docs",
  "src",
  "lib",
  "generated",
  "gallery-previews.ts",
);

export interface PreviewInventoryEntry {
  id: string;
  filename: string;
}

export interface GenerateGalleryPreviewOptions {
  entries?: readonly ExampleManifestEntry[];
  source?: string;
  output?: string;
  projection?: string;
  check?: boolean;
}

export function canonicalPreviewFilename(id: string): string {
  return `${id.replaceAll("/", "-")}-light.png`;
}

export function previewSourceInventory(
  entries: readonly ExampleManifestEntry[],
): PreviewInventoryEntry[] {
  return entries.map((entry) => ({ id: entry.id, filename: canonicalPreviewFilename(entry.id) }));
}

function digest(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

async function projectionSource(
  inventory: readonly PreviewInventoryEntry[],
  source: string,
): Promise<string> {
  const records = inventory.map((entry) => {
    const path = join(source, entry.filename);
    if (!existsSync(path)) throw new Error(`Missing canonical gallery preview: ${entry.filename}`);
    return {
      id: entry.id,
      filename: entry.filename,
      path: `/previews/${entry.filename}`,
      sha256: digest(path),
    };
  });
  const raw = `// Generated by bun scripts/gen-gallery-previews.ts — do not edit.\n\nexport interface GalleryPreview {\n  readonly id: string;\n  readonly filename: string;\n  readonly path: string;\n  readonly sha256: string;\n}\n\nexport const GALLERY_PREVIEWS = ${JSON.stringify(records, null, 2)} as const satisfies readonly GalleryPreview[];\n`;
  const result = await format(DEFAULT_PROJECTION, raw);
  if (result.errors.length > 0) {
    throw new Error(
      `Could not format gallery preview projection: ${result.errors[0]?.message ?? "unknown error"}`,
    );
  }
  return result.code;
}

export async function generateGalleryPreviews(
  options: GenerateGalleryPreviewOptions = {},
): Promise<void> {
  const entries = options.entries ?? EXAMPLES;
  const source = options.source ?? DEFAULT_SOURCE;
  const output = options.output ?? DEFAULT_OUTPUT;
  const projection = options.projection ?? DEFAULT_PROJECTION;
  const inventory = previewSourceInventory(entries);
  const expected = new Set(inventory.map((entry) => entry.filename));
  const generated = await projectionSource(inventory, source);

  if (options.check === true) {
    if (!existsSync(projection) || readFileSync(projection, "utf8") !== generated) {
      throw new Error(
        "Generated gallery preview projection is stale. Run bun run gallery:previews:gen.",
      );
    }
    for (const entry of inventory) {
      const sourcePath = join(source, entry.filename);
      const outputPath = join(output, entry.filename);
      if (!existsSync(outputPath) || digest(sourcePath) !== digest(outputPath)) {
        throw new Error(`Generated gallery preview is stale: ${entry.filename}`);
      }
    }
    const extras = existsSync(output)
      ? readdirSync(output).filter(
          (filename) => filename.endsWith(".png") && !expected.has(filename),
        )
      : [];
    if (extras.length > 0) throw new Error(`Unexpected generated gallery preview: ${extras[0]}`);
    return;
  }

  mkdirSync(output, { recursive: true });
  mkdirSync(dirname(projection), { recursive: true });
  for (const filename of readdirSync(output)) {
    if (filename.endsWith(".png") && !expected.has(filename)) rmSync(join(output, filename));
  }
  for (const entry of inventory) {
    const from = join(source, entry.filename);
    const to = join(output, entry.filename);
    // Gallery inventory is self-owned when source === output (smoke baselines
    // no longer feed previews). Avoid no-op same-path copies.
    if (from !== to) copyFileSync(from, to);
  }
  writeFileSync(projection, generated);
}

if (import.meta.main) {
  await generateGalleryPreviews({ check: process.argv.includes("--check") });
  console.log(
    process.argv.includes("--check")
      ? "gallery previews are current"
      : "gallery previews generated",
  );
}
