import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";

import { format } from "oxfmt";

import { GUIDE_SECTIONS } from "../apps/docs/src/lib/catalog/guide.ts";
import lifecycle from "../lifecycle.json";
import { extractMarkdownHeadings, guidePages, type LifecycleDoc } from "./gen-llms.ts";
import {
  createDocsRouteInventory,
  type DocsRouteRecord,
  type RouteHeading,
} from "./docs-route-inventory.ts";

const OUTPUT_PATH = join(
  import.meta.dir,
  "..",
  "apps",
  "docs",
  "src",
  "lib",
  "generated",
  "routes.ts",
);

function withGuideHeadings(inventory: readonly DocsRouteRecord[]): DocsRouteRecord[] {
  const pages = new Map(
    guidePages(lifecycle as unknown as LifecycleDoc).map((page) => [page.slug, page]),
  );
  return inventory.map((route) => {
    if (!route.path.startsWith("/guide/")) return route;
    const page = pages.get(route.path.slice("/guide/".length));
    if (page === undefined) throw new Error(`No guide prose for route ${route.path}.`);
    const headings: RouteHeading[] = extractMarkdownHeadings(page.markdown)
      .filter((heading) => heading.level === 2 || heading.level === 3)
      .map(({ id, title, level }) => ({ id, title, level }));
    return { ...route, headings };
  });
}

function guideNavigation(routes: readonly DocsRouteRecord[]) {
  const groups = new Map<string, Array<{ path: string; label: string; order: number }>>();
  for (const route of routes) {
    if (route.navigation === undefined) continue;
    const entries = groups.get(route.navigation.section) ?? [];
    entries.push({
      path: route.path,
      label: route.navigation.label,
      order: route.navigation.order,
    });
    groups.set(route.navigation.section, entries);
  }
  return GUIDE_SECTIONS.filter((section) => groups.has(section)).map((section) => ({
    section,
    entries: groups
      .get(section)!
      .toSorted((a, b) => a.order - b.order)
      .map(({ path, label }) => ({ path, label })),
  }));
}

export async function generateDocsRouteProjection(
  inventory: readonly DocsRouteRecord[],
): Promise<string> {
  const routes = withGuideHeadings(inventory);
  const navigation = guideNavigation(routes);
  const source = `// Generated by bun scripts/gen-docs-routes.ts — do not edit.\nimport type { DocsRouteMetadata, GuideNavigationGroup } from "../route-types.js";\n\nexport const DOCS_ROUTES = ${JSON.stringify(routes, null, 2)} as const satisfies readonly DocsRouteMetadata[];\n\nexport const GUIDE_NAVIGATION = ${JSON.stringify(navigation, null, 2)} as const satisfies readonly GuideNavigationGroup[];\n`;
  const result = await format(OUTPUT_PATH, source);
  if (result.errors.length > 0) {
    throw new Error(
      `Could not format generated docs routes: ${result.errors[0]?.message ?? "unknown error"}`,
    );
  }
  return result.code;
}

export async function generateDocsRoutes(check = false): Promise<void> {
  const output = await generateDocsRouteProjection(createDocsRouteInventory());
  if (check) {
    const existing = readFileSync(OUTPUT_PATH, "utf8");
    if (existing !== output) {
      throw new Error("Generated docs routes are stale. Run `bun run docs:routes:gen`.");
    }
    console.log("docs route projection is current");
    return;
  }
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, output);
  console.log(`wrote ${OUTPUT_PATH}`);
}

if (import.meta.main || import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  await generateDocsRoutes(process.argv.includes("--check"));
}
