import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const repoRoot = join(import.meta.dir, "..");

describe("plot-spec-validator.ts staleness", () => {
  it(
    "committed file matches the TypeBox Code() emit (regenerate with bun run validator:gen)",
    async () => {
      const { plotSpecValidatorArtifact } = await import("./gen-plot-validator.ts");
      await plotSpecValidatorArtifact(repoRoot).check();
      const current = readFileSync(
        join(repoRoot, "packages/spec/src/generated/plot-spec-validator.ts"),
        "utf8",
      );
      expect(current).toContain("AUTO-GENERATED by scripts/gen-plot-validator.ts");
    },
    { timeout: 30_000 },
  );
});
