/**
 * gen-builder-scales — generates packages/spec/src/builder-scales.ts from
 * SCALE_CAPABILITIES (#1081 PR A).
 *
 * Every camelCase non-Colour helper on the ledger becomes a thin GGBuilder
 * method: `return this.scales(helper(...args))`. Style-channel ggplot2
 * ordinal aliases (Size/Alpha/Linewidth/Shape) are included even when only
 * the snake_case twin is listed on the ledger.
 *
 * Usage:
 *   bun scripts/gen-builder-scales.ts           # (re)write builder-scales.ts
 *   bun scripts/gen-builder-scales.ts --check   # exit 1 on drift without writing
 */
import { join } from "node:path";

import { SCALE_CAPABILITIES } from "@ggsvelte/spec";

import { defineArtifact, formatGeneratedSource } from "./artifact.ts";

export const BUILDER_SCALES_PATH = "packages/spec/src/builder-scales.ts";

/**
 * ggplot2-style ordinal aliases kept on the builder (binding-identical to the
 * corresponding discrete helper). Component shells re-export these names too
 * (#830/#832); the capability ledger lists only snake_case for some of them.
 */
export const STYLE_ORDINAL_BUILDER_HELPERS = [
  "scaleSizeOrdinal",
  "scaleAlphaOrdinal",
  "scaleLinewidthOrdinal",
  "scaleShapeOrdinal",
] as const;

/** CamelCase non-Colour helpers from SCALE_CAPABILITIES, sorted. */
export function ledgerCamelHelpers(): string[] {
  const out = new Set<string>();
  for (const cap of SCALE_CAPABILITIES) {
    for (const h of cap.helpers) {
      if (h.includes("_")) continue;
      if (h.includes("Colour")) continue;
      out.add(h);
    }
  }
  return [...out].toSorted();
}

/** Full set of helper names the builder mixin must wrap. */
export function builderScaleHelpers(): string[] {
  const out = new Set([...ledgerCamelHelpers(), ...STYLE_ORDINAL_BUILDER_HELPERS]);
  return [...out].toSorted();
}

export function renderBuilderScalesSource(helpers: readonly string[]): string {
  const importList = helpers.map((h) => `  ${h},`).join("\n");
  const methods = helpers
    .map(
      (h) => `
    ${h}(...args: Parameters<typeof ${h}>): GGBuilder {
      return this.scales(${h}(...args));
    }`,
    )
    .join("");

  return `/**
 * AUTO-GENERATED by scripts/gen-builder-scales.ts — do not edit by hand.
 * Regenerate: bun run builder:scales:gen
 *
 * Fluent builder scale sugar methods (thin wrappers over scale-helpers).
 * Source of truth: SCALE_CAPABILITIES camelCase helpers + style ordinal aliases.
 * Core builder: builder-core.ts. Public GGBuilder: builder.ts.
 */
import type { GGBuilder } from "./builder.js";
import {
${importList}
} from "./scale-helpers.js";
import type { Scales } from "./schema.js";

/** Host must expose scales() returning the public fluent builder type. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- mixin host constructor
type ScaleHostConstructor = new (...args: any[]) => {
  scales(scales: Scales): GGBuilder;
};

/**
 * Mixin that adds scaleX/Y/Color/Fill/style sugar methods.
 * Every method is annotated to return GGBuilder so fluent chains keep full typing.
 */
export function WithBuilderScales<TBase extends ScaleHostConstructor>(Base: TBase) {
  return class extends Base {${methods}
  };
}
`;
}

export function builderScalesArtifact(repoRoot: string) {
  return defineArtifact({
    path: join(repoRoot, BUILDER_SCALES_PATH),
    label: BUILDER_SCALES_PATH,
    regenerateWith: "builder:scales:gen",
    build: () => {
      const raw = renderBuilderScalesSource(builderScaleHelpers());
      return formatGeneratedSource(join(repoRoot, BUILDER_SCALES_PATH), raw);
    },
  });
}

if (import.meta.main) {
  const repoRoot = join(import.meta.dir, "..");
  await builderScalesArtifact(repoRoot).cli();
}
