/**
 * gen-builder-geoms — generates packages/spec/src/builder-geoms.ts from
 * KNOWN_GEOMS (#1081 PR C).
 *
 * Every catalog geom becomes a thin GGBuilder method wrapping layerFrom,
 * except geomJitter which folds flat width/height/seed into positionParams
 * (same contract as the hand-written predecessor).
 *
 * Usage:
 *   bun scripts/gen-builder-geoms.ts           # (re)write builder-geoms.ts
 *   bun scripts/gen-builder-geoms.ts --check   # exit 1 on drift without writing
 */
import { join } from "node:path";

import { KNOWN_GEOMS, type GeomName } from "@ggsvelte/spec";

import { defineArtifact, formatGeneratedSource } from "./artifact.ts";

export const BUILDER_GEOMS_PATH = "packages/spec/src/builder-geoms.ts";

/** Geoms whose options object is required (no empty default). */
export const REQUIRED_OPTIONS_GEOMS = new Set<GeomName>(["function", "map"]);

/** snake_case geom → geomPascal method name (mirrors gen-geom-children). */
export function methodNameForGeom(geom: string): string {
  const pascal = geom
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `geom${pascal}`;
}

/** snake_case geom → GeomPascalOptions type name. */
export function optionsTypeForGeom(geom: string): string {
  const pascal = geom
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `Geom${pascal}Options`;
}

export function renderBuilderGeomsSource(geoms: readonly GeomName[] = KNOWN_GEOMS): string {
  const optionTypes = [...geoms].map(optionsTypeForGeom).toSorted();
  const typeImports = optionTypes.map((t) => `  ${t},`).join("\n");

  const methods = geoms
    .map((geom) => {
      const method = methodNameForGeom(geom);
      const optionsType = optionsTypeForGeom(geom);
      if (geom === "jitter") {
        return `
    /**
     * Sugar for .layer({ geom: 'jitter', ... }) — points with position jitter
     * (ggplot2 geom_jitter; normalize() → point + position jitter). Flat
     * width/height/seed are assembled into positionParams here (not by normalize).
     */
    geomJitter(options: GeomJitterOptions = {}): GGBuilder {
      const { width, height, seed, positionParams, ...rest } = options;
      const mergedPositionParams = {
        ...positionParams,
        ...(width !== undefined && { width }),
        ...(height !== undefined && { height }),
        ...(seed !== undefined && { seed }),
      };
      const hasPositionParams = Object.keys(mergedPositionParams).length > 0;
      return this.layer(
        layerFrom("jitter", {
          ...rest,
          ...(hasPositionParams && { positionParams: mergedPositionParams }),
        }),
      );
    }`;
      }
      const defaultArg = REQUIRED_OPTIONS_GEOMS.has(geom) ? "" : " = {}";
      return `
    /** Sugar for .layer({ geom: '${geom}', ... }). */
    ${method}(options: ${optionsType}${defaultArg}): GGBuilder {
      return this.layer(layerFrom("${geom}", options));
    }`;
    })
    .join("");

  return `/**
 * AUTO-GENERATED by scripts/gen-builder-geoms.ts — do not edit by hand.
 * Regenerate: bun run builder:geoms:gen
 *
 * Fluent builder geom sugar methods (thin wrappers over layerFrom).
 * Source of truth: KNOWN_GEOMS. Core builder: builder-core.ts.
 * Public GGBuilder: builder.ts (WithBuilderScales(WithBuilderGeoms(Core))).
 */
import type { GGBuilder } from "./builder.js";
import type {
${typeImports}
} from "./builder-options.js";
import { layerFrom } from "./builder-core.js";
import type { LayerInput } from "./normalize.js";

/** Host must expose layer() returning the public fluent builder type. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- mixin host constructor
type GeomHostConstructor = new (...args: any[]) => {
  layer(layer: LayerInput): GGBuilder;
};

/**
 * Mixin that adds geom* sugar methods for every KNOWN_GEOMS entry.
 * Every method is annotated to return GGBuilder so fluent chains keep full typing.
 */
export function WithBuilderGeoms<TBase extends GeomHostConstructor>(Base: TBase) {
  return class extends Base {${methods}
  };
}
`;
}

export function builderGeomsArtifact(repoRoot: string) {
  return defineArtifact({
    path: join(repoRoot, BUILDER_GEOMS_PATH),
    label: BUILDER_GEOMS_PATH,
    regenerateWith: "builder:geoms:gen",
    build: () => {
      const raw = renderBuilderGeomsSource();
      return formatGeneratedSource(join(repoRoot, BUILDER_GEOMS_PATH), raw);
    },
  });
}

if (import.meta.main) {
  const repoRoot = join(import.meta.dir, "..");
  await builderGeomsArtifact(repoRoot).cli();
}
