import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";

import { EXAMPLES, type ExampleManifestEntry } from "../examples/manifest.js";
import {
  ArtifactError,
  defineArtifact,
  defineArtifactGroup,
  formatGeneratedSource,
} from "./artifact.ts";
import {
  assertPreviewProvenance,
  loadProvenance,
  provenancePath,
  pruneProvenanceToIds,
  writeProvenance,
} from "./gallery-preview-provenance.js";
import { manifestArtifact } from "./gen-manifest.ts";

const ROOT = resolve(import.meta.dir, "..");
// Gallery lights are owned by the published previews tree, not the VR smoke
// baseline dir (tests/visual/__screenshots__). Smoke may lag; previews may lag.
const DEFAULT_SOURCE = join(ROOT, "apps", "docs", "static", "previews");
const DEFAULT_OUTPUT = join(ROOT, "apps", "docs", "static", "previews");
const DEFAULT_PROJECTION = join(
  ROOT,
  "apps",
  "docs",
  "src",
  "lib",
  "generated",
  "gallery-previews.ts",
);
const DEFAULT_EXAMPLES_ROOT = join(ROOT, "examples");

export interface PreviewInventoryEntry {
  id: string;
  filename: string;
}

export interface GenerateGalleryPreviewOptions {
  entries?: readonly ExampleManifestEntry[];
  source?: string;
  output?: string;
  projection?: string;
  /** Root of the examples/ tree — used only for provenance source digests. */
  examplesRoot?: string;
  check?: boolean;
}

export function canonicalPreviewFilename(id: string): string {
  return `${id.replaceAll("/", "-")}-light.png`;
}

export function previewSourceInventory(
  entries: readonly ExampleManifestEntry[],
): PreviewInventoryEntry[] {
  return entries.map((entry) => ({ id: entry.id, filename: canonicalPreviewFilename(entry.id) }));
}

function digest(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

export async function projectionSource(
  inventory: readonly PreviewInventoryEntry[],
  source: string,
  formatPath: string = DEFAULT_PROJECTION,
): Promise<string> {
  const records = inventory.map((entry) => {
    const path = join(source, entry.filename);
    if (!existsSync(path)) throw new Error(`Missing canonical gallery preview: ${entry.filename}`);
    return {
      id: entry.id,
      filename: entry.filename,
      path: `/previews/${entry.filename}`,
      sha256: digest(path),
    };
  });
  const raw = `// Generated by bun scripts/gen-gallery-previews.ts — do not edit.\n\nexport interface GalleryPreview {\n  readonly id: string;\n  readonly filename: string;\n  readonly path: string;\n  readonly sha256: string;\n}\n\nexport const GALLERY_PREVIEWS = ${JSON.stringify(records, null, 2)} as const satisfies readonly GalleryPreview[];\n`;
  return await formatGeneratedSource(formatPath, raw);
}

function defaultGalleryGroup() {
  const entries = EXAMPLES;
  const source = DEFAULT_SOURCE;
  const output = DEFAULT_OUTPUT;
  const examplesRoot = DEFAULT_EXAMPLES_ROOT;
  const inventory = previewSourceInventory(entries);
  const expected = new Set(inventory.map((entry) => entry.filename));

  const projectionArtifact = defineArtifact({
    path: DEFAULT_PROJECTION,
    label: "apps/docs/src/lib/generated/gallery-previews.ts",
    regenerateWith: "gallery:previews:gen",
    dependsOn: [manifestArtifact],
    build: () => projectionSource(inventory, source, DEFAULT_PROJECTION),
  });

  return defineArtifactGroup({
    regenerateWith: "gallery:previews:gen",
    members: [projectionArtifact],
    extraCheck: () => {
      for (const entry of inventory) {
        const sourcePath = join(source, entry.filename);
        const outputPath = join(output, entry.filename);
        if (!existsSync(outputPath) || digest(sourcePath) !== digest(outputPath)) {
          throw new ArtifactError({
            status: existsSync(outputPath) ? "STALE" : "MISSING",
            path: outputPath,
            regenerateWith: "gallery:previews:gen",
            label: entry.filename,
          });
        }
      }
      const extras = existsSync(output)
        ? readdirSync(output).filter(
            (filename) => filename.endsWith(".png") && !expected.has(filename),
          )
        : [];
      if (extras.length > 0) {
        throw new ArtifactError({
          status: "STALE",
          path: join(output, extras[0]!),
          regenerateWith: "gallery:previews:gen",
          label: extras[0]!,
        });
      }
      assertPreviewProvenance({
        examplesRoot,
        previewsDir: output,
        entries,
        provenance: loadProvenance(provenancePath(output)),
      });
    },
    extraWrite: () => {
      mkdirSync(output, { recursive: true });
      for (const filename of readdirSync(output)) {
        if (filename.endsWith(".png") && !expected.has(filename)) rmSync(join(output, filename));
      }
      for (const entry of inventory) {
        const from = join(source, entry.filename);
        const to = join(output, entry.filename);
        if (from !== to) copyFileSync(from, to);
      }
      const provFile = provenancePath(output);
      if (existsSync(provFile)) {
        writeProvenance(
          provFile,
          pruneProvenanceToIds(loadProvenance(provFile), new Set(entries.map((entry) => entry.id))),
        );
      }
    },
  });
}

/** Default-path protocol group (projection + PNG/provenance extras). */
export const galleryPreviewsGroup = defaultGalleryGroup();

export async function generateGalleryPreviews(
  options: GenerateGalleryPreviewOptions = {},
): Promise<void> {
  const isDefault =
    options.entries === undefined &&
    options.source === undefined &&
    options.output === undefined &&
    options.projection === undefined &&
    options.examplesRoot === undefined;

  if (isDefault) {
    if (options.check === true) {
      await galleryPreviewsGroup.check();
      return;
    }
    await galleryPreviewsGroup.write();
    return;
  }

  // Custom paths for unit tests — same domain logic, outside the default handle.
  const entries = options.entries ?? EXAMPLES;
  const source = options.source ?? DEFAULT_SOURCE;
  const output = options.output ?? DEFAULT_OUTPUT;
  const projection = options.projection ?? DEFAULT_PROJECTION;
  const examplesRoot = options.examplesRoot ?? DEFAULT_EXAMPLES_ROOT;
  const inventory = previewSourceInventory(entries);
  const expected = new Set(inventory.map((entry) => entry.filename));
  const generated = await projectionSource(inventory, source, projection);

  if (options.check === true) {
    if (!existsSync(projection) || readFileSync(projection, "utf8") !== generated) {
      throw new Error(
        "Generated gallery preview projection is stale. Run bun run gallery:previews:gen.",
      );
    }
    for (const entry of inventory) {
      const sourcePath = join(source, entry.filename);
      const outputPath = join(output, entry.filename);
      if (!existsSync(outputPath) || digest(sourcePath) !== digest(outputPath)) {
        throw new Error(`Generated gallery preview is stale: ${entry.filename}`);
      }
    }
    const extras = existsSync(output)
      ? readdirSync(output).filter(
          (filename) => filename.endsWith(".png") && !expected.has(filename),
        )
      : [];
    if (extras.length > 0) throw new Error(`Unexpected generated gallery preview: ${extras[0]}`);
    assertPreviewProvenance({
      examplesRoot,
      previewsDir: output,
      entries,
      provenance: loadProvenance(provenancePath(output)),
    });
    return;
  }

  mkdirSync(output, { recursive: true });
  mkdirSync(dirname(projection), { recursive: true });
  for (const filename of readdirSync(output)) {
    if (filename.endsWith(".png") && !expected.has(filename)) rmSync(join(output, filename));
  }
  for (const entry of inventory) {
    const from = join(source, entry.filename);
    const to = join(output, entry.filename);
    if (from !== to) copyFileSync(from, to);
  }
  writeFileSync(projection, generated);
  const provFile = provenancePath(output);
  if (existsSync(provFile)) {
    writeProvenance(
      provFile,
      pruneProvenanceToIds(loadProvenance(provFile), new Set(entries.map((entry) => entry.id))),
    );
  }
}

if (import.meta.main) {
  await galleryPreviewsGroup.cli();
}
