import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { GUIDE_SECTIONS } from "../apps/docs/src/lib/catalog/guide.ts";
import lifecycle from "../lifecycle.json";
import { defineArtifact, defineArtifactGroup, formatGeneratedSource } from "./artifact.ts";
import {
  createDocsRouteInventory,
  type DocsRouteRecord,
  type RouteHeading,
} from "./docs-route-inventory.ts";
import { lifecycleArtifact } from "./gen-lifecycle.ts";
import { extractMarkdownHeadings, guidePages, type LifecycleDoc } from "./gen-llms.ts";
import { GETTING_STARTED_PAGE_HEADINGS } from "./quickstart.ts";

const GENERATED_DIR = join(import.meta.dir, "..", "apps", "docs", "src", "lib", "generated");
const ROUTES_OUTPUT_PATH = join(GENERATED_DIR, "routes.ts");
const GUIDE_NAV_OUTPUT_PATH = join(GENERATED_DIR, "guide-navigation.ts");

function withGuideHeadings(inventory: readonly DocsRouteRecord[]): DocsRouteRecord[] {
  const pages = new Map(
    guidePages(lifecycle as unknown as LifecycleDoc).map((page) => [page.slug, page]),
  );
  return inventory.map((route) => {
    if (!route.path.startsWith("/guide/")) return route;
    // The human getting-started page is a component, not guide markdown: the
    // markdown at that slug is the agent doc served from /llms.txt. Its
    // on-this-page nav comes from the lesson catalog instead.
    if (route.path === "/guide/getting-started") {
      return { ...route, headings: GETTING_STARTED_PAGE_HEADINGS.map((h) => ({ ...h })) };
    }
    const page = pages.get(route.path.slice("/guide/".length));
    if (page === undefined) throw new Error(`No guide prose for route ${route.path}.`);
    const headings: RouteHeading[] = extractMarkdownHeadings(page.markdown)
      .filter((heading) => heading.level === 2 || heading.level === 3)
      .map(({ id, title, level }) => ({ id, title, level }));
    return { ...route, headings };
  });
}

function guideNavigation(routes: readonly DocsRouteRecord[]) {
  const groups = new Map<string, Array<{ path: string; label: string; order: number }>>();
  for (const route of routes) {
    if (route.navigation === undefined) continue;
    const entries = groups.get(route.navigation.section) ?? [];
    entries.push({
      path: route.path,
      label: route.navigation.label,
      order: route.navigation.order,
    });
    groups.set(route.navigation.section, entries);
  }
  return GUIDE_SECTIONS.filter((section) => groups.has(section)).map((section) => ({
    section,
    entries: groups
      .get(section)!
      .toSorted((a, b) => a.order - b.order)
      .map(({ path, label }) => ({ path, label })),
  }));
}

/** Server/search projection: full per-route metadata only. */
export function generateDocsRouteProjection(
  inventory: readonly DocsRouteRecord[],
): Promise<string> {
  const routes = withGuideHeadings(inventory);
  const source = `// Generated by bun scripts/gen-docs-routes.ts — do not edit.\nimport type { DocsRouteMetadata } from "../route-types.js";\n\nexport const DOCS_ROUTES = ${JSON.stringify(routes, null, 2)} as const satisfies readonly DocsRouteMetadata[];\n`;
  return formatGeneratedSource(ROUTES_OUTPUT_PATH, source);
}

/**
 * Client shell projection: guide sidebar map only.
 *
 * Kept in a separate ESM module from DOCS_ROUTES so importing
 * GUIDE_NAVIGATION cannot pull the full ~120KB route catalog into layout JS.
 */
export function generateDocsGuideNavigationProjection(
  inventory: readonly DocsRouteRecord[],
): Promise<string> {
  const navigation = guideNavigation(withGuideHeadings(inventory));
  const source = `// Generated by bun scripts/gen-docs-routes.ts — do not edit.\nimport type { GuideNavigationGroup } from "../route-types.js";\n\nexport const GUIDE_NAVIGATION = ${JSON.stringify(navigation, null, 2)} as const satisfies readonly GuideNavigationGroup[];\n`;
  return formatGeneratedSource(GUIDE_NAV_OUTPUT_PATH, source);
}

/** DOCS_ROUTES artifact — search and server routes depend on this alone. */
export const docsRoutesArtifact = defineArtifact({
  path: ROUTES_OUTPUT_PATH,
  label: "apps/docs/src/lib/generated/routes.ts",
  regenerateWith: "docs:routes:gen",
  // lifecycle.json feeds guide headings; stale lifecycle must not blame routes alone.
  dependsOn: [lifecycleArtifact],
  build: () => generateDocsRouteProjection(createDocsRouteInventory()),
});

export const docsGuideNavigationArtifact = defineArtifact({
  path: GUIDE_NAV_OUTPUT_PATH,
  label: "apps/docs/src/lib/generated/guide-navigation.ts",
  regenerateWith: "docs:routes:gen",
  dependsOn: [lifecycleArtifact],
  build: () => generateDocsGuideNavigationProjection(createDocsRouteInventory()),
});

const docsRoutesArtifacts = defineArtifactGroup({
  regenerateWith: "docs:routes:gen",
  members: [docsRoutesArtifact, docsGuideNavigationArtifact],
});

export async function generateDocsRoutes(check = false): Promise<void> {
  if (check) {
    await docsRoutesArtifacts.check();
    console.log("docs route projections are current");
    return;
  }
  await docsRoutesArtifacts.write();
  console.log(`wrote ${ROUTES_OUTPUT_PATH}`);
  console.log(`wrote ${GUIDE_NAV_OUTPUT_PATH}`);
}

if (import.meta.main || import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  await docsRoutesArtifacts.cli();
}
