/**
 * gen-scale-children — generates declaration-only <Scale*> shells for every
 * camelCase scale helper in SCALE_CAPABILITIES (#659 slice 4).
 *
 * Manifest: scripts/gen-scale-children-manifest.ts (ledger + completeness).
 * This file owns pure emission, index rewrite, and the CLI entrypoint.
 *
 * Usage:
 *   bun scripts/gen-scale-children.ts           # (re)write shells + index region
 *   bun scripts/gen-scale-children.ts --check   # exit 1 on drift without writing
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { defineArtifact, defineArtifactGroup } from "./artifact.ts";
import { SHELL_MANIFEST, manifestAliases, type ShellSpec } from "./gen-scale-children-manifest.ts";

// ---------------------------------------------------------------------------
// Paths + markers
// ---------------------------------------------------------------------------

export const SCALE_DIR = "packages/svelte/src/lib/scale";
export const INDEX_PATH = "packages/svelte/src/lib/index.ts";

export const REGION_START = "// <generated:scale-children> — bun run scale:children:gen";
export const REGION_END = "// </generated:scale-children>";

export const GENERATED_HEADER =
  "<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->";

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

/** Render one shell .svelte source. Pure — unit-tested; prettier-stable (printWidth 80). */
export function renderShell(spec: ShellSpec): string {
  // Match prettier: single-line import when it fits, multi-line otherwise.
  let importBlock: string;
  if (spec.typeImports.length === 1) {
    const single = `  import { ${spec.helper}, type ${spec.typeImports[0]} } from "@ggsvelte/spec";`;
    if (single.length <= 80) {
      importBlock = single;
    } else {
      importBlock = [
        `  import {`,
        `    ${spec.helper},`,
        `    type ${spec.typeImports[0]},`,
        `  } from "@ggsvelte/spec";`,
      ].join("\n");
    }
  } else {
    importBlock = [
      `  import {`,
      `    ${spec.helper},`,
      ...spec.typeImports.map((name) => `    type ${name},`),
      `  } from "@ggsvelte/spec";`,
    ].join("\n");
  }
  const temporalImport = spec.optionsType.startsWith("Temporal")
    ? `  import "@ggsvelte/core/temporal";`
    : undefined;
  // Long Omit annotations exceed printWidth; wrap the `= $props()` assignment.
  const propsSingle = `  const props: ${spec.optionsType} = $props();`;
  const propsBlock =
    propsSingle.length > 80 ? `  const props: ${spec.optionsType} =\n    $props();` : propsSingle;
  // Multi-line factory import: single-line form exceeds prettier printWidth 80
  // (`createPlotLayer, definedProps` from `../layers/plot-layer.svelte.js`).
  const factoryImport = [
    `  import {`,
    `    createPlotLayer,`,
    `    definedProps,`,
    `  } from "../layers/plot-layer.svelte.js";`,
  ].join("\n");
  // createPlotLayer("scale", () => helper(definedProps(props))) — longest
  // helper names still fit printWidth 80 (e.g. scaleLinewidthContinuous).
  const createCall = `  createPlotLayer("scale", () => ${spec.helper}(definedProps(props)));`;
  return [
    GENERATED_HEADER,
    `<script lang="ts">`,
    importBlock,
    ...(temporalImport === undefined ? [] : [temporalImport]),
    factoryImport,
    ``,
    propsBlock,
    createCall,
    `</script>`,
    ``,
  ].join("\n");
}

/**
 * One compact lifecycle-tagged export line (form gen-lifecycle already
 * parses): an inline `@lifecycle` JSDoc marker, then the single-name
 * statement on the same line. oxfmt hugs single-specifier exports, so the
 * line is stable at any length.
 */
function exportLine(asName: string, fileComponent: string): string {
  return `/** @lifecycle stable-intent */ export { default as ${asName} } from "./scale/${fileComponent}.svelte";`;
}

/** Render the full delimited index region body (markers included). Pure. */
export function renderIndexRegion(manifest: readonly ShellSpec[] = SHELL_MANIFEST): string {
  const lines: string[] = [REGION_START];
  for (const spec of manifest) {
    lines.push(exportLine(spec.component, spec.component));
  }
  for (const spec of manifest) {
    for (const alias of spec.aliases ?? []) {
      lines.push(exportLine(alias, spec.component));
    }
  }
  lines.push(REGION_END);
  return lines.join("\n");
}

/**
 * Rewrite the delimited region in index.ts source. FAILS HARD if either
 * marker is missing — never silently appends.
 */
export function rewriteIndexRegion(source: string, region: string = renderIndexRegion()): string {
  const startIdx = source.indexOf(REGION_START);
  const endIdx = source.indexOf(REGION_END);
  if (startIdx === -1 || endIdx === -1) {
    const missing =
      startIdx === -1 && endIdx === -1
        ? "both markers"
        : startIdx === -1
          ? `start marker (${REGION_START})`
          : `end marker (${REGION_END})`;
    throw new Error(
      `scale-children index region markers missing (${missing}). ` +
        `Expected both:\n  ${REGION_START}\n  ${REGION_END}\n` +
        `in ${INDEX_PATH}. Refusing to append silently.`,
    );
  }
  if (endIdx < startIdx) {
    throw new Error(
      `scale-children index region markers out of order in ${INDEX_PATH}: ` +
        `end marker appears before start marker.`,
    );
  }
  // Include the end marker line fully (through its trailing newline if any).
  const endLineEnd = endIdx + REGION_END.length;
  const afterEnd = source.slice(endLineEnd);
  const consumedEnd = afterEnd.startsWith("\n") ? endLineEnd + 1 : endLineEnd;
  return source.slice(0, startIdx) + region + "\n" + source.slice(consumedEnd);
}

/** Relative path of a shell file from repo root. */
export function shellRelPath(component: string): string {
  return `${SCALE_DIR}/${component}.svelte`;
}

// ---------------------------------------------------------------------------
// CLI (#783 shared protocol)
// ---------------------------------------------------------------------------

export interface GenerateResult {
  wrote: string[];
  unchanged: string[];
  indexChanged: boolean;
}

function scaleChildrenGroup(repoRoot: string) {
  const shellMembers = SHELL_MANIFEST.map((spec) => {
    const rel = shellRelPath(spec.component);
    return defineArtifact({
      path: join(repoRoot, rel),
      label: rel,
      regenerateWith: "scale:children:gen",
      build: () => renderShell(spec),
    });
  });
  const indexMember = defineArtifact({
    path: join(repoRoot, INDEX_PATH),
    label: INDEX_PATH,
    regenerateWith: "scale:children:gen",
    build: () => {
      const indexAbs = join(repoRoot, INDEX_PATH);
      // Index always exists; rewrite the generated region in place.
      return rewriteIndexRegion(readFileSync(indexAbs, "utf8"));
    },
  });
  return defineArtifactGroup({
    regenerateWith: "scale:children:gen",
    members: [...shellMembers, indexMember],
    // Intentionally no orphan Scale*.svelte scan — current --check is first-stale only.
  });
}

export function generateScaleChildren(opts: { repoRoot: string; check?: boolean }): GenerateResult {
  const { repoRoot, check = false } = opts;
  const wrote: string[] = [];
  const unchanged: string[] = [];
  let indexChanged = false;

  // Keep the programmatic API for tests; CLI routes through defineArtifactGroup.
  for (const spec of SHELL_MANIFEST) {
    const rel = shellRelPath(spec.component);
    const abs = join(repoRoot, rel);
    const fresh = renderShell(spec);
    const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
    if (current === fresh) {
      unchanged.push(rel);
      continue;
    }
    if (check) {
      throw new Error(
        current === null
          ? `${rel} is MISSING. Run: bun run scale:children:gen`
          : `${rel} is STALE. Run: bun run scale:children:gen`,
      );
    }
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, fresh);
    wrote.push(rel);
  }

  const indexAbs = join(repoRoot, INDEX_PATH);
  const indexSrc = readFileSync(indexAbs, "utf8");
  const freshIndex = rewriteIndexRegion(indexSrc);
  if (freshIndex !== indexSrc) {
    indexChanged = true;
    if (check) {
      throw new Error(`${INDEX_PATH} generated region is STALE. Run: bun run scale:children:gen`);
    }
    writeFileSync(indexAbs, freshIndex);
  }

  return { wrote, unchanged, indexChanged };
}

if (import.meta.main) {
  const repoRoot = join(import.meta.dir, "..");
  const group = scaleChildrenGroup(repoRoot);
  try {
    if (process.argv.includes("--check")) {
      await group.check();
      console.log(
        `scale children are current (${String(SHELL_MANIFEST.length)} shells, ` +
          `${String(manifestAliases().size)} aliases).`,
      );
    } else {
      await group.write();
      console.log(
        `scale children generated (${String(SHELL_MANIFEST.length)} shells, ` +
          `${String(manifestAliases().size)} aliases).`,
      );
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
