/**
 * Render the getting-started lesson's step charts to static SVG files.
 *
 * Eight live 838-point plots on one page cost roughly three seconds of
 * hydration each — measured on the built site — which is not a page anyone
 * should have to wait for. The step charts are illustrations of one delta, so
 * they ship as real library output rendered at build time; the inspect step
 * and the finished chart stay live, because interaction is the thing they are
 * there to demonstrate.
 *
 * This is the same shape as gen-gallery-previews: generate into
 * apps/docs/static, project an inventory module, and offer --check for CI.
 *
 *   bun scripts/gen-lesson-charts.ts          # write
 *   bun scripts/gen-lesson-charts.ts --check  # verify committed output
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { renderToSVGString } from "@ggsvelte/core";

import { kyotoSakura } from "../packages/svelte/src/lib/data/index.js";
import {
  ArtifactError,
  defineArtifact,
  defineArtifactGroup,
  formatGeneratedSource,
} from "./artifact.ts";
import { foldSakura, SAKURA_STEPS } from "./quickstart.js";

const ROOT = resolve(import.meta.dir, "..");
const OUTPUT_DIR = join(ROOT, "apps", "docs", "static", "lesson");
const PROJECTION = join(ROOT, "apps", "docs", "src", "lib", "generated", "lesson-charts.ts");

/**
 * Steps rendered live in the browser, by index into SAKURA_STEPS.
 *
 * None: the finished chart directly below the steps is live and full width,
 * which is where inspection is worth demonstrating. A second live copy of the
 * same 838 points bought nothing and cost another three seconds of hydration.
 */
export const LIVE_STEP_INDEXES: readonly number[] = [];

/** Nominal size; the SVG scales to its container via viewBox. */
export const LESSON_CHART_WIDTH = 660;
export const LESSON_CHART_HEIGHT = 400;

export interface LessonChartEntry {
  /** -1 is the first render, before any step. */
  step: number;
  filename: string;
}

export function lessonChartFilename(step: number): string {
  return step < 0 ? "first-render.svg" : `step-${String(step + 1)}.svg`;
}

/** Every chart the page shows statically, first render first. */
export function staticLessonSteps(): number[] {
  const steps = [-1];
  for (let index = 0; index < SAKURA_STEPS.length; index += 1) {
    if (!LIVE_STEP_INDEXES.includes(index)) steps.push(index);
  }
  return steps;
}

export function renderLessonChart(step: number): string {
  const rows = kyotoSakura.map((row) => ({ ...row }));
  // Rendered at the width the step gives them, which is wide enough for the
  // record callouts (the ladder in the component uses the same threshold).
  const { spec } = foldSakura(step + 1, rows);
  // renderToSVGString already emits xmlns and viewBox, which is what makes the
  // output valid as a standalone image.
  return `${renderToSVGString(spec, {
    width: LESSON_CHART_WIDTH,
    height: LESSON_CHART_HEIGHT,
  })}\n`;
}

function projection(entries: readonly LessonChartEntry[]): Promise<string> {
  // Preserve the historical oxfmt path string for byte-stable output (#783 review).
  return formatGeneratedSource(
    "lesson-charts.ts",
    `// Generated by scripts/gen-lesson-charts.ts. Do not edit.
// Static renders of the getting-started lesson steps; regenerate with
// \`bun run lesson:charts:gen\`.
export interface LessonChartEntry {
  step: number;
  filename: string;
}

export const LESSON_CHART_WIDTH = ${String(LESSON_CHART_WIDTH)};
export const LESSON_CHART_HEIGHT = ${String(LESSON_CHART_HEIGHT)};

export const LESSON_CHARTS: readonly LessonChartEntry[] = ${JSON.stringify(entries)};

/** Step indexes rendered live in the browser (interaction is the point). */
export const LIVE_STEP_INDEXES: readonly number[] = ${JSON.stringify([...LIVE_STEP_INDEXES])};
`,
  );
}

function lessonChartEntries(): LessonChartEntry[] {
  return staticLessonSteps().map((step) => ({
    step,
    filename: lessonChartFilename(step),
  }));
}

function lessonArtifacts(entries: readonly LessonChartEntry[]) {
  const svgMembers = entries.map((entry) =>
    defineArtifact({
      path: join(OUTPUT_DIR, entry.filename),
      label: entry.filename,
      regenerateWith: "lesson:charts:gen",
      build: () => renderLessonChart(entry.step),
    }),
  );
  const projectionMember = defineArtifact({
    path: PROJECTION,
    label: "apps/docs/src/lib/generated/lesson-charts.ts",
    regenerateWith: "lesson:charts:gen",
    build: () => projection(entries),
  });
  return defineArtifactGroup({
    regenerateWith: "lesson:charts:gen",
    members: [...svgMembers, projectionMember],
    extraCheck: () => {
      // An extra file left behind would still be served.
      let present: string[] = [];
      try {
        present = readdirSync(OUTPUT_DIR);
      } catch {
        present = [];
      }
      const expected = new Set(entries.map((entry) => entry.filename));
      for (const file of present) {
        if (!expected.has(file)) {
          throw new ArtifactError({
            status: "STALE",
            path: join(OUTPUT_DIR, file),
            regenerateWith: "lesson:charts:gen",
            label: file,
          });
        }
      }
    },
    extraWrite: () => {
      // Members already wrote; nothing else. Wipe happens before write below.
    },
  });
}

export async function generateLessonCharts(options: { check?: boolean } = {}): Promise<{
  entries: LessonChartEntry[];
  stale: string[];
}> {
  const entries = lessonChartEntries();
  const group = lessonArtifacts(entries);
  if (options.check === true) {
    try {
      await group.check();
      return { entries, stale: [] };
    } catch (error) {
      if (error instanceof ArtifactError) {
        return {
          entries,
          stale: [error.because?.artifactPath ?? error.artifactPath].map((p) => {
            const base = p.split("/").pop() ?? p;
            return base === "lesson-charts.ts" || p.endsWith("lesson-charts.ts")
              ? "lesson-charts.ts"
              : base;
          }),
        };
      }
      throw error;
    }
  }
  rmSync(OUTPUT_DIR, { recursive: true, force: true });
  mkdirSync(OUTPUT_DIR, { recursive: true });
  // Write SVGs + projection via protocol (dir pre-wiped so orphans cannot remain).
  for (const entry of entries) {
    writeFileSync(join(OUTPUT_DIR, entry.filename), renderLessonChart(entry.step));
  }
  writeFileSync(PROJECTION, await projection(entries));
  return { entries, stale: [] };
}

if (import.meta.main) {
  const entries = lessonChartEntries();
  const group = lessonArtifacts(entries);
  if (process.argv.includes("--check")) {
    await group.cli(["--check"]);
  } else {
    rmSync(OUTPUT_DIR, { recursive: true, force: true });
    mkdirSync(OUTPUT_DIR, { recursive: true });
    await group.write();
    console.log(`wrote ${String(entries.length)} lesson charts to ${OUTPUT_DIR}`);
  }
}
