/**
 * Generate @ggsvelte/react Geom, Scale, and Theme shells from existing manifests.
 */
import { mkdirSync, writeFileSync } from "node:fs";

import { SCALE_CAPABILITIES } from "@ggsvelte/spec";

import { SHELL_MANIFEST as GEOM_MANIFEST } from "./gen-geom-children-manifest.ts";
import { SHELL_MANIFEST as SCALE_MANIFEST } from "./gen-scale-children-manifest.ts";

const GEOM_DIR = "packages/react/src/geoms";
const SCALE_OUT = "packages/react/src/scales.tsx";
const THEME_OUT = "packages/react/src/themes.tsx";

function geomShellBody(spec: (typeof GEOM_MANIFEST)[number]): string[] {
  if (spec.kind === "jitter") {
    return [
      `export function ${spec.component}(props: ShellProps): ReactNode {`,
      `  const { width, height, seed, positionParams, ...rest } = props;`,
      `  useGeomLayer("jitter", {`,
      `    ...rest,`,
      `    positionParams: {`,
      `      ...positionParams,`,
      `      ...(typeof width === "number" ? { width } : {}),`,
      `      ...(typeof height === "number" ? { height } : {}),`,
      `      ...(typeof seed === "number" ? { seed } : {}),`,
      `    },`,
      `  });`,
      `  return null;`,
      `}`,
    ];
  }
  return [
    `export function ${spec.component}(props: ShellProps): ReactNode {`,
    `  useGeomLayer("${spec.geom}", props);`,
    `  return null;`,
    `}`,
  ];
}

function writeGeomFiles(): void {
  mkdirSync(GEOM_DIR, { recursive: true });
  const index: string[] = [`/* GENERATED by scripts/gen-react-children.ts — do not edit. */`, ``];
  for (const spec of GEOM_MANIFEST) {
    const register =
      spec.registration === undefined
        ? []
        : [`import { ${spec.registration} } from "@ggsvelte/core";`, `${spec.registration}();`, ``];
    const source = [
      `/* GENERATED by scripts/gen-react-children.ts — do not edit. */`,
      `import type { ReactNode } from "react";`,
      `import type { DataInput } from "@ggsvelte/spec";`,
      `import { useGeomLayer, type GeomProps } from "../geom-factory.js";`,
      ...register,
      `type ShellProps = GeomProps & Record<string, unknown> & {`,
      `  data?: DataInput | readonly Record<string, unknown>[];`,
      `};`,
      ``,
      ...geomShellBody(spec),
      ``,
    ].join("\n");
    writeFileSync(`${GEOM_DIR}/${spec.component}.tsx`, source);
    index.push(`export { ${spec.component} } from "./${spec.component}.js";`);
  }
  index.push(``);
  writeFileSync(`${GEOM_DIR}/index.ts`, index.join("\n"));
}

function scaleFile(): string {
  const helpers = SCALE_MANIFEST.map((s) => s.helper);
  const lines = [
    `/* GENERATED by scripts/gen-react-children.ts — do not edit. */`,
    `import "@ggsvelte/core/temporal";`,
    `import type { ReactNode } from "react";`,
    `import {`,
    ...helpers.map((h, i) => `  ${h}${i < helpers.length - 1 ? "," : ""}`),
    `} from "@ggsvelte/spec";`,
    `import { definedProps } from "./defined-props.js";`,
    `import { usePlotLayerValue } from "./geom-factory.js";`,
    ``,
  ];
  for (const spec of SCALE_MANIFEST) {
    lines.push(
      `export function ${spec.component}(props: Record<string, unknown> = {}): ReactNode {`,
      `  usePlotLayerValue("scale", () => ${spec.helper}(definedProps(props) as never));`,
      `  return null;`,
      `}`,
    );
    if (spec.aliases) {
      for (const alias of spec.aliases) {
        lines.push(`export { ${spec.component} as ${alias} };`);
      }
    }
    lines.push(``);
  }
  void SCALE_CAPABILITIES;
  return lines.join("\n");
}

function pascalTheme(name: string): string {
  return name
    .split(/[_-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

const THEME_COMPONENTS: [string, string][] = [
  ["default", "ThemeDefault"],
  ["light", "ThemeLight"],
  ["dark", "ThemeDark"],
  ["minimal", "ThemeMinimal"],
  ["ggplot2", "ThemeGgplot2"],
  ["classic", "ThemeClassic"],
  ["bw", "ThemeBw"],
  ["hrbr", "ThemeHrbr"],
  ["few", "ThemeFew"],
  ["clean", "ThemeClean"],
  ["fivethirtyeight", "ThemeFivethirtyeight"],
  ["economist", "ThemeEconomist"],
  ["tufte", "ThemeTufte"],
  ["linedraw", "ThemeLinedraw"],
  ["void", "ThemeVoid"],
  ["stata", "ThemeStata"],
  ["stata_s1color", "ThemeStatas1color"],
  ["solarized", "ThemeSolarized"],
  ["solarizeddark", "ThemeSolarizeddark"],
  ["economist_white", "ThemeEconomistwhite"],
  ["solarized_2", "ThemeSolarized2"],
  ["solarized_2dark", "ThemeSolarized2dark"],
  ["wsj", "ThemeWsj"],
  ["hc", "ThemeHc"],
  ["hcdark", "ThemeHcdark"],
  ["pander", "ThemePander"],
  ["base", "ThemeBase"],
  ["igray", "ThemeIgray"],
  ["map", "ThemeMap"],
  ["solid", "ThemeSolid"],
  ["grey", "ThemeGrey"],
  ["gray", "ThemeGray"],
];

function themeFile(): string {
  const extra = THEME_COMPONENTS.filter(([name]) => pascalTheme(name) !== name);
  void extra;
  const lines = [
    `/* GENERATED by scripts/gen-react-children.ts — do not edit. */`,
    `import type { ReactNode } from "react";`,
    `import type { ThemeName, ThemeSpec } from "@ggsvelte/spec";`,
    `import { definedProps } from "./defined-props.js";`,
    `import { usePlotLayerValue } from "./geom-factory.js";`,
    ``,
    `type RoleProps = Partial<ThemeSpec>;`,
    ``,
    `function useNamedTheme(name: ThemeName, props: RoleProps): void {`,
    `  usePlotLayerValue("theme", () => {`,
    `    const roles = definedProps(props);`,
    `    return Object.keys(roles).length === 0 ? name : { name, ...roles };`,
    `  });`,
    `}`,
    ``,
  ];
  for (const [name, component] of THEME_COMPONENTS) {
    lines.push(
      `export function ${component}(props: RoleProps = {}): ReactNode {`,
      `  useNamedTheme("${name}", props);`,
      `  return null;`,
      `}`,
      ``,
    );
  }
  lines.push(
    `export function ThemeTest(props: RoleProps = {}): ReactNode {`,
    `  useNamedTheme("test", props);`,
    `  return null;`,
    `}`,
    ``,
  );
  return lines.join("\n");
}

writeGeomFiles();
writeFileSync(SCALE_OUT, scaleFile());
writeFileSync(THEME_OUT, themeFile());
console.log(`wrote ${GEOM_DIR}/* , ${SCALE_OUT}, ${THEME_OUT}`);
