/**
 * Emit static SVG shells for themes / palettes pages as separate files.
 *
 * Inlining every shell into +page.server load data bloated prerendered HTML
 * (~475 KB themes, ~390 KB palettes) because each SVG was also duplicated into
 * the SvelteKit data payload. Files under apps/docs/static are one request
 * each and stay off the HTML critical path until the browser paints them.
 *
 *   bun scripts/gen-theme-static-shells.ts
 *   bun scripts/gen-theme-static-shells.ts --check
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import type { ColorScaleSpec } from "@ggsvelte/spec";

import { CATEGORICAL_PALETTES } from "../apps/docs/src/lib/catalog/themes.js";
import {
  isMarksOnlyTheme,
  MARKS_ONLY_DARK_SITE_ROLES,
} from "../apps/docs/src/lib/marks-only-theme-contrast.js";
import { RASTER_Z_DOMAIN, THEME_SPECIMENS } from "../apps/docs/src/lib/theme-specimens/catalog.js";
import {
  paletteSpecimenStaticSvg,
  sequentialRasterStaticSvg,
  temperaturesStaticSvg,
  themeSpecimenStaticSvg,
} from "../apps/docs/src/lib/theme-specimens/static-svg.js";
import { formatGeneratedSource } from "./artifact.ts";

const ROOT = resolve(import.meta.dir, "..");
const OUTPUT_DIR = join(ROOT, "apps", "docs", "static", "theme-shells");
const PROJECTION = join(ROOT, "apps", "docs", "src", "lib", "generated", "theme-static-shells.ts");

const SEQUENTIAL_EXAMPLES: readonly {
  id: string;
  label: string;
  scale: ColorScaleSpec;
}[] = [
  {
    id: "viridis",
    label: "Viridis",
    scale: { type: "sequential", scheme: "viridis" },
  },
  {
    id: "viridis-reversed",
    label: "Reversed",
    scale: { type: "sequential", scheme: "viridis", reverse: true },
  },
  {
    id: "custom-range",
    label: "Custom range",
    scale: {
      type: "sequential",
      range: ["#2d1e2f", "#3d5a80", "#e76f51"],
    },
  },
  {
    id: "pinned-domain",
    label: "Pinned domain",
    scale: {
      type: "sequential",
      scheme: "viridis",
      domain: [...RASTER_Z_DOMAIN],
    },
  },
];

type ShellFile = { filename: string; body: string };

function sha256(body: string): string {
  return createHash("sha256").update(body).digest("hex");
}

function buildShells(): ShellFile[] {
  const files: ShellFile[] = [];
  for (const specimen of THEME_SPECIMENS) {
    files.push({
      filename: `theme-${specimen.name}.svg`,
      body: themeSpecimenStaticSvg({
        name: specimen.name,
        kind: specimen.kind,
        scheme: specimen.scheme,
        height: 380,
      }),
    });
    // Transparent-paper themes need a second portrait for the dark docs shell
    // (dark ink on transparent paper vanishes into the page background).
    if (isMarksOnlyTheme(specimen.name)) {
      files.push({
        filename: `theme-${specimen.name}-dark-site.svg`,
        body: themeSpecimenStaticSvg({
          name: specimen.name,
          kind: specimen.kind,
          scheme: specimen.scheme,
          height: 380,
          themeRoles: MARKS_ONLY_DARK_SITE_ROLES,
        }),
      });
    }
  }
  files.push({
    filename: "theme-lab-default.svg",
    body: temperaturesStaticSvg({
      theme: "default",
      scheme: "observable10",
      height: 400,
    }),
  });
  for (const palette of CATEGORICAL_PALETTES) {
    files.push({
      filename: `palette-${palette.name}.svg`,
      body: paletteSpecimenStaticSvg({
        scheme: palette.name,
        capacity: palette.capacity,
        reverse: false,
        paperTheme: "light",
      }),
    });
  }
  for (const example of SEQUENTIAL_EXAMPLES) {
    files.push({
      filename: `sequential-${example.id}.svg`,
      body: sequentialRasterStaticSvg({
        label: example.label,
        scale: example.scale,
        height: 360,
      }),
    });
  }
  return files;
}

function projectionSource(files: readonly ShellFile[]): Promise<string> {
  const entries = files
    .map((file) => {
      const id = file.filename.replace(/\.svg$/, "");
      const path = `/theme-shells/${file.filename}`;
      return `  {\n    id: ${JSON.stringify(id)},\n    filename: ${JSON.stringify(file.filename)},\n    path: ${JSON.stringify(path)},\n    sha256: ${JSON.stringify(sha256(file.body))},\n  }`;
    })
    .join(",\n");
  const raw = `// Generated by bun scripts/gen-theme-static-shells.ts — do not edit.

export interface ThemeStaticShell {
  readonly id: string;
  readonly filename: string;
  readonly path: string;
  readonly sha256: string;
}

export const THEME_STATIC_SHELLS = [
${entries},
] as const;

export const THEME_STATIC_SHELL_BY_ID: Readonly<Record<string, string>> =
  Object.fromEntries(THEME_STATIC_SHELLS.map((s) => [s.id, s.path]));
`;
  // Match pre-commit oxfmt so --check stays byte-stable.
  return formatGeneratedSource(PROJECTION, raw);
}

async function check(files: readonly ShellFile[]): Promise<void> {
  if (!existsSync(OUTPUT_DIR) || !existsSync(PROJECTION)) {
    throw new Error("theme-static-shells is MISSING. Run: bun scripts/gen-theme-static-shells.ts");
  }
  const wantNames = new Set(files.map((f) => f.filename));
  const haveNames = new Set(readdirSync(OUTPUT_DIR).filter((n) => n.endsWith(".svg")));
  for (const name of wantNames) {
    if (!haveNames.has(name)) {
      throw new Error(
        `theme-static-shells STALE (missing ${name}). Run: bun scripts/gen-theme-static-shells.ts`,
      );
    }
    const onDisk = readFileSync(join(OUTPUT_DIR, name), "utf8");
    const want = files.find((f) => f.filename === name)!.body;
    if (onDisk !== want) {
      throw new Error(
        `theme-static-shells STALE (${name} content). Run: bun scripts/gen-theme-static-shells.ts`,
      );
    }
  }
  for (const name of haveNames) {
    if (!wantNames.has(name)) {
      throw new Error(
        `theme-static-shells STALE (orphan ${name}). Run: bun scripts/gen-theme-static-shells.ts`,
      );
    }
  }
  const wantProj = await projectionSource(files);
  const haveProj = readFileSync(PROJECTION, "utf8");
  if (haveProj !== wantProj) {
    throw new Error(
      "theme-static-shells projection STALE. Run: bun scripts/gen-theme-static-shells.ts",
    );
  }
  console.log("theme:static-shells artifacts are current.");
}

async function write(files: readonly ShellFile[]): Promise<void> {
  rmSync(OUTPUT_DIR, { recursive: true, force: true });
  mkdirSync(OUTPUT_DIR, { recursive: true });
  for (const file of files) {
    writeFileSync(join(OUTPUT_DIR, file.filename), file.body);
  }
  writeFileSync(PROJECTION, await projectionSource(files));
  console.log(`wrote ${String(files.length)} theme/palette shells to ${OUTPUT_DIR}`);
}

if (import.meta.main) {
  const files = buildShells();
  if (process.argv.includes("--check")) {
    await check(files);
  } else {
    await write(files);
  }
}
