/**
 * gen-geom-children — generates declaration-only <Geom*> shells for every
 * KNOWN_GEOMS entry (#1039). Param keys live in GEOM_PARAM_KEYS; shells only
 * wire types + createGeomLayer.
 *
 * Manifest: scripts/gen-geom-children-manifest.ts (ledger + completeness).
 * This file owns pure emission, index rewrite, and the CLI entrypoint.
 *
 * Usage:
 *   bun scripts/gen-geom-children.ts           # (re)write shells + index region
 *   bun scripts/gen-geom-children.ts --check   # exit 1 on drift without writing
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { defineArtifact, defineArtifactGroup } from "./artifact.ts";
import { SHELL_MANIFEST, type ShellSpec } from "./gen-geom-children-manifest.ts";

// ---------------------------------------------------------------------------
// Paths + markers
// ---------------------------------------------------------------------------

export const GEOM_DIR = "packages/svelte/src/lib/geoms";
export const INDEX_PATH = "packages/svelte/src/lib/index.ts";

export const REGION_START = "// <generated:geom-children> — bun run geom:children:gen";
export const REGION_END = "// </generated:geom-children>";

export const GENERATED_HEADER =
  "<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->";

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

const DATA_OVERRIDE = "data?: DataInput | readonly Record<string, unknown>[]";

/**
 * Type import block matching prettier-plugin-svelte: short lists stay
 * single-line; longer lists (jitter) multi-line.
 */
function typeImportBlock(spec: ShellSpec): string {
  if (spec.kind === "jitter") {
    return [
      `  import type {`,
      `    DataInput,`,
      `    PositionParams,`,
      `    ${spec.paramsType},`,
      `    ${spec.layerInput},`,
      `  } from "@ggsvelte/spec";`,
    ].join("\n");
  }
  const single = `  import type { DataInput, ${spec.paramsType}, ${spec.layerInput} } from "@ggsvelte/spec";`;
  if (single.length <= 80) return single;
  return [
    `  import type {`,
    `    DataInput,`,
    `    ${spec.paramsType},`,
    `    ${spec.layerInput},`,
    `  } from "@ggsvelte/spec";`,
  ].join("\n");
}

/** Props type expression matching prettier brace layout. */
function propsTypeExpr(spec: ShellSpec): string {
  return (
    `${spec.paramsType} &\n` +
    `    Omit<${spec.layerInput}, "geom" | "params" | "data"> & {\n` +
    `      ${DATA_OVERRIDE};\n` +
    `    }`
  );
}

/** Render one shell .svelte source. Pure — unit-tested; prettier-stable. */
export function renderShell(spec: ShellSpec): string {
  if (spec.kind === "jitter") {
    return renderJitterShell(spec);
  }
  return [
    GENERATED_HEADER,
    ...registrationBlock(spec),
    `<script lang="ts">`,
    typeImportBlock(spec),
    ``,
    `  import { createGeomLayer } from "./factory.svelte.js";`,
    ``,
    `  const props: ${propsTypeExpr(spec)} = $props();`,
    `  createGeomLayer("${spec.geom}", () => props);`,
    `</script>`,
    ``,
  ].join("\n");
}

/**
 * Self-registration <script module> block (#1420) for specialty shells:
 * importing the component is what pulls its geom batch + default stat frame
 * into the consumer bundle. Runs once per module evaluation; idempotent.
 */
function registrationBlock(spec: ShellSpec): string[] {
  if (spec.registration === undefined) return [];
  return [
    `<script module lang="ts">`,
    `  import { ${spec.registration} } from "@ggsvelte/core";`,
    ``,
    `  // Self-registration (#1420): this component's geom batch + default stat`,
    `  // frame enter the bundle (and the core registries) only when the`,
    `  // component itself is imported. Idempotent.`,
    `  ${spec.registration}();`,
    `</script>`,
    ``,
  ];
}

/**
 * GeomJitter: flat width/height/seed assemble into positionParams (ggplot2
 * geom_jitter sugar). Param whitelist is still PointParams via the factory.
 */
function renderJitterShell(spec: ShellSpec): string {
  const propsType =
    `${spec.paramsType} &\n` +
    `    Omit<${spec.layerInput}, "geom" | "params" | "data"> & {\n` +
    `      ${DATA_OVERRIDE};\n` +
    `      /** Maximum horizontal jitter (data units / band-step fraction). */\n` +
    `      width?: number;\n` +
    `      /** Maximum vertical jitter (data units / band-step fraction). */\n` +
    `      height?: number;\n` +
    `      /** Seeded RNG seed (ggsvelte jitter is always seeded; default 42). */\n` +
    `      seed?: number;\n` +
    `    }`;
  return [
    GENERATED_HEADER,
    `<script lang="ts">`,
    typeImportBlock(spec),
    ``,
    `  import { createGeomLayer } from "./factory.svelte.js";`,
    ``,
    `  const props: ${propsType} = $props();`,
    `  createGeomLayer("${spec.geom}", () => {`,
    `    const { width, height, seed, positionParams, ...rest } = props;`,
    `    const merged: PositionParams = {`,
    `      ...positionParams,`,
    `      ...(width !== undefined && { width }),`,
    `      ...(height !== undefined && { height }),`,
    `      ...(seed !== undefined && { seed }),`,
    `    };`,
    `    return {`,
    `      ...rest,`,
    `      ...(Object.keys(merged).length > 0 && { positionParams: merged }),`,
    `    };`,
    `  });`,
    `</script>`,
    ``,
  ].join("\n");
}

function exportLine(component: string): string {
  return [
    `/** @lifecycle stable-intent */`,
    `export { default as ${component} } from "./geoms/${component}.svelte";`,
  ].join("\n");
}

/** Render the full delimited index region body (markers included). Pure. */
export function renderIndexRegion(manifest: readonly ShellSpec[] = SHELL_MANIFEST): string {
  const lines: string[] = [REGION_START];
  for (const spec of manifest) {
    lines.push(exportLine(spec.component));
  }
  lines.push(REGION_END);
  return lines.join("\n");
}

/**
 * Rewrite the delimited region in index.ts source. FAILS HARD if either
 * marker is missing — never silently appends.
 */
export function rewriteIndexRegion(source: string, region: string = renderIndexRegion()): string {
  const startIdx = source.indexOf(REGION_START);
  const endIdx = source.indexOf(REGION_END);
  if (startIdx === -1 || endIdx === -1) {
    const missing =
      startIdx === -1 && endIdx === -1
        ? "both markers"
        : startIdx === -1
          ? `start marker (${REGION_START})`
          : `end marker (${REGION_END})`;
    throw new Error(
      `geom-children index region markers missing (${missing}). ` +
        `Expected both:\n  ${REGION_START}\n  ${REGION_END}\n` +
        `in ${INDEX_PATH}. Refusing to append silently.`,
    );
  }
  if (endIdx < startIdx) {
    throw new Error(
      `geom-children index region markers out of order in ${INDEX_PATH}: ` +
        `end marker appears before start marker.`,
    );
  }
  const endLineEnd = endIdx + REGION_END.length;
  const afterEnd = source.slice(endLineEnd);
  const consumedEnd = afterEnd.startsWith("\n") ? endLineEnd + 1 : endLineEnd;
  return source.slice(0, startIdx) + region + "\n" + source.slice(consumedEnd);
}

/** Relative path of a shell file from repo root. */
export function shellRelPath(component: string): string {
  return `${GEOM_DIR}/${component}.svelte`;
}

function geomChildrenGroup(repoRoot: string) {
  const shellMembers = SHELL_MANIFEST.map((spec) => {
    const rel = shellRelPath(spec.component);
    return defineArtifact({
      path: join(repoRoot, rel),
      label: rel,
      regenerateWith: "geom:children:gen",
      build: () => renderShell(spec),
    });
  });
  const indexMember = defineArtifact({
    path: join(repoRoot, INDEX_PATH),
    label: INDEX_PATH,
    regenerateWith: "geom:children:gen",
    build: () => {
      const indexAbs = join(repoRoot, INDEX_PATH);
      return rewriteIndexRegion(readFileSync(indexAbs, "utf8"));
    },
  });
  return defineArtifactGroup({
    regenerateWith: "geom:children:gen",
    members: [...shellMembers, indexMember],
  });
}

if (import.meta.main) {
  const repoRoot = join(import.meta.dir, "..");
  const group = geomChildrenGroup(repoRoot);
  try {
    if (process.argv.includes("--check")) {
      await group.check();
      console.log(`geom children are current (${String(SHELL_MANIFEST.length)} shells).`);
    } else {
      await group.write();
      console.log(`geom children generated (${String(SHELL_MANIFEST.length)} shells).`);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
