/**
 * gen-builder-scales unit tests + staleness guard
 * (CI parity for `bun run builder:scales:check`).
 */
import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  BUILDER_SCALES_PATH,
  builderScaleHelpers,
  ledgerCamelHelpers,
  renderBuilderScalesSource,
  STYLE_ORDINAL_BUILDER_HELPERS,
} from "./gen-builder-scales.ts";

const repoRoot = join(import.meta.dir, "..");

describe("builder scale helper set", () => {
  it("includes every ledger camelCase helper", () => {
    const ledger = new Set(ledgerCamelHelpers());
    const builder = new Set(builderScaleHelpers());
    for (const h of ledger) {
      expect(builder.has(h), `missing builder helper ${h}`).toBe(true);
    }
    expect(ledger.size).toBeGreaterThan(90);
  });

  it("includes style ordinal aliases", () => {
    const builder = new Set(builderScaleHelpers());
    for (const h of STYLE_ORDINAL_BUILDER_HELPERS) {
      expect(builder.has(h), h).toBe(true);
    }
  });

  it("render emits every helper method and a generated header", () => {
    const helpers = builderScaleHelpers();
    const src = renderBuilderScalesSource(helpers);
    expect(src).toContain("AUTO-GENERATED by scripts/gen-builder-scales.ts");
    expect(src).toContain("export function WithBuilderScales");
    for (const h of helpers) {
      expect(src.includes(`${h}(...args: Parameters<typeof ${h}>)`), h).toBe(true);
      expect(src.includes(`return this.scales(${h}(...args))`), h).toBe(true);
    }
  });
});

describe("builder-scales.ts staleness", () => {
  it("committed file matches render (regenerate with bun run builder:scales:gen)", async () => {
    const { builderScalesArtifact } = await import("./gen-builder-scales.ts");
    // check() throws ArtifactError when STALE/MISSING
    await builderScalesArtifact(repoRoot).check();
    // Sanity: file exists and is non-empty
    const current = readFileSync(join(repoRoot, BUILDER_SCALES_PATH), "utf8");
    expect(current.length).toBeGreaterThan(500);
  });
});
