/**
 * gen-plot-validator — precompile the PlotSpecSchema TypeBox validator to a
 * standalone generated module, so `validate()` never pays the multi-second
 * runtime `Compile()` (module-load or first-call) cost.
 *
 * Usage:
 *   bun run validator:gen           # rewrite packages/spec/src/generated/plot-spec-validator.ts
 *   bun run validator:check         # exit 1 on drift
 */
import { createRequire } from "node:module";
import { join } from "node:path";

import { PlotSpecSchema } from "../packages/spec/src/schema.ts";

import { defineArtifact, formatGeneratedSource } from "./artifact.ts";

// typebox is a @ggsvelte/spec dependency, not a root one — resolve through
// the package so this script works regardless of hoisting. Typed locally so
// the scripts tsconfig never resolves typebox's declarations.
const specRequire = createRequire(join(import.meta.dir, "../packages/spec/package.json"));
const compileModule = specRequire("typebox/compile") as {
  Code(schema: unknown): { Code: string; External: { variables: RegExp[] } };
};
const Code = (schema: unknown): { Code: string; External: { variables: RegExp[] } } =>
  compileModule.Code(schema);
const { Settings } = specRequire("typebox/system") as {
  Settings: {
    Get(): { exactOptionalPropertyTypes?: boolean };
    Set(value: { exactOptionalPropertyTypes?: boolean }): void;
  };
};

const REL = "packages/spec/src/generated/plot-spec-validator.ts";

/**
 * The standalone module TypeBox emits, post-processed:
 * - externals (property-name/format regexes) inlined as literals — no
 *   SetExternal handshake at module load;
 * - the unused SetExternal export and unused typebox imports stripped;
 * - @ts-nocheck: the emit is untyped by construction.
 */
function buildValidatorSource(): string {
  const previousExactOptional = Settings.Get().exactOptionalPropertyTypes ?? false;
  Settings.Set({ exactOptionalPropertyTypes: true });
  try {
    const { Code: code, External } = Code(PlotSpecSchema);
    const variables = External.variables;
    const inline = `[${variables.map(String).join(", ")}]`;
    let body = code.replace("let External = []", `let External = ${inline}`);
    if (body === code) throw new Error("gen-plot-validator: externals marker not found");
    body = body.replace(/export function SetExternal[^\n]*\n\n/, "");
    for (const name of ["Hashing", "Format", "Guard"]) {
      if (!new RegExp(`\\b${name}\\.`).test(body)) {
        body = body.replace(new RegExp(`import \\{ ${name} \\} from "typebox/[a-z]+"\\n`), "");
      }
    }
    return `/* oxlint-disable -- generated validator emit */
/**
 * AUTO-GENERATED by scripts/gen-plot-validator.ts — do not edit by hand.
 * Regenerate: bun run validator:gen
 *
 * Standalone precompiled PlotSpecSchema validator (TypeBox Code() emit with
 * externals inlined). Semantics are pinned against a runtime-compiled
 * validator by packages/spec/tests/plot-spec-validator-generated.test.ts.
 */
// @ts-nocheck
${body}`;
  } finally {
    Settings.Set({ exactOptionalPropertyTypes: previousExactOptional });
  }
}

export function plotSpecValidatorArtifact(repoRoot: string) {
  return defineArtifact({
    path: join(repoRoot, REL),
    label: REL,
    regenerateWith: "validator:gen",
    build: () => formatGeneratedSource(join(repoRoot, REL), buildValidatorSource()),
  });
}

if (import.meta.main) {
  await plotSpecValidatorArtifact(join(import.meta.dir, "..")).cli();
}
