/**
 * Render the getting-started lesson's step charts to static SVG files.
 *
 * Eight live 838-point plots on one page cost roughly three seconds of
 * hydration each — measured on the built site — which is not a page anyone
 * should have to wait for. The step charts are illustrations of one delta, so
 * they ship as real library output rendered at build time; the inspect step
 * and the finished chart stay live, because interaction is the thing they are
 * there to demonstrate.
 *
 * This is the same shape as gen-gallery-previews: generate into
 * apps/docs/static, project an inventory module, and offer --check for CI.
 *
 *   bun scripts/gen-lesson-charts.ts          # write
 *   bun scripts/gen-lesson-charts.ts --check  # verify committed output
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { renderToSVGString } from "@ggsvelte/core";
import { format } from "oxfmt";

import { kyotoSakura } from "../packages/svelte/src/lib/data/index.js";
import { foldSakura, SAKURA_STEPS } from "./quickstart.js";

const ROOT = resolve(import.meta.dir, "..");
const OUTPUT_DIR = join(ROOT, "apps", "docs", "static", "lesson");
const PROJECTION = join(ROOT, "apps", "docs", "src", "lib", "generated", "lesson-charts.ts");

/**
 * Steps rendered live in the browser, by index into SAKURA_STEPS.
 *
 * None: the finished chart directly below the steps is live and full width,
 * which is where inspection is worth demonstrating. A second live copy of the
 * same 838 points bought nothing and cost another three seconds of hydration.
 */
export const LIVE_STEP_INDEXES: readonly number[] = [];

/** Nominal size; the SVG scales to its container via viewBox. */
export const LESSON_CHART_WIDTH = 660;
export const LESSON_CHART_HEIGHT = 400;

export interface LessonChartEntry {
  /** -1 is the first render, before any step. */
  step: number;
  filename: string;
}

export function lessonChartFilename(step: number): string {
  return step < 0 ? "first-render.svg" : `step-${String(step + 1)}.svg`;
}

/** Every chart the page shows statically, first render first. */
export function staticLessonSteps(): number[] {
  const steps = [-1];
  for (let index = 0; index < SAKURA_STEPS.length; index += 1) {
    if (!LIVE_STEP_INDEXES.includes(index)) steps.push(index);
  }
  return steps;
}

export function renderLessonChart(step: number): string {
  const rows = kyotoSakura.map((row) => ({ ...row }));
  // Rendered at the width the step gives them, which is wide enough for the
  // record callouts (the ladder in the component uses the same threshold).
  const { spec } = foldSakura(step + 1, rows);
  // renderToSVGString already emits xmlns and viewBox, which is what makes the
  // output valid as a standalone image.
  return `${renderToSVGString(spec, {
    width: LESSON_CHART_WIDTH,
    height: LESSON_CHART_HEIGHT,
  })}\n`;
}

async function projection(entries: readonly LessonChartEntry[]): Promise<string> {
  const result = await format(
    "lesson-charts.ts",
    `// Generated by scripts/gen-lesson-charts.ts. Do not edit.
// Static renders of the getting-started lesson steps; regenerate with
// \`bun run lesson:charts:gen\`.
export interface LessonChartEntry {
  step: number;
  filename: string;
}

export const LESSON_CHART_WIDTH = ${String(LESSON_CHART_WIDTH)};
export const LESSON_CHART_HEIGHT = ${String(LESSON_CHART_HEIGHT)};

export const LESSON_CHARTS: readonly LessonChartEntry[] = ${JSON.stringify(entries)};

/** Step indexes rendered live in the browser (interaction is the point). */
export const LIVE_STEP_INDEXES: readonly number[] = ${JSON.stringify([...LIVE_STEP_INDEXES])};
`,
  );
  if (result.errors.length > 0) {
    throw new Error(
      `Could not format lesson-chart projection: ${result.errors[0]?.message ?? "?"}`,
    );
  }
  return result.code;
}

export async function generateLessonCharts(options: { check?: boolean } = {}): Promise<{
  entries: LessonChartEntry[];
  stale: string[];
}> {
  const steps = staticLessonSteps();
  const entries: LessonChartEntry[] = steps.map((step) => ({
    step,
    filename: lessonChartFilename(step),
  }));
  const stale: string[] = [];

  if (options.check !== true) {
    rmSync(OUTPUT_DIR, { recursive: true, force: true });
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  for (const entry of entries) {
    const path = join(OUTPUT_DIR, entry.filename);
    const svg = renderLessonChart(entry.step);
    if (options.check === true) {
      let current: string | null = null;
      try {
        current = readFileSync(path, "utf8");
      } catch {
        current = null;
      }
      if (current !== svg) stale.push(entry.filename);
    } else {
      writeFileSync(path, svg);
    }
  }

  const projected = await projection(entries);
  if (options.check === true) {
    let current: string | null = null;
    try {
      current = readFileSync(PROJECTION, "utf8");
    } catch {
      current = null;
    }
    if (current !== projected) stale.push("lesson-charts.ts");
    // An extra file left behind would still be served, so it counts as stale.
    let present: string[] = [];
    try {
      present = readdirSync(OUTPUT_DIR);
    } catch {
      present = [];
    }
    const expected = new Set(entries.map((entry) => entry.filename));
    for (const file of present) if (!expected.has(file)) stale.push(file);
  } else {
    writeFileSync(PROJECTION, projected);
  }

  return { entries, stale };
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const { entries, stale } = await generateLessonCharts({ check });
  if (check) {
    if (stale.length > 0) {
      console.error(`lesson charts are stale: ${stale.join(", ")}`);
      console.error("run `bun run lesson:charts:gen`");
      process.exit(1);
    }
    console.log("lesson charts are current");
  } else {
    console.log(`wrote ${String(entries.length)} lesson charts to ${OUTPUT_DIR}`);
  }
}
