import { describe, expect, it } from "bun:test";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const GUARD = join(ROOT, "scripts", "guards", "max-loc.sh");

const overLimit = "x\n".repeat(501);
const atLimit = "x\n".repeat(500);
const unterminated501 = "x\n".repeat(500) + "x";

interface Repo {
  dir: string;
  write(path: string, content: string): void;
  writeList(content: string): string;
  guard(args: string[]): { status: number; stderr: string };
  commit(message: string): void;
}

function makeRepo(): Repo {
  const dir = mkdtempSync(join(tmpdir(), "max-loc-test-"));
  spawnSync("git", ["init", "-q"], { cwd: dir });
  const listPath = join(dir, "exclusions.txt");
  return {
    dir,
    write(path, content) {
      const full = join(dir, path);
      const parent = full.slice(0, full.lastIndexOf("/"));
      spawnSync("mkdir", ["-p", parent]);
      writeFileSync(full, content);
    },
    writeList(content) {
      writeFileSync(listPath, content);
      return listPath;
    },
    guard(args) {
      const res = spawnSync("bash", [GUARD, ...args], {
        cwd: dir,
        // Strip CI anchor vars: the temp repo has no base ref to resolve, and
        // only the dedicated GITHUB_BASE_REF test may set it.
        env: { ...process.env, GITHUB_BASE_REF: undefined, MAX_LOC_EXCLUSIONS: listPath },
      });
      return {
        status: res.status ?? 1,
        stderr: new TextDecoder().decode(res.stderr),
      };
    },
    commit(message) {
      spawnSync("git", ["add", "-A"], { cwd: dir });
      spawnSync("git", ["-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", message], {
        cwd: dir,
      });
    },
  };
}

describe("max-loc guard", () => {
  it("accepts a file at exactly 500 lines and rejects 501", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("a.ts", atLimit);
    repo.write("b.ts", overLimit);
    expect(repo.guard(["a.ts"]).status).toBe(0);
    const res = repo.guard(["b.ts"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("b.ts: 501 lines");
    rmSync(repo.dir, { recursive: true, force: true });
  });

  it("counts a missing final newline (grep -c '', not wc -l)", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("a.ts", unterminated501);
    const res = repo.guard(["a.ts"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("a.ts: 501 lines");
    rmSync(repo.dir, { recursive: true });
  });

  it("auto-exempts generated files via a DO NOT EDIT header", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("gen.ts", "// Generated by tool — DO NOT EDIT.\n" + overLimit);
    expect(repo.guard(["gen.ts"]).status).toBe(0);
    rmSync(repo.dir, { recursive: true });
  });

  it("exempts generated files with the marker split across header lines", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("gen.ts", "// Generated by tool.\n// DO NOT EDIT.\n" + overLimit);
    expect(repo.guard(["gen.ts"]).status).toBe(0);
    rmSync(repo.dir, { recursive: true });
  });

  it("flags a generated file that is still listed as stale", () => {
    const repo = makeRepo();
    repo.writeList("gen.ts 501 # oops, generated files must not be listed\n");
    repo.write("gen.ts", "// Generated by tool — DO NOT EDIT.\n" + overLimit);
    const res = repo.guard(["gen.ts"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("stale");
    rmSync(repo.dir, { recursive: true });
  });

  it("audits pinned files when only the exclusion list changes", () => {
    const repo = makeRepo();
    repo.writeList("legacy.ts 501 # legacy\n");
    repo.write("legacy.ts", overLimit);
    repo.commit("baseline");
    repo.writeList("");
    const res = repo.guard([join(repo.dir, "exclusions.txt")]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("legacy.ts: 501 lines");
    rmSync(repo.dir, { recursive: true });
  });

  it("does not exempt a DO NOT EDIT mention without a generator marker", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("hand.ts", "// see DO NOT EDIT policy doc\n" + overLimit);
    expect(repo.guard(["hand.ts"]).status).toBe(1);
    rmSync(repo.dir, { recursive: true });
  });

  it("accepts a listed file at its baseline and enforces the ratchet", () => {
    const repo = makeRepo();
    repo.writeList("legacy.ts 501 # pending refactor slice\n");
    repo.write("legacy.ts", overLimit);
    expect(repo.guard(["legacy.ts"]).status).toBe(0);

    repo.write("legacy.ts", "y\n".repeat(502));
    const grown = repo.guard(["legacy.ts"]);
    expect(grown.status).toBe(1);
    expect(grown.stderr).toContain("grew past");
    rmSync(repo.dir, { recursive: true });
  });

  it("flags a listed file that shrank under the limit as stale", () => {
    const repo = makeRepo();
    repo.writeList("shrunk.ts 600 # legacy\n");
    repo.write("shrunk.ts", atLimit);
    const res = repo.guard(["shrunk.ts"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("stale");
    rmSync(repo.dir, { recursive: true });
  });

  it("flags a listed file deleted from the tree as stale", () => {
    const repo = makeRepo();
    repo.writeList("gone.ts 900 # legacy\n");
    const res = repo.guard(["gone.ts"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("stale");
    rmSync(repo.dir, { recursive: true });
  });

  it("tolerates comments and blank lines in the exclusion list", () => {
    const repo = makeRepo();
    repo.writeList("# header comment\n\nlegacy.ts 501 # reason here\n\n# tail\n");
    repo.write("legacy.ts", overLimit);
    expect(repo.guard(["legacy.ts"]).status).toBe(0);
    rmSync(repo.dir, { recursive: true });
  });

  it("rejects malformed and duplicate exclusion entries", () => {
    const repo = makeRepo();
    repo.writeList("no-baseline.ts # oops\n");
    expect(repo.guard(["x.ts"]).status).toBe(1);
    expect(repo.guard(["x.ts"]).stderr).toContain("malformed");

    const repo2 = makeRepo();
    repo2.writeList("dup.ts 501 # a\ndup.ts 502 # b\n");
    expect(repo2.guard(["x.ts"]).status).toBe(1);
    expect(repo2.guard(["x.ts"]).stderr).toContain("duplicate");
    rmSync(repo.dir, { recursive: true });
    rmSync(repo2.dir, { recursive: true });
  });

  it("fails closed when the exclusion list is missing", () => {
    const repo = makeRepo();
    spawnSync("rm", ["-f", join(repo.dir, "exclusions.txt")]);
    repo.write("a.ts", overLimit);
    const res = repo.guard(["a.ts"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("missing");
    rmSync(repo.dir, { recursive: true });
  });

  it("ignores non-code extensions and spikes/", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("readme.md", overLimit);
    repo.write("spikes/lab/main.ts", overLimit);
    expect(repo.guard(["readme.md", "spikes/lab/main.ts"]).status).toBe(0);
    rmSync(repo.dir, { recursive: true });
  });

  it("--all audits tracked files via git ls-files", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("src/big.ts", overLimit);
    repo.write("src/ok.ts", atLimit);
    spawnSync("git", ["add", "src"], { cwd: repo.dir });
    const res = repo.guard(["--all"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toContain("src/big.ts: 501 lines");
    expect(res.stderr).not.toContain("src/ok.ts");
    rmSync(repo.dir, { recursive: true });
  });

  it("matches the shipped exclusion list against the real tree", () => {
    const res = spawnSync("bash", [GUARD, "--all"], {
      cwd: ROOT,
      env: {
        ...process.env,
        GITHUB_BASE_REF: undefined,
        MAX_LOC_EXCLUSIONS: join(ROOT, "scripts", "guards", "max-loc-exclusions.txt"),
      },
    });
    expect(res.status).toBe(0);
  });

  it("--all excludes tracked spikes/ files", () => {
    const repo = makeRepo();
    repo.writeList("");
    repo.write("spikes/lab/big.ts", overLimit);
    repo.guard(["--all"]);
    expect(repo.guard(["--all"]).status).toBe(0);
    rmSync(repo.dir, { recursive: true });
  });

  it("rejects raised baselines and new entries vs HEAD", () => {
    const repo = makeRepo();
    repo.writeList("legacy.ts 501 # legacy\n");
    repo.write("legacy.ts", overLimit);
    repo.write("other.ts", overLimit);
    repo.commit("baseline");

    repo.write("legacy.ts", "y\n".repeat(502));
    repo.writeList("legacy.ts 502 # raised\n");
    const raised = repo.guard(["legacy.ts", join(repo.dir, "exclusions.txt")]);
    expect(raised.status).toBe(1);
    expect(raised.stderr).toContain("baseline raised 501 -> 502");

    repo.writeList("legacy.ts 501 # legacy\nother.ts 501 # new\n");
    const added = repo.guard(["other.ts", join(repo.dir, "exclusions.txt")]);
    expect(added.status).toBe(1);
    expect(added.stderr).toContain("NEW exclusion entry");
    rmSync(repo.dir, { recursive: true });
  });

  it("accepts pruning an entry after the file shrank", () => {
    const repo = makeRepo();
    repo.writeList("legacy.ts 501 # legacy\n");
    repo.write("legacy.ts", overLimit);
    repo.commit("baseline");

    repo.write("legacy.ts", atLimit);
    repo.writeList("");
    expect(repo.guard(["legacy.ts", join(repo.dir, "exclusions.txt")]).status).toBe(0);
    rmSync(repo.dir, { recursive: true });
  });

  it("anchors the ratchet to the PR base in CI (GITHUB_BASE_REF)", () => {
    const repo = makeRepo();
    repo.writeList("legacy.ts 501 # legacy\n");
    repo.write("legacy.ts", overLimit);
    repo.commit("base");
    spawnSync("git", ["update-ref", "refs/remotes/origin/main", "HEAD"], { cwd: repo.dir });
    spawnSync("git", ["checkout", "-qb", "pr"], { cwd: repo.dir });
    repo.write("legacy.ts", "y\n".repeat(502));
    repo.writeList("legacy.ts 502 # raised\n");
    const res = spawnSync("bash", [GUARD, "legacy.ts"], {
      cwd: repo.dir,
      env: {
        ...process.env,
        MAX_LOC_EXCLUSIONS: join(repo.dir, "exclusions.txt"),
        GITHUB_BASE_REF: "main",
      },
    });
    expect(res.status).toBe(1);
    expect(new TextDecoder().decode(res.stderr)).toContain("baseline raised 501 -> 502");
    rmSync(repo.dir, { recursive: true });
  });

  it("guards run when only the exclusion list changes (hook files pattern)", () => {
    const config = readFileSync(join(ROOT, ".pre-commit-config.yaml"), "utf8");
    const hook = config.slice(config.indexOf("id: max-loc"));
    expect(hook).toMatch(/max-loc-exclusions\.txt/);
  });
});
