/**
 * Comparison-table version lockstep (README + docs homepage).
 *
 * Package manifests are the version source of truth. The "Why ggsvelte?"
 * tables cite that version; after every Version Packages PR they must match
 * the just-bumped package.json, not a hand-edited leftover.
 */
import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  readLockstepVersion,
  syncBenchmarkGgsvelteVersion,
  syncReadmeApiStability,
} from "./sync-comparison-versions.ts";

const ROOT = join(import.meta.dir, "..");

const SAMPLE_README = `# ggsvelte

## Why ggsvelte?

| Capability                                 | ggsvelte  | SveltePlot           | LayerCake            |
| ------------------------------------------ | --------- | -------------------- | -------------------- |
| **Bundle size** (min+gzip, 1k scatter app) | ⚠️ 138 KB | ✅ 109 KB            | ✅ 41 KB             |
| **API stability**                          | ⚠️ v0.30  | ⚠️ v0.14             | ✅ v10               |
| **Headless server-side SVG** (no DOM)      | ✅        | ❌ empty shell       | ⚠️ opt-in \`ssr\` flag |
`;

const SAMPLE_PROJECTION = `// Generated by bun scripts/gen-benchmark-charts.ts — do not edit.

export const BENCHMARK_VERSIONS = {
  ggsvelte: "0.31.2",
  svelteplot: "0.14.2",
  layercake: "10.0.3",
} as const;
`;

describe("syncReadmeApiStability", () => {
  it("replaces only the ggsvelte API-stability cell with the full released version", () => {
    const out = syncReadmeApiStability(SAMPLE_README, "0.32.0");
    // Preserve trailing padding before the next column pipe.
    expect(out).toContain(
      "| **API stability**                          | ⚠️ v0.32.0  | ⚠️ v0.14             | ✅ v10               |",
    );
    // Peer cells and other rows are untouched.
    expect(out).toContain(
      "| **Bundle size** (min+gzip, 1k scatter app) | ⚠️ 138 KB | ✅ 109 KB            | ✅ 41 KB             |",
    );
    expect(out).toContain("⚠️ v0.14");
    expect(out).toContain("✅ v10");
    expect(out).not.toContain("⚠️ v0.30");
  });

  it("is a no-op when the README already cites the given version", () => {
    const once = syncReadmeApiStability(SAMPLE_README, "0.32.0");
    expect(syncReadmeApiStability(once, "0.32.0")).toBe(once);
  });

  it("throws when the API stability row is missing or malformed", () => {
    expect(() => syncReadmeApiStability("# bare", "0.32.0")).toThrow(/API stability/);
    expect(() => syncReadmeApiStability(SAMPLE_README, "not-a-version")).toThrow(/semver/);
  });
});

describe("syncBenchmarkGgsvelteVersion", () => {
  it("rewrites only BENCHMARK_VERSIONS.ggsvelte", () => {
    const out = syncBenchmarkGgsvelteVersion(SAMPLE_PROJECTION, "0.32.0");
    expect(out).toContain('ggsvelte: "0.32.0"');
    expect(out).toContain('svelteplot: "0.14.2"');
    expect(out).toContain('layercake: "10.0.3"');
    expect(out).not.toContain('ggsvelte: "0.31.2"');
  });

  it("is a no-op when the projection already matches", () => {
    const once = syncBenchmarkGgsvelteVersion(SAMPLE_PROJECTION, "0.32.0");
    expect(syncBenchmarkGgsvelteVersion(once, "0.32.0")).toBe(once);
  });

  it("throws when the ggsvelte version field is missing", () => {
    expect(() => syncBenchmarkGgsvelteVersion("export const X = 1;", "0.32.0")).toThrow(
      /BENCHMARK_VERSIONS\.ggsvelte/,
    );
  });
});

describe("live comparison tables match the published lockstep version", () => {
  const version = readLockstepVersion(ROOT);

  it("reads a real lockstep semver from packages/svelte", () => {
    expect(version).toMatch(/^\d+\.\d+\.\d+$/);
    // Lockstep: every published package shares this version.
    for (const pkg of ["spec", "core", "svelte", "cli", "skill"] as const) {
      const manifest = JSON.parse(
        readFileSync(join(ROOT, "packages", pkg, "package.json"), "utf8"),
      ) as { version: string };
      expect(manifest.version, `@ggsvelte/${pkg}`).toBe(version);
    }
  });

  it("README API-stability cell cites that version", () => {
    const readme = readFileSync(join(ROOT, "README.md"), "utf8");
    expect(syncReadmeApiStability(readme, version)).toBe(readme);
    expect(readme).toContain(`⚠️ v${version}`);
  });

  it("docs homepage BENCHMARK_VERSIONS.ggsvelte cites that version", () => {
    const proj = readFileSync(
      join(ROOT, "apps/docs/src/lib/generated/benchmark-charts.ts"),
      "utf8",
    );
    expect(syncBenchmarkGgsvelteVersion(proj, version)).toBe(proj);
    expect(proj).toContain(`ggsvelte: "${version}"`);
  });
});

describe("release wiring auto-bumps comparison tables on Version Packages", () => {
  it("root package.json version script runs changeset version then the sync", () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as {
      scripts: Record<string, string>;
    };
    // changesets/action `version:` replaces `changeset version`; the custom
    // script must call it, then rewrite README + docs projection.
    expect(pkg.scripts["version"]).toMatch(/changeset version/);
    expect(pkg.scripts["version"]).toContain("sync-comparison-versions");
    expect(pkg.scripts["comparison:versions:check"]).toContain(
      "sync-comparison-versions.ts --check",
    );
    // Drift must fail the same check chain CI unit already runs.
    expect(pkg.scripts["check"]).toContain("comparison:versions:check");
  });

  it("release.yml passes the version script to changesets/action", () => {
    const yml = readFileSync(join(ROOT, ".github/workflows/release.yml"), "utf8");
    const stepAt = yml.indexOf("changesets — open/update Version Packages PR");
    expect(stepAt).toBeGreaterThan(-1);
    const nextStep = yml.indexOf("\n      - ", stepAt + 1);
    const step = nextStep === -1 ? yml.slice(stepAt) : yml.slice(stepAt, nextStep);
    expect(step).toContain("changesets/action@");
    // Custom version input — not the default bare `changeset version`.
    expect(step).toMatch(/version:\s*bun run version/);
  });
});
