import { describe, expect, it } from "bun:test";

import {
  CATEGORICAL_PALETTES,
  THEME_OPTIONS,
  VIRIDIS_COLORS,
} from "../apps/docs/src/lib/catalog/themes.ts";
import { colorBehaviorEvidence } from "./color-evidence.ts";
import {
  MONTH_BREAKS,
  RASTER_Z_DOMAIN,
  THEME_SPECIMENS,
} from "../apps/docs/src/lib/theme-specimens/catalog.ts";
import { TEMPERATURES_CHART } from "../apps/docs/src/lib/theme-specimens/temperatures-chart.ts";

describe("themes catalog", () => {
  it("projects every public theme and categorical palette without docs-owned colors", () => {
    // grey/gray alias ggplot2 (#824) — one picker row (ggplot2), not three.
    expect(THEME_OPTIONS.map(({ name, scheme }) => ({ name, scheme }))).toEqual([
      { name: "default", scheme: "observable10" },
      { name: "light", scheme: "tableau10" },
      { name: "dark", scheme: "flexoki" },
      { name: "minimal", scheme: "colorblind" },
      { name: "ggplot2", scheme: "observable10" },
      { name: "classic", scheme: "tableau10" },
      { name: "bw", scheme: "tableau10" },
      { name: "hrbr", scheme: "ipsum" },
      { name: "few", scheme: "few" },
      { name: "clean", scheme: "flexoki" },
      { name: "fivethirtyeight", scheme: "fivethirtyeight" },
      { name: "economist", scheme: "economist" },
      { name: "tufte", scheme: "colorblind" },
      { name: "linedraw", scheme: "colorblind" },
      { name: "void", scheme: "colorblind" },
      { name: "solarized", scheme: "solarized" },
      { name: "solarizeddark", scheme: "solarized" },
      { name: "economist_white", scheme: "economist" },
      { name: "solarized_2", scheme: "tableau10" },
      { name: "solarized_2dark", scheme: "tableau10" },
      { name: "wsj", scheme: "wsj" },
      { name: "gdocs", scheme: "gdocs" },
      { name: "hc", scheme: "hc" },
      { name: "hcdark", scheme: "hc_dark" },
      { name: "pander", scheme: "pander" },
      { name: "test", scheme: "colorblind" },
    ]);
    expect(THEME_OPTIONS.map((theme) => theme.name)).not.toContain("grey");
    expect(THEME_OPTIONS.map((theme) => theme.name)).not.toContain("gray");

    expect(CATEGORICAL_PALETTES).toEqual([
      {
        name: "observable10",
        label: "Observable 10",
        capacity: 10,
        colors: [
          "#4269d0",
          "#efb118",
          "#ff725c",
          "#6cc5b0",
          "#3ca951",
          "#ff8ab7",
          "#a463f2",
          "#97bbf5",
          "#9c6b4e",
          "#9498a0",
        ],
      },
      {
        name: "ipsum",
        label: "Ipsum",
        capacity: 9,
        colors: [
          "#d18975",
          "#8fd175",
          "#3f2d54",
          "#75b8d1",
          "#2d543d",
          "#c9d175",
          "#d1ab75",
          "#d175b8",
          "#758bd1",
        ],
      },
      {
        name: "flexoki",
        label: "Flexoki",
        capacity: 8,
        colors: [
          "#D14D41",
          "#DA702C",
          "#D0A215",
          "#879A39",
          "#3AA99F",
          "#4385BE",
          "#8B7EC8",
          "#CE5D97",
        ],
      },
      {
        name: "tableau10",
        label: "Tableau 10",
        capacity: 10,
        colors: [
          "#4E79A7",
          "#F28E2B",
          "#E15759",
          "#76B7B2",
          "#59A14F",
          "#EDC948",
          "#B07AA1",
          "#FF9DA7",
          "#9C755F",
          "#BAB0AC",
        ],
      },
      {
        name: "colorblind",
        label: "Colorblind",
        capacity: 8,
        colors: [
          "#000000",
          "#E69F00",
          "#56B4E9",
          "#009E73",
          "#F0E442",
          "#0072B2",
          "#D55E00",
          "#CC79A7",
        ],
      },
      {
        name: "economist",
        label: "Economist",
        capacity: 9,
        colors: [
          "#6794a7",
          "#014d64",
          "#01a2d9",
          "#7ad2f6",
          "#00887d",
          "#76c0c1",
          "#7c260b",
          "#ee8f71",
          "#adadad",
        ],
      },
      {
        name: "solarized",
        label: "Solarized",
        capacity: 8,
        colors: [
          "#268bd2",
          "#b58900",
          "#cb4b16",
          "#dc322f",
          "#d33682",
          "#6c71c4",
          "#2aa198",
          "#859900",
        ],
      },
      {
        name: "few",
        label: "Few",
        capacity: 8,
        colors: [
          "#5DA5DA",
          "#FAA43A",
          "#60BD68",
          "#F17CB0",
          "#B2912F",
          "#B276B2",
          "#DECF3F",
          "#F15854",
        ],
      },
      {
        name: "few_light",
        label: "Few Light",
        capacity: 8,
        colors: [
          "#88BDE6",
          "#FBB258",
          "#90CD97",
          "#F6AAC9",
          "#BFA554",
          "#BC99C7",
          "#EDDD46",
          "#F07E6E",
        ],
      },
      {
        name: "few_dark",
        label: "Few Dark",
        capacity: 8,
        colors: [
          "#265DAB",
          "#DF5C24",
          "#059748",
          "#E5126F",
          "#9D722A",
          "#7B3A96",
          "#C7B42E",
          "#CB2027",
        ],
      },
      {
        name: "fivethirtyeight",
        label: "FiveThirtyEight",
        capacity: 3,
        colors: ["#008FD5", "#FF2700", "#77AB43"],
      },
      {
        name: "ptol",
        label: "Paul Tol",
        capacity: 12,
        colors: [
          "#332288",
          "#6699CC",
          "#88CCEE",
          "#44AA99",
          "#117733",
          "#999933",
          "#DDCC77",
          "#661100",
          "#CC6677",
          "#AA4466",
          "#882255",
          "#AA4499",
        ],
      },
      {
        name: "canva",
        label: "Canva",
        capacity: 4,
        colors: ["#f98866", "#ff420e", "#80bd9e", "#89da59"],
      },
      {
        name: "wsj",
        label: "WSJ",
        capacity: 6,
        colors: ["#c72e29", "#016392", "#be9c2e", "#098154", "#fb832d", "#000000"],
      },
      {
        name: "wsj_rgby",
        label: "WSJ R/G/B/Y",
        capacity: 4,
        colors: ["#d3ba68", "#d5695d", "#5d8ca8", "#65a479"],
      },
      {
        name: "wsj_red_green",
        label: "WSJ Red/Green",
        capacity: 2,
        colors: ["#088158", "#ba2f2a"],
      },
      {
        name: "wsj_black_green",
        label: "WSJ Black/Green",
        capacity: 4,
        colors: ["#000000", "#595959", "#59a77f", "#008856"],
      },
      {
        name: "wsj_dem_rep",
        label: "WSJ Dem/Rep",
        capacity: 3,
        colors: ["#006a8e", "#b1283a", "#a8a6a7"],
      },
      {
        name: "tableau20",
        label: "Tableau 20",
        capacity: 20,
        colors: [
          "#4E79A7",
          "#A0CBE8",
          "#F28E2B",
          "#FFBE7D",
          "#59A14F",
          "#8CD17D",
          "#B6992D",
          "#F1CE63",
          "#499894",
          "#86BCB6",
          "#E15759",
          "#FF9D9A",
          "#79706E",
          "#BAB0AC",
          "#D37295",
          "#FABFD2",
          "#B07AA1",
          "#D4A6C8",
          "#9D7660",
          "#D7B5A6",
        ],
      },
      {
        name: "tableau_colorblind",
        label: "Tableau Color Blind",
        capacity: 10,
        colors: [
          "#1170aa",
          "#fc7d0b",
          "#a3acb9",
          "#57606c",
          "#5fa2ce",
          "#c85200",
          "#7b848f",
          "#a3cce9",
          "#ffbc79",
          "#c8d0d9",
        ],
      },
      {
        name: "tableau_seattle_grays",
        label: "Seattle Grays",
        capacity: 5,
        colors: ["#767f8b", "#b3b7b8", "#5c6068", "#d3d3d3", "#989ca3"],
      },
      {
        name: "tableau_traffic",
        label: "Traffic",
        capacity: 9,
        colors: [
          "#b60a1c",
          "#e39802",
          "#309143",
          "#e03531",
          "#f0bd27",
          "#51b364",
          "#ff684c",
          "#ffda66",
          "#8ace7e",
        ],
      },
      {
        name: "tableau_miller_stone",
        label: "Miller Stone",
        capacity: 11,
        colors: [
          "#4f6980",
          "#849db1",
          "#a2ceaa",
          "#638b66",
          "#bfbb60",
          "#f47942",
          "#fbb04e",
          "#b66353",
          "#d7ce9f",
          "#b9aa97",
          "#7e756d",
        ],
      },
      {
        name: "tableau_superfishel_stone",
        label: "Superfishel Stone",
        capacity: 10,
        colors: [
          "#6388b4",
          "#ffae34",
          "#ef6f6a",
          "#8cc2ca",
          "#55ad89",
          "#c3bc3f",
          "#bb7693",
          "#baa094",
          "#a9b5ae",
          "#767676",
        ],
      },
      {
        name: "tableau_nuriel_stone",
        label: "Nuriel Stone",
        capacity: 9,
        colors: [
          "#8175aa",
          "#6fb899",
          "#31a1b3",
          "#ccb22b",
          "#a39fc9",
          "#94d0c0",
          "#959c9e",
          "#027b8e",
          "#9f8f12",
        ],
      },
      {
        name: "tableau_jewel_bright",
        label: "Jewel Bright",
        capacity: 9,
        colors: [
          "#eb1e2c",
          "#fd6f30",
          "#f9a729",
          "#f9d23c",
          "#5fbb68",
          "#64cdcc",
          "#91dcea",
          "#a4a4d5",
          "#bbc9e5",
        ],
      },
      {
        name: "tableau_summer",
        label: "Summer",
        capacity: 8,
        colors: [
          "#bfb202",
          "#b9ca5d",
          "#cf3e53",
          "#f1788d",
          "#00a2b3",
          "#97cfd0",
          "#f3a546",
          "#f7c480",
        ],
      },
      {
        name: "tableau_winter",
        label: "Winter",
        capacity: 10,
        colors: [
          "#90728f",
          "#b9a0b4",
          "#9d983d",
          "#cecb76",
          "#e15759",
          "#ff9888",
          "#6b6b6b",
          "#bab2ae",
          "#aa8780",
          "#dab6af",
        ],
      },
      {
        name: "tableau_green_orange_teal",
        label: "Green/Orange/Teal",
        capacity: 12,
        colors: [
          "#4e9f50",
          "#87d180",
          "#ef8a0c",
          "#fcc66d",
          "#3ca8bc",
          "#98d9e4",
          "#94a323",
          "#c3ce3d",
          "#a08400",
          "#f7d42a",
          "#26897e",
          "#8dbfa8",
        ],
      },
      {
        name: "tableau_red_blue_brown",
        label: "Red/Blue/Brown",
        capacity: 12,
        colors: [
          "#466f9d",
          "#91b3d7",
          "#ed444a",
          "#feb5a2",
          "#9d7660",
          "#d7b5a6",
          "#3896c4",
          "#a0d4ee",
          "#ba7e45",
          "#39b87f",
          "#c8133b",
          "#ea8783",
        ],
      },
      {
        name: "tableau_purple_pink_gray",
        label: "Purple/Pink/Gray",
        capacity: 12,
        colors: [
          "#8074a8",
          "#c6c1f0",
          "#c46487",
          "#ffbed1",
          "#9c9290",
          "#c5bfbe",
          "#9b93c9",
          "#ddb5d5",
          "#7c7270",
          "#f498b6",
          "#b173a0",
          "#c799bc",
        ],
      },
      {
        name: "tableau_hue_circle",
        label: "Hue Circle",
        capacity: 19,
        colors: [
          "#1ba3c6",
          "#2cb5c0",
          "#30bcad",
          "#21B087",
          "#33a65c",
          "#57a337",
          "#a2b627",
          "#d5bb21",
          "#f8b620",
          "#f89217",
          "#f06719",
          "#e03426",
          "#f64971",
          "#fc719e",
          "#eb73b3",
          "#ce69be",
          "#a26dc2",
          "#7873c0",
          "#4f7cba",
        ],
      },
      {
        name: "gdocs",
        label: "Google Docs",
        capacity: 24,
        colors: [
          "#4285f4",
          "#ea4335",
          "#fbbc04",
          "#34a853",
          "#ff6d01",
          "#46bdc6",
          "#7baaf7",
          "#f07b72",
          "#fcd04f",
          "#71c287",
          "#ff994d",
          "#ff994d",
          "#b3cefb",
          "#f7b4ae",
          "#fde49b",
          "#aedcba",
          "#ffc599",
          "#c9e4e7",
          "#ecf3fe",
          "#fdeceb",
          "#fff8e6",
          "#ebf6ee",
          "#fff0e6",
          "#edf8f9",
        ],
      },
      {
        name: "hc",
        label: "Highcharts",
        capacity: 10,
        colors: [
          "#7cb5ec",
          "#434348",
          "#90ed7d",
          "#f7a35c",
          "#8085e9",
          "#f15c80",
          "#e4d354",
          "#8085e8",
          "#8d4653",
          "#91e8e1",
        ],
      },
      {
        name: "hc_dark",
        label: "Highcharts Dark",
        capacity: 11,
        colors: [
          "#2b908f",
          "#90ee7e",
          "#f45b5b",
          "#7798BF",
          "#aaeeee",
          "#ff0066",
          "#eeaaee",
          "#55BF3B",
          "#DF5353",
          "#7798BF",
          "#aaeeee",
        ],
      },
      {
        name: "pander",
        label: "Pander",
        capacity: 8,
        colors: [
          "#56B4E9",
          "#009E73",
          "#F0E442",
          "#0072B2",
          "#D55E00",
          "#CC79A7",
          "#999999",
          "#E69F00",
        ],
      },
      {
        name: "Set1",
        label: "Set1",
        capacity: 9,
        colors: [
          "#e41a1c",
          "#377eb8",
          "#4daf4a",
          "#984ea3",
          "#ff7f00",
          "#ffff33",
          "#a65628",
          "#f781bf",
          "#999999",
        ],
      },
      {
        name: "Set2",
        label: "Set2",
        capacity: 8,
        colors: [
          "#66c2a5",
          "#fc8d62",
          "#8da0cb",
          "#e78ac3",
          "#a6d854",
          "#ffd92f",
          "#e5c494",
          "#b3b3b3",
        ],
      },
      {
        name: "Set3",
        label: "Set3",
        capacity: 12,
        colors: [
          "#8dd3c7",
          "#ffffb3",
          "#bebada",
          "#fb8072",
          "#80b1d3",
          "#fdb462",
          "#b3de69",
          "#fccde5",
          "#d9d9d9",
          "#bc80bd",
          "#ccebc5",
          "#ffed6f",
        ],
      },
      {
        name: "Dark2",
        label: "Dark2",
        capacity: 8,
        colors: [
          "#1b9e77",
          "#d95f02",
          "#7570b3",
          "#e7298a",
          "#66a61e",
          "#e6ab02",
          "#a6761d",
          "#666666",
        ],
      },
      {
        name: "Paired",
        label: "Paired",
        capacity: 12,
        colors: [
          "#a6cee3",
          "#1f78b4",
          "#b2df8a",
          "#33a02c",
          "#fb9a99",
          "#e31a1c",
          "#fdbf6f",
          "#ff7f00",
          "#cab2d6",
          "#6a3d9a",
          "#ffff99",
          "#b15928",
        ],
      },
      {
        name: "Accent",
        label: "Accent",
        capacity: 8,
        colors: [
          "#7fc97f",
          "#beaed4",
          "#fdc086",
          "#ffff99",
          "#386cb0",
          "#f0027f",
          "#bf5b17",
          "#666666",
        ],
      },
      {
        name: "hue",
        label: "Hue",
        capacity: 10,
        colors: [
          "#ff794d",
          "#ffe44d",
          "#afff4d",
          "#4dff55",
          "#4dffc1",
          "#4dd2ff",
          "#4d67ff",
          "#9d4dff",
          "#ff4df6",
          "#ff4d8b",
        ],
      },
      {
        name: "grey",
        label: "Grey",
        capacity: 10,
        colors: [
          "#333333",
          "#444444",
          "#555555",
          "#666666",
          "#777777",
          "#888888",
          "#999999",
          "#aaaaaa",
          "#bbbbbb",
          "#cccccc",
        ],
      },
      {
        name: "gray",
        label: "Gray",
        capacity: 10,
        colors: [
          "#333333",
          "#444444",
          "#555555",
          "#666666",
          "#777777",
          "#888888",
          "#999999",
          "#aaaaaa",
          "#bbbbbb",
          "#cccccc",
        ],
      },
    ]);

    expect(VIRIDIS_COLORS).toEqual([
      "#440154",
      "#482878",
      "#3e4989",
      "#31688e",
      "#26828e",
      "#1f9e89",
      "#35b779",
      "#6ece58",
      "#b5de2b",
      "#fde725",
    ]);
  });

  it("lists every non-alias theme as a full-width specimen with a real chart kind", () => {
    // THEME_OPTIONS already drops grey/gray aliases (#824) — specimens match 1:1.
    expect(THEME_SPECIMENS.map((specimen) => specimen.name)).toEqual(
      THEME_OPTIONS.map((theme) => theme.name),
    );
    for (const specimen of THEME_SPECIMENS) {
      expect(specimen.caption.length).toBeGreaterThan(12);
      expect(specimen.caption.length).toBeLessThanOrEqual(96);
      expect(specimen.scheme).toBe(
        THEME_OPTIONS.find((theme) => theme.name === specimen.name)!.scheme,
      );
    }
    expect(new Set(THEME_SPECIMENS.map((specimen) => specimen.kind)).size).toBeGreaterThanOrEqual(
      6,
    );
    expect(RASTER_Z_DOMAIN[0]).toBeLessThan(RASTER_Z_DOMAIN[1]);
    // Macdonell man-counts (thumbnail window); mid pin sits inside observed z.
    expect(RASTER_Z_DOMAIN[0]).toBeGreaterThan(0);
    expect(RASTER_Z_DOMAIN[1]).toBeLessThanOrEqual(100);
  });

  it("reports incompatible schemes and palette exhaustion through public boundaries", () => {
    expect(colorBehaviorEvidence()).toEqual({
      incompatible: {
        code: "scale-scheme-type",
        path: "/scales/color/scheme",
        message: 'The categorical scheme "ipsum" cannot be used with a sequential color scale.',
        fix: 'Use "viridis" or provide a sequential range of #rgb/#rrggbb stops.',
      },
      cycle: {
        code: "palette-exhausted",
        message:
          "More than 2 discrete values; cycling the palette. Consider an explicit domain or a larger range. (Warned once.)",
      },
      error: {
        code: "palette-exhausted",
        path: "/scales/color",
        message:
          "Palette exhausted: 3 discrete values but range has only 2 entries and onExhaust is 'error'. Provide a larger range or an explicit domain.",
      },
    });
  });
});

describe("hero temperatures chart config", () => {
  it("keeps key and month breaks stable for TemperaturesSpecimen", () => {
    expect(TEMPERATURES_CHART.key).toBe("id");
    expect([...TEMPERATURES_CHART.monthBreaks]).toEqual([...MONTH_BREAKS]);
  });
});
