/**
 * Thin name lists for docs client chrome (ReferenceLede, etc.).
 *
 * Do not import these from `@ggsvelte/spec` on client routes: the package
 * barrel co-chunks with the ggsvelte-spec graph. Parity is locked by
 * scripts/docs-known-names-parity.test.ts against @ggsvelte/spec.
 */

export const KNOWN_GEOMS = [
  "point",
  "line",
  "path",
  "col",
  "bar",
  "histogram",
  "freqpoly",
  "area",
  "rule",
  "hline",
  "vline",
  "text",
  "label",
  "smooth",
  "quantile",
  "boxplot",
  "density",
  "errorbar",
  "linerange",
  "pointrange",
  "crossbar",
  "rect",
  "tile",
  "raster",
  "ribbon",
  "segment",
  "count",
  "violin",
  "function",
  "polygon",
  "hex",
  "bin_2d",
  "abline",
  "curve",
  "contour",
  "density_2d",
  "density_2d_filled",
  "dotplot",
  "map",
  "sf",
  "sf_text",
  "sf_label",
  "blank",
  "jitter",
  "spoke",
  "rug",
  "step",
  "qq",
  "qq_line",
] as const;

export type DocsGeomName = (typeof KNOWN_GEOMS)[number];

export const KNOWN_STATS = [
  "identity",
  "unique",
  "manual",
  "connect",
  "count",
  "bin",
  "bin_hex",
  "bin_2d",
  "smooth",
  "quantile",
  "boxplot",
  "density",
  "summary",
  "sum",
  "ydensity",
  "function",
  "ecdf",
  "summary_bin",
  "contour",
  "align",
  "density_2d",
  "density_2d_filled",
  "bindot",
  "ellipse",
  "sf",
  "sf_coordinates",
  "qq",
  "qq_line",
] as const;

export type DocsStatName = (typeof KNOWN_STATS)[number];
